<?php $db = new Application_Model_DbTable_DbVdGlobal();
$db_select = new Application_Model_DbTable_DbGlobalselect();
$lang =$db->getLaguage();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$menu_items = $db_select->getMenuItems();
?>
<head>
	<meta charset="UTF-8">
	<title>Cam App Technology</title>	

<script>
var baseurl = '<?php echo $this->baseUrl();?>';
<?php if ($lang==1){?>
var monthNames = [
                  "Jan", "Feb", "Mar",
                  "Apr", "May", "Jun", "Jul",
                  "Aug", "September", "Oct",
                  "Nov", "Dec"
                ];
<?php }else{?>
var monthNames = [
              "មករា", "កុម្ភៈ", "មិនា",
              "មេសា", "ឧសភា", "មិថុនា", "កក្កដា",
              "សីហា", "កញ្ញា", "តុលា",
              "វិច្ឆិការ", "ធ្នូ"
            ];
<?php }?>
</script>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
<script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
	<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
	<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
	<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>
	<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/main.css' type='text/css' media='all' />

</head>
<section id="static-image2" class=" static-image-2" >
			<div class="container search-bar search-bar-version4">
				<div id="advanced-search-widget-version2" class="home-search">
					<div class="">
						<div class="advanced-search-widget-content">
							<div class="col-md-12">
							<form id="frmadvancesearch" action="<?php echo $this->url(array("module"=>'default','controller'=>'listads','action'=>'advancesearch'));?>" method="post" id="views-exposed-form-search-view-other-ads-page" accept-charset="UTF-8">
								<div class="col-md-3">
									<div class="views-widget">
										<div class="control-group form-type-textfield form-item-search-api-views-fulltext form-item">
											<div class="controls"> 
												<input placeholder="<?php echo $tr->translate("Search your keyword here");?>..." type="text" id="edit-search-api-views-fulltext" name="keywork_search" value="<?php echo $this->search['keywork_search'];?>" size="30" maxlength="128" class="form-text">
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-3">
									<select id="category_search" name="category_search" class="form-select" onchange="getControll();" >												
										<option value="-1" selected="selected"><?php echo $tr->translate("Choose Category");?></option>
										<?php 
											$db = new Application_Model_DbTable_DbVdGlobal();
											$rscate = $db->getCategory();
											if(!empty($rscate)){
												foreach($rscate as $rsc){
											?>
												<option value="<?php echo $rsc['id'];?>" <?php if($this->search['category_search']==$rsc['id']){ echo'selected="selected"';}?> ><?php echo $rsc['name'];?></option>
											<?php }
											} 
										?>
								   </select>
								</div>
								<div class="col-md-3">
									<div id="edit-ad-location-wrapper" class="views-exposed-widget views-widget-filter-field_ad_location">
										<div class="views-widget"><!--  onclick="advancesearch();" -->
											<div class="control-group form-type-select form-item-ad-location form-item">
												<button class="btn btn-primary form-submit" id="edit-submit-search-view" name="submit_search" value="Search Now" type="button" onclick="advancesearch();" ><span><?php echo $tr->translate("Search Now");?><i class="fa fa-search"></i></span></button>
											</div>
										</div>
									</div><!--  -->
								</div>
								<label id="lbl_controlsearch" style="width:100%;"></label>
								<div style="clear:both;"></div>
								<div class="col-md-3">
									<select id="location_search" name="location_search" class="form-select locationRadius" style="display: none;" onchange="getAllDistrict();">
										<option value="-1"><?php echo $tr->translate("Choose Location");?></option>
										<?php 
											$db = new Application_Model_DbTable_DbGlobalselect();
											$rslocation = $db->getAllLocation();
											if(!empty($rslocation)){
												foreach($rslocation as $rsl){
											?>
												<option value="<?php echo $rsl['id'];?>" <?php if($this->search['location_search']==$rsl['id']){ echo'selected="selected"';}?>><?php echo $rsl['province_name'];?></option>
											<?php }
											} 
										?>
									</select>
								</div>
								<div class="col-md-3">
									<label id="lbl_district">
										<select id="district" name="district" class="form-select col-md-12">
											<option value="-1" selected="selected"><?php echo $tr->translate("Choose Distict");?></option>
										</select>
									</label>
								</div>
								<div class="col-md-3">
									<label id="lbl_commune">
										<select id="commune" name="commune" class="form-select col-md-12">
											<option value="-1" selected="selected"><?php echo $tr->translate("Choose Commune");?></option>
										</select>
									</label>
								</div>
								<div class="col-md-3">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>	
			</div>
			<div class="banner-cat-container">
				<div class="container">		
					<div id="main-category">
						<div  class="pos-relative">
						</div>
					</div>
					<div class="tab-content">
					</div>
				</div>
				<span style="clear: both;"></span>
			</div>	
				<span style="clear: both;"></span>		
			
	</section>
	<span style="clear: both;"></span>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script src="<?php echo $this->baseUrl()."/template/js/custom.js";?>"></script>
	<script src="<?php echo $this->baseUrl()."/template/js/bootstrap.min.js"; ?>"></script>
	<div class="page">
		<div class="breadcrumb">
			<div class="container">
				<ul class="breadcrumb">
				  <li><a href="<?php echo $this->baseUrl().""?>"><i class="fa fa-home"></i><?php echo $tr->translate("Home");?></a></li>
				   <li><a href="<?php echo $this->baseUrl()."/listads/index?all_category.html"?>"><?php echo $tr->translate("All Categories");?></a></li>
				  <li><?php echo $tr->translate("Advance Search");?></li>
				</ul>
			</div>
		</div>
		<div class="all-categories section">
			<div class="container">
				<div class="row clearpadding">
					<div class="col-md-2 col-sm-3 leftblog" style=" height:500px;background:#fff;">
						<img src="<?php echo $this->baseUrl()."/images/minyuan.gif"; ?>" />
					</div><!-- col-sm-4 -->
					<div class="col-md-8 col-sm-7" style="border-left:1px solid #eee;border-right:1px solid #eee;">
						<div class="category-adds">
									<div class="tab-view" style="width:100%;">
										<ul class="list-inline advance">
											<li class="small-view-tab active"><i class="fa fa-th"></i></li>
											<li class="list-view-tab"><i class="fa fa-th-list"></i></li>
										</ul>
									</div>
								<div class="category-tab"  >
								  	<div class="tab-content small-view-tab">
								    	<div role="tabpanel" class="tab-pane active" id="recent">
								    		<ul>
								    			<label id="lbl_adsshow" style="width: 100%;">
											<?php 
											if(!empty($this->rsads))foreach($this->rsads as $rs){?>
								    			<li class="item-wrap">
									    				<div class="item ad-box ">
																<div class="item-image">
																	<a href="<?php echo $this->baseUrl()."/listads/detail/ads/".$rs['alias'].".html";?>">
																	<?php if (!empty($rs['images'])){?>
																		<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rs['image_feature']; ?>" alt=""  />
																	<?php }else{?>
																		<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
																	<?php }?>
																	</a>
																	<div class="additional-buttons">
																		<span class="quickview" onClick="getAdsDetail('<?php echo $rs['alias'];?>');" ><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
																		<div class="sold-by-container">
																			<a title="<?php echo $rs['store_title'];?>" href="<?php echo $this->baseUrl()."/store/index?store=".$rs['store_alias'].".html";?>"><span><?php echo $tr->translate("Store");?> </span> : <?php echo $rs['store_title'];?></a>
																		</div>
																	</div>
																</div>
																<div class="item-price">
																	<span>$<?php echo number_format($rs['price'],2);?></span>
																</div> 
															<div class="item-description">
																<div class="item-title">
																	<h3>
																	<a href="<?php echo $this->baseUrl()."/listads/detail/ads/".$rs['alias'].".html";?>">
																		<?php echo substr($rs['ads_title'],0,100);?>
																	</a>
																	</h3>
																</div>
																<div class="item-info">
																	<p class="description"><?php 
																	$str1 = utf8_encode($rs['description']);
																	$description = substr($str1, 0, 600);
																	echo utf8_decode($description); 
																	?></p>
																	<ul>
																	   <li ><?php echo $rs['category_name'];?></li>
																	  <?php if (!empty($rs['commune_name'])){?>
																     	<li class="list_view"> <?php echo $rs['commune_name']." ,";?></li>
																     	<?php }?>
																	   <?php if (!empty($rs['district_name'])){?>
																   		<li class="list_view"> <?php echo $rs['district_name']." ,";?></li>
																   		<?php }?>
																     	<li class="province"> <?php echo $rs['province_name'];?></li>
																	</ul>
																</div>
															</div><!-- item-description -->
															<div class="footerads" >
																	<ul >
																	   <li> <i class="fa fa-eye"></i><?php echo $rs['viewer'];?> Views</li>
																	   <li> <i class="fa fa-calendar"></i><?php echo date("M d, Y",strtotime($rs['publish_date']));?></li>
																	</ul>
															</div>
														</div><!-- item -->
								    			</li><!-- item-wrap -->
								    			<?php }?>
								    			</lable>
								    		</ul>
								    	</div> <!--tab-pane-->
								  	</div>
								</div>
						</div>
						<div class="pager-section">
							<ul class="pagination ">
								<li><a href="#"><i class="fa fa-chevron-left"></i></a></li>
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li class="active"><a href="#">4</a></li>
								<li><a href="#">5</a></li>
								<li><a href="#">6</a></li>
								<li><a href="#">7</a></li>
								<li><a href="#"><i class="fa fa-chevron-right"></i></a></li>
							</ul>
						</div><!-- pager-section -->
					</div><!-- end blog center -->
					<div class="col-md-2 col-sm-3" style="height:500px;background:#fff;border-right:1px solid #eee;">
						<img src="<?php echo $this->baseUrl()."/images/minyuan.gif"; ?>" />
					</div><!-- col-sm-4 -->
				</div>
			</div>
		</div> <!-- all-categories -->
	</div>	<!-- page -->
	<div id="load-wrapper" class="load-wrapper">
		<div class="load-blog">
			<div class="loader">
				<img class="loading" src="<?php echo $this->baseUrl()."/images/loader-light.gif";?>" />
			</div>
		</div>
	</div>
	
	<?php
   $page = $this->baseurl();
	echo $this->render('sideright.phtml');
	echo $this->render('frontbottom.phtml');?>
	<script>
	jQuery(document).ready(function($){
		<?php if($this->search['category_search']>0){ ?>
		getControll();
		<?php }?>
		});
	var url_search = '<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'searchajax'));?> ';
	   function advancesearch(){
	   var formData = $('#frmadvancesearch').val(); 
	   $("#load-wrapper").css("display", "block");
	   $.ajax({
	        url: url_search,
	        type: "post",
	        data: $('#frmadvancesearch').serialize(),		
	        success: function(dataproduct){
	        	$("#load-wrapper").css("display", "none");
	        	document.getElementById('lbl_adsshow').innerHTML=dataproduct;					
			},
				error: function(err) {
					 $("#load-wrapper").css("display", "none");
				}
			});
	}	
   var url_getcontrol = '<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'getcontroller'));?> ';
   function getControll(){
	   var category_search = $('#category_search').val(); 
		   $.ajax({
				url: url_getcontrol,
				type: "post",
				data:{'category_id':category_search},
				success: function(data){
					//alert(data);
					
					document.getElementById('lbl_controlsearch').innerHTML=data;
					var noResult = jQuery(".form-select").data('noResult');
					jQuery(".form-select").chosen({});
				},
				error:function(err){
				}
			});
	}		
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	$.ajax({
		url: url_changelang,
		type: "post",
		data:{'lange':lang},
		success: function(data){
			location.reload();
		},
		error:function(err){
		}
	});
}
	</script>
	<script>
var url_district = '<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'get-districtbyid'));?> ';
function getAllDistrict(){
	var pro_id = $('#location_search').val();
	$.ajax({
		url: url_district,
		type: "post",
		data:{'pro_id':pro_id},
		success: function(data){
			datars = $.parseJSON(data);
			stringhtml='<select onchange="getCommuneById()" id="district" name="district" class="form-select">';
			stringhtml+='<option value="0" selected="selected"><?php echo $tr->translate("Choose Distict");?></option>';
			for(j=0;j<datars.length;j++){
				stringhtml+='<option value="'+datars[j].id+'">'+datars[j].district_name+'</option>';
			}
			stringhtml+='</select';
			document.getElementById('lbl_district').innerHTML=stringhtml;
			stringcommune='<select id="commune" name="commune" class="form-select"><option><?php echo $tr->translate("Choose Commune");?></option></select>';
			document.getElementById('lbl_commune').innerHTML=stringcommune;
			var noResult = jQuery(".form-select").data('noResult');
			jQuery(".form-select").chosen({});
		},
		error:function(err){
			alert(err);
		}
	});
}
var url_commune = '<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'get-communebyid'));?> ';
function getCommuneById(){
	var commune_id = $('#district').val();
	if(commune_id==0){return false;}
	$.ajax({
		url: url_commune,
		type: "post",
		data:{'distict_id':commune_id},
		success: function(data){
			datars = $.parseJSON(data);
			stringhtml='<select id="commune" name="commune" class="form-select">';
			stringhtml+='<option value="0" selected="selected"><?php echo $tr->translate("Choose Commune");?></option>';
			for(j=0;j<datars.length;j++){
				stringhtml+='<option value="'+datars[j].id+'">'+datars[j].commune_name+'</option>';
			}
			stringhtml+='</select';
			document.getElementById('lbl_commune').innerHTML=stringhtml;
			var noResult = jQuery(".form-select").data('noResult');
			jQuery(".form-select").chosen({});
		},
		error:function(xhr){
		}
	});
}
</script>