<!DOCTYPE html>
<html lang="en">
  
<!-- Mirrored from template.gridbootstrap.com/avt/details.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 04 Mar 2017 04:03:52 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Theme Region">
   	<meta name="description" content="">

    <title>Advert | Ad Details | Classifieds Ads Template</title>

   <!-- CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" >
    <link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/owl.carousel.css">  
    <link rel="stylesheet" href="css/main.css">  
    <link rel="stylesheet" href="css/responsive.css">
	
	
	<!-- font -->
	<link href='https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300' rel='stylesheet' type='text/css'>

	<!-- favicon icon -->
	<link rel="shortcut icon" type="image/x-icon" href="images/ico/favicon.ico">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<div class="page">
		<div class="all-categories section">
			<div class="container">
				<div class="ad-details">
					<div class="row">
						<div class="col-md-8 col-sm-7">
							<div class="item">
		    					<div class="detail-item-image item-image carousel slide" data-ride="carousel">
		    						<div class="carousel-inner">
		    							<div class="item active">
		    								<img src="<?php echo $this->baseUrl()."/imagesphotoA10_1.jpg"?>" alt="" class="img-responsive">
		    							</div>
		    							<div class="item">
		    								<img src="<?php echo $this->baseUrl()."/imagesphotoA10_1.jpg"?>" alt="" class="img-responsive">
		    							</div>
		    							<div class="item">
		    								<img src="<?php echo $this->baseUrl()."/imagesphotoA10_1.jpg"?>" alt="" class="img-responsive">
		    							</div>
		    						</div>
		    						<a class="left-control" href="-3.html" role="button" data-slide="prev">
									    <i class="fa fa-angle-left" aria-hidden="true"></i>
									    <span class="sr-only">Previous</span>
								  	</a>
									  	<a class="right-control" href="-3.html" role="button" data-slide="next">
									    <i class="fa fa-angle-right" aria-hidden="true"></i>
									    <span class="sr-only">Next</span>
								  	</a>
								  	<div class="item-price">
										<span>$399</span>
									</div>
								</div>
								<div class="details-description">
									<div class="item-info item-meta">
										<div class="item-post-date">
											<span><i class="fa fa-clock-o"></i>Dec 28, 14:54 pm</span>
										</div>
										<div class="ad-title">
											<h3>Fast Laptop Computer Intel Dual Core</h3>
										</div>
										<ul class="list-inline product-social">
											<li><a href="#"><i class="fa fa-bookmark-o" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a></li>
										</ul> 
									</div><!-- item-info -->
									<div class="item-info">
										<h4>Description</h4>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
									</div><!-- item-info -->
									<div class="item-info">
										<h4>Other Info</h4>
										<ul>
											<li>Consectetur adipisicing elit</li>
											<li>Sed do eiusmod tempor incididunt</li>
											<li>Quis nostrud exercitation ullamco </li>
											<li>Labore et dolore magna aliqua</li>
											<li>Ut enim ad minim veniam</li>
											<li>Consectetur adipisicing elit</li>
											<li>Sed do eiusmod tempor incididunt</li>
											<li>Quis nostrud exercitation ullamco </li>
											<li>Labore et dolore magna aliqua</li>
											<li>Ut enim ad minim veniam</li>
											<li>Consectetur adipisicing elit</li>
											<li>Sed do eiusmod tempor incididunt</li>
										</ul>
									</div><!-- item-info -->
								</div>
		    				</div><!-- item -->
		    				<div class="location-map">
		    					<h4>Seller Location</h4>
		    					<div id="gmap"></div>
		    				</div><!-- location-map -->
						</div>


						<div class="col-sm-5 col-md-4">
							<div class="side-bar">
								<div class="item-author widget">
									<h4>Seller Info</h4>
									<div class="row">
										<div class="col-md-4">
											<div class="seller-image">
												<img class="img-responsive" src="<?php echo $this->baseUrl()."/imagesphotoA10_1.jpg"?>" alt="seller">
											</div>
										</div>
										<div class="col-md-8">
											<div class="seller-info">
												<p><span>Seller:</span> <a href="#">Mark Bartlar</a></p>
												<address>
													<span>Address:</span> 151/7, Green Road, NY, USA
												</address>
												<p><span>Phone :</span> +012 012 345 678 </p>
												<p><a href="#">View other items of this seller</a></p>
											</div>
										</div>
									</div>
								</div>
								<div class="contact-seller widget">
									<h4>Contact Seller</h4>
									<form id="contact-form" class="contact-form" name="contact-form" method="post" action="#">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Name">
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<input type="email" class="form-control" required="required" placeholder="Email Id">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Subject">
												</div> 
											</div> 
											
											<div class="col-md-12">
												<div class="form-group">
													<textarea name="message" id="message" required="required" class="form-control" rows="7" placeholder="Message"></textarea>
												</div>             
											</div>     
										</div>
										<div class="form-group">
											<button type="submit" class="btn btn-primary">Submit Message</button>
										</div>

									</form>
								</div>
							</div><!-- side-bar -->
						</div>
					</div>
				</div>
			</div>
		</div> <!-- all-categories -->
	</div>	<!-- page -->
	<!-- footer -->
     <!-- JS -->
    <script src="js/jquery.min.js"></script>
    <script src="js/modernizr.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script src="js/gmaps.min.js"></script>
	<script src="js/map.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>