<!DOCTYPE html>
  <?php 
  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $ads = $this->adsDetail;
  if (!empty($ads['logo_store'])){
  	$image = "store/".$ads['logo_store'];
  }else{
  	$image = "profile.jpg";
  }
  
  ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="cam app technology">
    <title><?php echo $ads['ads_title'];?></title>
   	<meta name="description" content="<?php echo $ads['ads_title'];?>">
    <link href="<?php echo $this->baseUrl();?>/template/css/main.css" media="screen" rel="stylesheet" type="text/css">
	<meta property="og:title" content="">
	<meta property="og:site_name" content="www.cam-app.com">
	<meta property="og:url" content="<?php echo "http://.$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]";?>">
	<meta property="og:description" content="<?php echo $ads['description'];?>">
	<meta property="og:image" content="<?php echo $this->baseUrl()."/images/adsimg/".$ads['image_feature']; ?>" >
	<meta property="og:type" content="website">
  </head>

  <body>
	<div class="page">
		<div class="breadcrumb">
			<div class="container">
				<ul class="breadcrumb">
				  <li><a href="<?php echo $this->baseUrl().""?>"><i class="fa fa-home"></i><?php echo $tr->translate("Home");?></a></li>
				  <li><a href="<?php echo $this->baseUrl()."/listads/index?all_category.html"?>"><?php echo $tr->translate("All Categories");?></a></li>
				  <?php if (!empty($ads['parent_category_name'])){?>
				  <li><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$ads['parent_alias_category'].".html";?>"><?php echo $ads['parent_category_name'];?></a></li>
				  <?php }?>
				   <?php if (!empty($ads['category_name'])){?>
				  <li><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$ads['alias_category'].".html";?>"><?php echo $ads['category_name'];?></a></li>
				  <?php }?>
				</ul>
			</div>
		</div>
		<div class="all-categories section">
			<div class="container">
				<div class="ad-details">
					<div class="row">
						<div class="col-md-8 col-sm-7">
							<div class="item">
								<div class="item-info item-meta">
									<div class="ad-title">
										<h3><?php echo $ads['ads_title'];?></h3>
									</div>
									<div class="viewer">
										<div class="item-post-date">
											<span><i class="fa fa-calendar"></i><?php echo date("d-m-Y",strtotime($ads['date_modified']));?></span>
											<span><i class="fa fa-eye"></i><?php echo $ads['viewer'];?> <?php echo $tr->translate("Views");?> </span> 
										</div>
										<div class="social-share">
											<div class="fb-share-button" data-href="<?php echo $this->baseUrl()."/listads/detail/ads/".$ads['alias'].".html";?>" data-layout="button" data-size="large" data-mobile-iframe="false"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%2Fcam-adsproject%2Ftrunk%2Fpublic%2Flistads%2Fdetail%2Fads%2Fiphone-5s-64GB-for-sale-quality-99225&amp;src=sdkpreparse">Share</a></div>
										</div>
									</div>
								</div><!-- item-info -->
			    				<div class="slide-content" style="max-width:100%;">
						    		  <div class="blog-main-slide">
						    		    <?php $images = explode(',', $ads['images']);
										$k=0;
									    foreach ($images as $i){$k++;
									    ?>
									    <img class="slides-detail" src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" >
								       <?php }?>
									  </div>
									  <div class="thumnail-blog">
									   
									    <?php $images = explode(',', $ads['images']);
										$k=0;
									    foreach ($images as $i){$k++;
									    ?>
									     <div class="thumnail-image-slide">
									      <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" style="width:100%" onclick="currentSlide(<?php echo $k;?>)">
									    </div>
									    <?php }?>
									  </div>
									   <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
									  <a class="next" onclick="plusSlides(1)">&#10095;</a>
									  <div class="item-price">
										<span><?php echo '$ '.number_format($ads['price'],2);?></span>
									</div>
								</div>
								<div class="details-description">
									<div class="item-info">
										<ul class="detail-ads">
											<li><span class="field-title"><?php echo $tr->translate("Price");?></span> : <span class="field-value"><?php echo '$ '.number_format($ads['price'],2);?></span></li>
											<?php if(!empty($this->rsattr))foreach ($this->rsattr as $attr){?>
									 		<li><span class="field-title"><?php echo $attr['control_name'];?></span> : <span class="field-value"><?php echo $attr['control_value'];?></span></li>
									 		<?php }?>
									 	</ul>
										<h4><?php echo $tr->translate("Description");?></h4>
										<pre><?php echo $ads['description'];?></pre>
									</div><!-- item-info -->
									<div class="item-info">
										<h4><?php echo $tr->translate("Contacts");?></h4>
										<ul class="detail-ads contact">
									 		<li><span class="field-title"><?php echo $tr->translate("Contacts Name");?></span> : <span class="field-value"><?php echo $ads['contact_name'];?></span></li>
									 		<li><span class="field-title"><?php echo $tr->translate("Phone");?></span> : <span class="field-value"><?php echo $ads['phone1']; if (!empty($ads['phone2'])){echo "/".$ads['phone2'];}?></span></li>
									 		<li><span class="field-title"><?php echo $tr->translate("Location");?></span> : <span class="field-value"><?php echo empty($ads['district_name'])?'':$ads['district_name']." , "; echo empty($ads['commune_name'])?'':$ads['commune_name']." , "; echo $ads['province_name'];?></span></li>
									 		<?php if (!empty($ads['address'])){?>
									 		<li><span class="field-title"><?php echo $tr->translate("Address");?></span> : <span class="field-value"><?php echo $ads['address'];?></span></li>
									 		<?php }?>
									 	</ul>
									</div>
									<div class="box-contact">
										<p><?php echo $tr->translate("Call to");?> <strong><?php echo $ads['phone1']; if (!empty($ads['phone2'])){echo "/".$ads['phone2'];}?></strong> for more information, don't forget to mention that you found this ad on Cam-App.com.</p>
									</div>
								</div>
		    				</div><!-- item -->
		    				<!--<div class="location-map">
		    					<h4>Seller Location</h4>
		    					<div id="gmap"></div>
		    				</div> location-map -->
		    				<?php if (!empty($this->relate_pro)){?>
		    				<div class="full">
		    					<div class="block-title-cate">
										<p class="b-title"><span><i class="fa fa-link"></i><?php echo $tr->translate("Related Ads");?> </span></p>
								</div>
								<div class="pane">
					    				<div class=" owl-carousel" data-items="3" data-items-tab-ls="2" data-items-tab="2" data-autoplay="false" data-gutter="4" data-autoplay-speed="1500" data-delay="1000" data-loop="true" data-nav="false"  data-dots="false">
				    					<?php //for($j=0;$j<=10;$j++){
  												foreach ($this->relate_pro as $relate){
  										?>
										<div class="ad-box ">
											<div class="ads-img-wrapper">
												<a class="ad-image box" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$relate['alias'];?>" title="<?php echo $relate['ads_title'];?>" >
													<?php if (!empty($relate['image_feature'])){?>
														<img src="<?php echo $this->baseUrl()."/images/adsimg/".$relate['image_feature']; ?>" alt=""  />
													<?php }else{?>
														<img src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" alt=""  />
													<?php }?>
												</a>
												<div class="additional-buttons">
													<span class="quickview" onClick="getAdsDetail('<?php echo $relate['id'];?>');"><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
													<div class="sold-by-container">
														<a title="<?php echo $relate['author'];?>" href="#"><span><?php echo $tr->translate("Posted By");?> </span><?php echo $relate['author'];?></a>
													</div>
												</div>
											</div>
											<div class="ads-title">
												<h4><a class="ads-title" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$relate['alias'].".html";?>" ><?php echo $relate['ads_title'];?></a></h4>
											 </div>
											 <div class="ads-price">
												<h4><a class="ads-price" href="#" ><?php echo '$ '.number_format($relate['price'],2);?></a></h4>
											 </div>
											 <div class="item-info">
												<ul>
												   <li><?php echo $relate['parent_category_name'];?></li>
												   <li><?php echo $relate['province_name'];?></li>
												</ul>
											</div>
											<div class="footerads" >
												<ul >
												   <li> <i class="fa fa-eye"></i><?php echo $relate['viewer'];?> <?php echo $tr->translate("Views");?></li>
												   <li> <i class="fa fa-calendar"></i><?php echo date("d-m-Y", strtotime($relate['date_modified']));?></li>
												</ul>
											</div>
										</div>
									<?php }?>
				    				</div>
			    				</div>
		    				</div>
		    				<?php }?>
						</div>
						<div class="col-sm-5 col-md-4 detail-right">
							<div class="side-bar">
								<div class="item-author widget">
									<h4><?php echo $tr->translate("Store Information");?></h4>
									<div class="row">
										<div class="col-md-4">
											<div class="seller-image">
												<img class="img-responsive" src="<?php echo $this->baseUrl().'/images/'.$image;?>" alt="<?php echo $ads['author'];?>"  />
											</div>
										</div>
										<div class="col-md-8">
											<div class="seller-info">
												<p><span><?php echo $tr->translate("Store");?> :</span> <a class="author" href="#"><?php echo $ads['store_title'];?></a></p>
												<address>
													<?php if (!empty($ads['store_address'])){?>
														<span><?php echo $tr->translate("Address");?> :</span> <?php echo $ads['store_address'];?>
													<?php }else{?>
														<span><?php echo $tr->translate("Address");?> :</span> <?php echo $ads['author_address'];?>
													<?php }?>
												</address>
												<p>
													<?php if (!empty($ads['store_phone'])){?>
														<span><?php echo $tr->translate("Phone");?> :</span> <?php echo $ads['store_phone'];?> 
													<?php }else{?>
														<span><?php echo $tr->translate("Phone");?> :</span> <?php echo $ads['author_phone'];?> 
													<?php }?>
												</p>
												<p><a  href="<?php echo $this->baseUrl()."/store/index?store=".$ads['store_alias'].".html";?>"><?php echo $tr->translate("Visit Store");?></a></p>
											</div>
										</div>
									</div>
								</div>
								<div class="safty widget">
									<div class="safty">
										<span class="title" style="border:none">សុវត្ថិភាពក្នុងការទិញទំនិញលើ cam-app.com៖</span>
										<p style="margin-top:3px"><strong>រាល់ការទិញទំនិញមិនត្រូវធ្វើការផ្ញើប្រាក់ទៅមុនជាដាច់ខាត</strong> ត្រូវជួបអ្នកលក់នៅទីតាំងដែលមានសុវត្ថិភាព និងសូមពិនិត្យមើលទំនិញមុនពេលដែលបង់ប្រាក់។</p>
									</div>
								</div>
								<div class="contact-seller widget">
									<h4><?php echo $tr->translate("Contact Seller");?></h4>
									<form id="contact-form" class="contact-form" name="contact-form" method="post" action="#">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Name">
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<input type="email" class="form-control" required="required" placeholder="Email Id">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Subject">
												</div> 
											</div> 
											
											<div class="col-md-12">
												<div class="form-group">
													<textarea name="message" id="message" required="required" class="form-control" rows="7" placeholder="Message"></textarea>
												</div>             
											</div>     
										</div>
										<div class="form-group">
											<button type="submit" class="btn btn-primary"><?php echo $tr->translate("Submit Message");?></button>
										</div>

									</form>
								</div>
							</div><!-- side-bar -->
						</div>
					</div>
				</div>
			</div>
		</div> <!-- all-categories -->
	</div>	<!-- page -->
	<!-- footer -->
	<script>
	/* slide detail*/ 
	var indexSlide=1;
		showSlideDetail(indexSlide);
	function plusSlides(n) {
	  showSlideDetail(indexSlide += n);
	}
	function currentSlide(n) {
	  showSlideDetail(indexSlide = n);
	}
	function showSlideDetail(n) {
	  var i;
	  var x = document.getElementsByClassName("slides-detail");
	 
	  if (n > x.length) {indexSlide = 1}
	  if (n < 1) {indexSlide = x.length}
	  for (i = 0; i < x.length; i++) {
		 x[i].style.display = "none";
	  }
	  x[indexSlide-1].style.display = "initial";
	
	}
	</script>
  </body>
</html>