<!DOCTYPE html>
  <?php 
  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $ads = $this->adsDetail;
  if (!empty($ads['author_photo'])){
  	$image = $ads['author_photo'];
  }else{
  	$image = "profile.jpg";
  }
  ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="cam app technology">
   	<meta name="description" content="<?php echo $ads['ads_title'];?>">
    <title><?php echo $ads['ads_title'];?></title>
   <!--  <link rel="stylesheet" href="css/bootstrap.min.css" >
    <link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/owl.carousel.css">  
    <link rel="stylesheet" href="css/main.css">  
    <link rel="stylesheet" href="css/responsive.css">-->
    <link href="<?php echo $this->baseUrl();?>/template/css/main.css" media="screen" rel="stylesheet" type="text/css">
	<!-- font -->

  </head>

  <body>
	<div class="page">
		<div class="breadcrumb">
			<div class="container">
				<ul class="breadcrumb">
				  <li><a href="<?php echo $this->baseUrl()."/index"?>"><i class="fa fa-home"></i>Home</a></li>
				  <li><a href="<?php echo $this->baseUrl()."//listads/index"?>">All Categories</a></li>
				  <?php if (!empty($ads['parent_category_name'])){?>
				  <li><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$ads['parent_alias_category'];?>"><?php echo $ads['parent_category_name'];?></a></li>
				  <?php }?>
				   <?php if (!empty($ads['category_name'])){?>
				  <li><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$ads['alias_category'];?>"><?php echo $ads['category_name'];?></a></li>
				  <?php }?>
				</ul>
			</div>
		</div>
		<div class="all-categories section">
			<div class="container">
				<div class="ad-details">
					<div class="row">
						<div class="col-md-8 col-sm-7">
							<div class="item">
		    				<div class="slide-content" style="max-width:100%;">
					    		  <div class="blog-main-slide">
				    		  		  <?php if (!empty($ads['image_feature'])){?>
									  	<img class="slides-detail" src="<?php echo $this->baseUrl()."/images/adsimg/".$ads['image_feature']; ?>" >
									  <?php }else{?>
									  	<img class="slides-detail" src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" >
									  <?php }?>
									  <?php for ($i=1; $i<=6; $i++){ ?>
									 	 <img class="slides-detail" src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" >
									  <?php }?>
								  </div>
								  <div class="thumnail-blog">
								    <div class="thumnail-image-slide">
								     <?php if (!empty($ads['image_feature'])){?>
								      <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/".$ads['image_feature']; ?>" style="width:100%" onclick="currentSlide(1)">
							    	 <?php }else{?>
							    	  <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" style="width:100%" onclick="currentSlide(1)">
						    	     <?php }?>
								    </div>
								    <?php for ($i=1; $i<=6; $i++){ ?>
								    <div class="thumnail-image-slide">
								      <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" style="width:100%" onclick="currentSlide(<?php echo $i+1;?>)">
								    </div>
								      <?php }?>
								  </div>
								   <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
								  <a class="next" onclick="plusSlides(1)">&#10095;</a>
								  <div class="item-price">
									<span><?php echo '$ '.number_format($ads['price'],2);?></span>
								</div>
							</div>
								<div class="details-description">
									<div class="item-info item-meta">
										<div class="ad-title">
											<h3><?php echo $ads['ads_title'];?></h3>
										</div>
										<div class="viewer">
											<div class="item-post-date">
												<span><i class="fa fa-eye"></i><?php echo $ads['viewer'];?> Views </span> 
												<span><i class="fa fa-calendar"></i><?php echo date("d-m-Y",strtotime($ads['date_modified']));?></span> 
											</div>
											<div class="social-share">
												<div class="fb-share-button" data-href="<?php echo $this->baseUrl()."/listads/detail/ads/".$ads['alias'];?>" data-layout="button" data-size="large" data-mobile-iframe="false"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%2Fcam-adsproject%2Ftrunk%2Fpublic%2Flistads%2Fdetail%2Fads%2Fiphone-5s-64GB-for-sale-quality-99225&amp;src=sdkpreparse">Share</a></div>
											</div>
										</div>
									</div><!-- item-info -->
									<div class="item-info">
										<h4>Description</h4>
										<p><?php echo $ads['description'];?></p>
									</div><!-- item-info -->
									 <div class="item-info">
										<h4>Other Info</h4>
										<ul>
										<?php if(!empty($this->rsattr))foreach ($this->rsattr as $attr){?>
											<li><?php echo $attr['control_name'];?> : <?php echo $attr['control_value'];?></li>
										<?php }?>
											
											<li>Sed do eiusmod tempor incididunt</li>
											<li>Quis nostrud exercitation ullamco </li>
											<li>Labore et dolore magna aliqua</li>
											<li>Ut enim ad minim veniam</li>
											<li>Consectetur adipisicing elit</li>
											<li>Sed do eiusmod tempor incididunt</li>
											<li>Quis nostrud exercitation ullamco </li>
											<li>Labore et dolore magna aliqua</li>
											<li>Ut enim ad minim veniam</li>
											<li>Consectetur adipisicing elit</li>
											<li>Sed do eiusmod tempor incididunt</li>
										</ul>
									</div>
								</div>
		    				</div><!-- item -->
		    				<!--<div class="location-map">
		    					<h4>Seller Location</h4>
		    					<div id="gmap"></div>
		    				</div> location-map -->
		    				<?php if (!empty($this->relate_pro)){?>
		    				<div class="full">
		    					<div class="block-title-cate">
										<p class="b-title"><span><i class="fa fa-link"></i>Related Ads</span></p>
								</div>
								<div class="pane">
					    				<div class=" owl-carousel" data-items="3" data-items-tab-ls="2" data-items-tab="2" data-autoplay="false" data-gutter="4" data-autoplay-speed="1500" data-delay="1000" data-loop="true" data-nav="false"  data-dots="false">
				    					<?php //for($j=0;$j<=10;$j++){
  												foreach ($this->relate_pro as $relate){
  										?>
										<div class="ad-box ">
											<div class="ads-img-wrapper">
												<a class="ad-image box" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$relate['alias'];?>" title="<?php echo $relate['ads_title'];?>" >
													<?php if (!empty($relate['image_feature'])){?>
														<img src="<?php echo $this->baseUrl()."/images/adsimg/".$relate['image_feature']; ?>" alt=""  />
													<?php }else{?>
														<img src="<?php echo $this->baseUrl()."/images/adsimg/noimagefound.jpg"; ?>" alt=""  />
													<?php }?>
												</a>
												<div class="additional-buttons">
													<span class="quickview" onClick="getAdsDetail('<?php echo $relate['id'];?>');"><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
													<div class="sold-by-container">
														<a title="<?php echo $relate['author'];?>" href="#"><span><?php echo $tr->translate("Posted By");?> </span><?php echo $relate['author'];?></a>
													</div>
												</div>
											</div>
											<div class="ads-title">
												<h4><a class="ads-title" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$relate['alias'];?>" ><?php echo $relate['ads_title'];?></a></h4>
											 </div>
											 <div class="ads-price">
												<h4><a class="ads-price" href="#" ><?php echo '$ '.number_format($relate['price'],2);?></a></h4>
											 </div>
											 <div class="item-info">
												<ul>
												   <li><?php echo $relate['parent_category_name'];?></li>
												   <li><?php echo $relate['province_name'];?></li>
												</ul>
											</div>
											<div class="footerads" >
												<ul >
												   <li> <i class="fa fa-eye"></i><?php echo $relate['viewer'];?> Views</li>
												   <li> <i class="fa fa-calendar"></i><?php echo date("d-m-Y", strtotime($relate['date_modified']));?></li>
												</ul>
											</div>
										</div>
									<?php }?>
				    				</div>
			    				</div>
		    				</div>
		    				<?php }?>
						</div>
						<div class="col-sm-5 col-md-4">
							<div class="side-bar">
								<div class="item-author widget">
									<h4>Author Information</h4>
									<div class="row">
										<div class="col-md-4">
											<div class="seller-image">
												<img class="img-responsive" src="<?php echo $this->baseUrl().'/images/'.$image;?>" alt="<?php echo $ads['author'];?>"  />
											</div>
										</div>
										<div class="col-md-8">
											<div class="seller-info">
												<p><span>Author:</span> <a class="author" href="#"><?php echo $ads['author'];?></a></p>
												<address>
													<span>Address:</span> <?php echo $ads['author_address'];?>
												</address>
												<p><span>Phone :</span> <?php echo $ads['author_phone'];?> </p>
												<p><a href="#">View other items of this seller</a></p>
											</div>
										</div>
									</div>
								</div>
								<div class="contact-seller widget">
									<h4>Contact Seller</h4>
									<form id="contact-form" class="contact-form" name="contact-form" method="post" action="#">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Name">
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<input type="email" class="form-control" required="required" placeholder="Email Id">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="text" class="form-control" required="required" placeholder="Subject">
												</div> 
											</div> 
											
											<div class="col-md-12">
												<div class="form-group">
													<textarea name="message" id="message" required="required" class="form-control" rows="7" placeholder="Message"></textarea>
												</div>             
											</div>     
										</div>
										<div class="form-group">
											<button type="submit" class="btn btn-primary">Submit Message</button>
										</div>

									</form>
								</div>
							</div><!-- side-bar -->
						</div>
					</div>
				</div>
			</div>
		</div> <!-- all-categories -->
	</div>	<!-- page -->
	<!-- footer -->
	<script>
	/* slide detail*/ 
	var indexSlide=1;
		showSlideDetail(indexSlide);
	function plusSlides(n) {
	  showSlideDetail(indexSlide += n);
	}
	function currentSlide(n) {
	  showSlideDetail(indexSlide = n);
	}
	function showSlideDetail(n) {
	  var i;
	  var x = document.getElementsByClassName("slides-detail");
	 
	  if (n > x.length) {indexSlide = 1}
	  if (n < 1) {indexSlide = x.length}
	  for (i = 0; i < x.length; i++) {
		 x[i].style.display = "none";
	  }
	  x[indexSlide-1].style.display = "initial";
	
	}
	</script>
  </body>
</html>