<!DOCTYPE html>
<?php $menu_info = $this->menu_info; 

$db = new Application_Model_DbTable_DbGlobalselect();
?>
<html lang="en">
<?php if ($menu_info['menu_type_id']==1){ //category blog?>
<?php }else if ($menu_info['menu_type_id']==2){//category list
	$article = $db->getArcticleByCate($menu_info['category_id']);
	
	
?>
    <div class="block-content-page">
    	<div class="container clear">
        	<div class="row">
        	 <div class="col-sm-12 col-md-3 scrollspy">
                	<div id="nav-left"  class="nav-left">
                        <ul class="nav list-unstyled">
                        	<?php if (!empty($article)) foreach ($article as $ss){?>
                            <li>
                                <a href="<?php echo '#'.$ss['alias_article'];?>"><?php echo $ss['title'];?></a>
                            </li>
                            <?php }?>                                    
                        </ul>
                    </div>
                </div>
            	<div class="col-sm-12 col-md-9">
            		<?php if (!empty($article)) foreach ($article as $ss){?>
                	<!-- start div-->
                	<div id="<?php echo $ss['alias_article'];?>">
                		<div class="title-blog">
                			<h1 class="title-blog"><?php echo $ss['title'];?></h1>
                		</div>
                    	<div class="blog-content">
                    	<?php echo $ss['description'];?>
                        </div>
                    </div>
                    <?php }?>
                    <!-- end div-->
                </div>
            </div>
        </div>
    </div>
    <?php }else if ($menu_info['menu_type_id']==3){//sigle aticle?>
     <?php }else if ($menu_info['menu_type_id']==4){//Contacts?>
    <?php }?>
     <!-- start prefooter-->
     <script>
		$(function() {
		  $('a[href*="#"]:not([href="#"])').click(function() {
			  $('#nav-left a').each(function () {
				  $(this).removeClass('active');
			  });
			  var currLink = $(this);
			  currLink.addClass("active");
			  
		    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
		      var target = $(this.hash);
		      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
		      if (target.length) {
		        $('html, body').animate({
		          scrollTop: target.offset().top
		        }, 1000);
		        return false;
		      }
		
		    }
		 
		  });
		});
		$(window).scroll(function() { 
			 var scroll = $(window).scrollTop();
			 var heigtheader = $("#static-image2").height();
			 if (scroll >= heigtheader) {
				 $(".nav-left").addClass("fixed");
			 }else{
				 $(".nav-left").removeClass("fixed");
			 }

			  $('#nav-left a').each(function () {
			        var currLink = $(this);
			        var refElement = $(currLink.attr("href"));
			        if (refElement.position().top <= scroll && refElement.position().top + refElement.height() > scroll) {
			            $('#nav-left ul li a').removeClass("active");
			            currLink.addClass("active");
			        }
			        else{
			            currLink.removeClass("active");
			        }
			    });
		
		});
	</script>
</html>