<?php 
$session_lang=new Zend_Session_Namespace('lang');
$lang  = $session_lang->lang_id;
?>
<!DOCTYPE html>
<html lang="en-US">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Cam App Technology</title>	
	<link rel="shortcut icon" href="wp-content/uploads/2016/04/favicon.jpg" type="image/x-icon" />
<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />

<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />

<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />

<!--<script type='text/javascript' src='<?php //echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
 <script type='text/javascript' src='<?php //echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script> -->

<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>

<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="featured-slider-3 blog-cateory-items-slide ">
		<div class="container" >
			<div class="col-md-12 col-sm-12" >
			<div class="banner-top" style="width:100; height:100px;border:1px solid #ccc;">
			<img src="<?php echo $this->baseUrl()."/images/banner/watashi_cc3a1f.gif"?>" />
				<!-- <h2 align="center">1170x100(px)</h2> -->
			</div>
			</div>
		</div>
	</section>
	<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	?>
	<?php 
	$db = new Application_Model_DbTable_DbVdGlobal();
				
	if(!empty($this->rscate))foreach($this->rscate as $cate) {?>
	<section class="featured-slider-3 blog-cateory-items-slide ">
		<div class="container" >
			<div class="col-md-12 col-sm-12" >
			<div class="block-title-cate">
				<p class="b-title"><span><i class="fa <?php echo $cate['fontawsome_icon'];?>"></i><?php echo $cate['name']?></span></p>
				<p class="label-show-all"><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$cate['alias_category'];?>"> <?php echo $tr->translate("Show All");?></a></p>
			</div>
			<div class="full">
				<div class="pane">
					<div class=" owl-carousel" data-items="5" data-items-tab-ls="2" data-items-tab="2" data-autoplay="false" data-gutter="4" data-autoplay-speed="1500" data-delay="1000" data-loop="true" data-nav="false"  data-dots="false">
						<?php 
						$rsads = $db->getAllAdsToHomepage($cate['id']);
						foreach($rsads as $rsad) {?>
							<div class="ad-box ">
								<div class="ads-img-wrapper">
									<a class="ad-image box" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$rsad['alias'];?>" title="<?php echo $rsad['ads_title'];?>" >
									<?php if (!empty($rsad['image_feature'])){?>
										<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rsad['image_feature']; ?>" alt=""  />
									<?php }else{?>
										<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
									<?php }?>
									</a>
									<div class="additional-buttons">
										<span class="quickview"  onClick="getAdsDetail('<?php echo $rsad['id'];?>');" ><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
										<div class="sold-by-container">
											<a title="<?php echo $rsad['suppliyer_name'];?>" href="<?php echo $this->baseUrl()."/store/index?store=".$rsad['store_alias'].".html";?>"><span><?php echo $tr->translate("Store");?> </span> : <?php echo $rsad['suppliyer_name'];?></a>
										</div>
									</div>
								</div>
								<div class="ads-title">
									<h4><a class="ads-title" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$rsad['alias'];?>" ><?php echo $rsad['ads_title'];?></a></h4>
								 </div>
							
							 	 <div class="ads-price">
									<h4><a class="ads-price" href="<?php echo $this->baseUrl()."/listads/detail/ads/".$rsad['alias'];?>" >$ <?php echo number_format($rsad['price']);?></a></h4>
								 </div>
								  <div class="item-info">
									<ul>
									   <li ><?php echo $rsad['category_name'];?></li>
									   <li > <?php echo $rsad['province_name'];?></li>
									</ul>
								</div>
								<div class="footerads" >
									<ul >
									   <li> <i class="fa fa-eye"></i><?php echo $rsad['viewer'].' '.$tr->translate("Viewer");?></li>
									   <li> <i class="fa fa-calendar"></i><?php echo date("M d, Y",strtotime($rsad['publish_date']));?></li>
									</ul>
								</div>
							</div>
						<?php }?>
						<?php for($j=0;$j<=10;$j++){?>
							
							<?php }?>
							
						<!--  <div class="ad-box ">
							<div class="ads-img-wrapper">
								<a class="ad-image box" href="#" title="Account need urgently" >
									<img src="<?php //echo $this->baseUrl();?>/template/imagedemo/job2-400x2801-30o7lr9ve46edz5vboegp6-31dc1phlynzmn2f7wc3cwa.jpg" alt="" />
								</a>		
								<div class="additional-buttons">
									<span class="quickview"><i class="fa fa-search-plus"></i> Quickview</span>
									<div class="sold-by-container">
										<span>Posted By: </span>
										<a title="Channy" href="#">Channy</a>
									</div>
								</div>	
							</div>							
							<div class="ads-title">
								
								<h4><a class="ads-title" href="#" >Lexux RX300</a></h4>
							 </div>
							 <div class="ads-price">
								<h4><a class="ads-price" href="#" >$ 2000</a></h4>
							 </div>
							 <div class="notify-new red">
								<span class="notify-new">NEW</span>
							</div>
						</div>-->
						
					</div>
				</div>
			</div>
		
			</div>
			
			
		</div>
	</section>
	<section class="featured-slider-3 blog-cateory-items-slide ">
		<div class="container" >
			<div class="col-md-12 col-sm-12" >
			<div class="banner-top" style="width:100; height:100px;border:1px solid #ccc;">
				<img src="<?php echo $this->baseUrl()."/images/banner/camappbanner.gif"?>" />
				<!-- <h2 align="center">1170x100(px)</h2> -->
			</div>
			</div>
		</div>
	</section>
		<?php }?>	
<div id="fb-root"></div>
</body>
</html>