<!DOCTYPE html>
<html lang="en-US">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Cam App Technology</title>	
	<link rel="shortcut icon" href="wp-content/uploads/2016/04/favicon.jpg" type="image/x-icon" />
<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />

<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />

<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />


<!--<script type='text/javascript' src='<?php //echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
 <script type='text/javascript' src='<?php //echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script> -->

<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>

<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	?>
	<?php 
	$db = new Application_Model_DbTable_DbVdGlobal();
				
	if(!empty($this->rscate))foreach($this->rscate as $cate) {?>
	<section class="featured-slider-3 blog-cateory-items-slide ">
		<div class="container" >
			<div class="col-md-12 col-sm-12" >
			<div class="block-title-cate">
				<p class="b-title"><span><i class="fa fa-television"></i><?php echo $cate['name']?></span></p>
				
				<p class="label-show-all"><a href="#">Show all</a></p>
			</div>
			
			<div class="full">
				<div class="pane">
					<div class=" owl-carousel" data-items="5" data-items-tab-ls="2" data-items-tab="2" data-autoplay="false" data-gutter="4" data-autoplay-speed="1500" data-delay="1000" data-loop="true" data-nav="false"  data-dots="false">
						<?php 
						$rsads = $db->getAllAdsToHomepage($cate['id']);
						foreach($rsads as $rsad) {?>
							<div class="ad-box ">
								<div class="ads-img-wrapper">
									<a class="ad-image box" href="#" title="Finance officer for hotel" >
									<?php if (!empty($rsad['images'])){?>
										<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rsad['images']; ?>" alt=""  />
									<?php }else{?>
										<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
									<?php }?>
									</a>
									<div class="additional-buttons">
										<span class="quickview" id="quickview" onClick="getAdsDetail('<?php echo $rsad['id'];?>');" ><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
										<div class="sold-by-container">
											<a title="<?php echo $rsad['suppliyer_name'];?>" href="#"><span><?php echo $tr->translate("Posted By");?> </span><?php echo $rsad['suppliyer_name'];?></a>
										</div>
									</div>
								</div>
								<div class="ads-title">
									<h4><a class="ads-title" href="#" ><?php echo $rsad['ads_title'];?></a></h4>
								 </div>
							
							 	 <div class="ads-price">
									<h4><a class="ads-price" href="#" >$ <?php echo number_format($rsad['price']);?></a></h4>
								 </div>
								  <div class="item-info">
									<ul style="font-size: 10px;">
									   <li ><?php echo $rsad['province_name'];?></li>
									   <li > <?php echo $rsad['province_name'];?></li>
									</ul>
								</div>
								<div class="footerads" >
									<ul >
									   <li> <i class="fa fa-eye"></i><?php echo $rsad['viewer'];?> </li>
									   <li> <i class="fa fa-clock-o"></i><?php echo date("M d, Y",strtotime($rsad['publish_date']));?></li>
									</ul>
								</div>
							</div>
						<?php }?>
						<?php for($j=0;$j<=10;$j++){?>
							<div class="ad-box ">
								<div class="ads-img-wrapper">
									<a class="ad-image box" href="#" title="Finance officer for hotel" >
										<img src="<?php echo $this->baseUrl()."/images/adsimg/borey.jpg"; ?>" alt=""  />
									</a>
									<div class="additional-buttons">
										<span class="quickview"><i class="fa fa-search-plus"></i><?php echo $tr->translate("Quickview");?></span>
										<div class="sold-by-container">
											<a title="Channy" href="#"><span><?php echo $tr->translate("Posted By");?> </span>sok chandara</a>
										</div>
									</div>
								</div>
								<div class="ads-title">
									<h4><a class="ads-title" href="#" >បង់ប្រាក់មុនត្រឹមតែ7900$អាចចូលស្នាក់នៅបានភ្លាមៗ</a></h4>
								 </div>
								 <div class="ads-price">
									<h4><a class="ads-price" href="#" >$ <?php echo number_format(11111123456);?></a></h4>
								 </div>
								 <div class="item-info">
									<ul style="font-size: 10px;">
									   <li >Phnom Penh</li>
									   <li > Phnom Penh</li>
									</ul>
								</div>
								<div class="footerads" >
									<ul >
									   <li> <i class="fa fa-eye"></i>100 Views</li>
									   <li> <i class="fa fa-clock-o"></i>12, Mar 2017</li>
									</ul>
								</div>
							</div>
							<?php }?>
							
						<!--  <div class="ad-box ">
							<div class="ads-img-wrapper">
								<a class="ad-image box" href="#" title="Account need urgently" >
									<img src="<?php //echo $this->baseUrl();?>/template/imagedemo/job2-400x2801-30o7lr9ve46edz5vboegp6-31dc1phlynzmn2f7wc3cwa.jpg" alt="" />
								</a>		
								<div class="additional-buttons">
									<span class="quickview"><i class="fa fa-search-plus"></i> Quickview</span>
									<div class="sold-by-container">
										<span>Posted By: </span>
										<a title="Channy" href="#">Channy</a>
									</div>
								</div>	
							</div>							
							<div class="ads-title">
								
								<h4><a class="ads-title" href="#" >Lexux RX300</a></h4>
							 </div>
							 <div class="ads-price">
								<h4><a class="ads-price" href="#" >$ 2000</a></h4>
							 </div>
							 <div class="notify-new red">
								<span class="notify-new">NEW</span>
							</div>
						</div>-->
						
					</div>
				</div>
			</div>
		
			</div>
			
			
		</div>
	</section>
	
		<?php }?>
	<footer  class="footer-style-4">
		<div class="container footer-grid-3">					
			<div class="row">
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">ABOUT CLASSIADS</h4>			
						<div class="textwidget">
							<p>
							Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop  professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern. 
							</p>
							<div class="widget-social footer-social-widget">
								<a href="#" target="_blank"><i class="fa fa-facebook"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-twitter"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-pinterest"></i></a>								
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-google-plus"></i></a>								
								<a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a>							
							</div>
							<a href="http://demo.designinvento.net/classiads4" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<div class="footer-logo">
							<a class="footer-about-us" href="#" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
						<div class="textwidget text-description">
							<p>
									Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern.						

							</p>
						</div>
					</div>
				</div>
				
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">Get In Touch</h4>			
						<div class="textwidget">
							<div role="form" class="wpcf7" id="wpcf7-f4333-o1" lang="en-US" dir="ltr">
								<div class="screen-reader-response"></div>
								<form action="#" method="post" class="wpcf7-form" novalidate="novalidate">
									<div style="display: none;">
										<input type="hidden" name="_wpcf7" value="4333" />
										<input type="hidden" name="_wpcf7_version" value="4.6" />
										<input type="hidden" name="_wpcf7_locale" value="en_US" />
										<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4333-o1" />
										<input type="hidden" name="_wpnonce" value="c4cd5f3f04" />
									</div>
									<p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Your Name" /></span> </p>
									<p><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="Email Address" /></span>  </p>
									<p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Type Your message here..."></textarea></span>  </p>
									<p><input type="submit" value="Submit Message" class="wpcf7-form-control wpcf7-submit" /></p>
									<div class="wpcf7-response-output wpcf7-display-none"></div>
								</form>
							</div>
						</div>
					</div>
				</div>			
			</div>			
		</div>			
	</footer>
	
	<section class="socket"  style="background-color:#262626;">
		<div class="container">
			<div class="site-info"  style="color:#999999;">
								 All copyrights reserved &#x00040; 2017 - Design &AMP; Development by <a href="http://cam-app.com/">Cam App Technology</a>
			</div><!-- .site-info -->
			<div class="footer-menu">
				<ul id="menu-footer" class="menu"><li id="menu-item-4384" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4384"><a>Home</a></li>
					<li id="menu-item-4328" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4328"><a href="blog/index.html">BLOG</a></li>
					<li id="menu-item-4331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4331"><a href="pricing-plans/index.html">PRICING PLANS</a></li>
					<li id="menu-item-4330" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4330"><a href="contact/index.html">CONTACT</a></li>
				</ul>					
			</div>
		</div>
	</section>
	<div id="pop-ads-detail" class="popup detail-pro" style="display:none;">
	  <!-- popup content -->
	  <div class="pop-content">
	    <div class="pop-content_header">
	      <span id="close-detail" class="close">×</span>
	      <h2>បង់ប្រាក់មុនត្រឹមតែ7900$អាចចូលស្នាក់នៅបានភ្លាមៗ</h2>
	    </div>

	    <div class="pop-content-body" >
	    	<div class="pop-content-body-left">
	    		<div class="slide-content" style="max-width:100%;">
	    		  <div class="blog-main-slide">
					  <img class="mySlides" src="<?php echo $this->baseUrl()."/images/adsimg/borey.jpg"; ?>" >
					  <img class="mySlides" src="<?php echo $this->baseUrl()."/images/adsimg/banimg.jpg"; ?>" >
					  <img class="mySlides" src="<?php echo $this->baseUrl()."/images/adsimg/borey.jpg"; ?>" >
				  </div>
				
				  <div class="thumnail-blog">
				    <div class="thumnail-image-slide">
				      <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/borey.jpg"; ?>" style="width:100%" onclick="currentDiv(1)">
				    </div>
				    <div class="thumnail-image-slide">
				      <img class=" images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/banimg.jpg"; ?>" style="width:100%" onclick="currentDiv(2)">
				    </div>
				    <div class="thumnail-image-slide">
				      <img class="images-thum" src="<?php echo $this->baseUrl()."/images/adsimg/borey.jpg"; ?>" style="width:100%" onclick="currentDiv(3)">
				    </div>
				  </div>
				</div>
	    	</div>
	    	<div class="pop-content-body-right">
	    		<div class="ads-title">
					<h4><a class="ads-title" href="#" >បង់ប្រាក់មុនត្រឹមតែ7900$អាចចូលស្នាក់នៅបានភ្លាមៗ</a></h4>
				 </div>
				 <div class="viewer" >
					<ul >
					   <li> <i class="fa fa-eye"></i>100 Views</li>
					   <li> <i class="fa fa-clock-o"></i>12, Mar 2017</li>
					</ul>
				</div>
				 <div class="ads-price">
					<h4><a class="ads-price" href="#" >$ <?php echo number_format(11111123456);?></a></h4>
				 </div>
				 <div class="description">
				 	<p>
				 		Morbi accumsan ipsum velit. Nam nec tellus a odio sit tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent permis conubia nostra, per inceptos himenaeos mauris inter erat justo. Nullam a
				 	</p>
				 </div>
				 <div class="postedby"> 
				 	<p>Posted By : <span class="bold"><a href="#">Sok Chandara</a></span></p>
				 </div>
				 <div class="item-info">
					<ul style="font-size: 10px;">
					   <li >Category : </li>
					   <li class="value">Houses & Lands</li>
					   <li > Location : </li>
					   <li class="value"> Phnom Penh</li>
					</ul>
				</div>
				<div class="social-share">
					<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button " data-size="large" data-mobile-iframe="false"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"></a></div>
				</div>
	    	</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
	<script>
		var slideIndex = 1;
		showDivs(slideIndex);
		
		function plusDivs(n) {
		  showDivs(slideIndex += n);
		}
		
		function currentDiv(n) {
		  showDivs(slideIndex = n);
		}
		
		function showDivs(n) {
		  var i;
		  var x = document.getElementsByClassName("mySlides");
		  var dots = document.getElementsByClassName("images-thum");
		  if (n > x.length) {slideIndex = 1}
		  if (n < 1) {slideIndex = x.length}
		  for (i = 0; i < x.length; i++) {
		     x[i].style.display = "none";
		  }
		  x[slideIndex-1].style.display = "initial";
		
		}


		/*
			popup form
		*/
		function getAdsDetail(index){
			alert(index);
			 $("#pop-ads-detail").css("display", "block");
		}
		jQuery("#close-detail").live("click", closeformdetail);
		window.onclick = function(event) {//When the user clicks anywhere outside of the modal, close it
			if (event.target == document.getElementById("pop-ads-detail")) {
				closeformdetail();
		    }

		}
		function closeformdetail() {
	         $("#pop-ads-detail").css("display", "none");
	    }
	</script>
	
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>