<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Log in</title>	
	<link rel="shortcut icon" href="wp-content/uploads/2016/04/favicon.jpg" type="image/x-icon" />
<!--[if lt IE 9]>
<link rel='stylesheet' id='classiads-ie-css'  href='http://demo.designinvento.net/classiads5/wp-content/themes/classiads/css/ie.css?ver=2013-11-08' type='text/css' media='all' />
<![endif]-->
<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />

<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />

<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />


<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>

<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>

<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<body>
	<section class="container">	
		<header class="public-head-layout wrapper" style="border-bottom: solid 1px #005dad;margin-bottom: 0px">
		    <div style="padding: 10px;">
				<div class="header-item">
					<a href="<?php echo $this->baseUrl();?>/index">
						<img src="<?php echo $this->baseUrl();?>/images/logo.png" class="logo" style=" margin-top: 10px;">
					</a>
				</div>
				<div class="header-item quick-menu">
					<dl class="language">
							<a class="lang km" href="#" title="Khmer" onclick="changeLange(1);"><img src="<?php echo $this->baseUrl();?>/images/km.png" ></a>
							<a class="lang en" href="#" title="English" onclick="changeLange(2);"><img src="<?php echo $this->baseUrl();?>/images/en.jpg" ></a>
					</dl>
				</div>
			</div>
		</header>
	</section>
	<section class="container">
		<div class="login-body">
			<div class="register-login-box">
				<div class="login-title"><h4 class="title">Log in</h4></div>
				<div class="formlogin-register">
					<form onsubmit="return validateFormlogin(this);" name="registerForm" action="" id="register-form" method="post" class="register-form" >
						<div class="form-row">
							<p style=" text-align: center;"><span style="color:#f50404;" id="error" class="error"><?php if (!empty($this->message)){ echo $this->message;}?></span></p>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>User Name <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
							<input type="text" placeholder="User Name"  name="user_name" id="user_name"  required="required" class="form-control" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Password <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="password" placeholder="Password" name="password" id="password"  required="required" class="form-control" />
							</div>
						</div>
						<div class="form-row botton">
							<button class="loginBtn register"> Log in</button>
							<h4>OR</h4>
							<button class="loginBtn loginBtn--facebook">
								   Log in with Facebook
							</button>
						</div>
						<div class="form-row botton">
							<p>Don't have an account ?<a href="<?php echo $this->baseUrl();?>/index/register"> Sign Up Here</a></p>
						</div>
					</form>
				</div>
			</div>
			
		</div>
	</section>


	
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script>
	getBaseUrl('<?php echo $this->baseUrl();?>');
	</script>
</body>
</html>