<?php $db = new Application_Model_DbTable_DbFormPostAds();?>
<html >
<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
      <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/formpost/css/style.css">
</head>

<body>
	<div class="form">
		 <form action="<?php echo $this->url(array('module'=>'degault','controller'=>'index','action'=>'add-watermark')); ?>" method="post">
			 <div class="top-row">
				<div class="field-wrap labelname">
	              <label>
	                Category<span class="req">*</span>
	              </label>
	            </div>
	            <div class="field-wrap">
	              <select onChange="getControllByCate();" id="category" name="category">
	              <?php if (!empty($this->category)) foreach ($this->category as $rs){?>
	              	<?php $child = $db->checkChild($rs['id']); if($child==0){?>
	             		<option value="<?php echo $rs['id']?>"><?php echo $rs['name'];?></option>
	             	<?php }else{?>
	             		<optgroup label="<?php echo $rs['name']?>"></optgroup>
	             	<?php }?>
					<?php }?>
	              </select>
	            </div>
	          </div>
	          <div id="blank">
				
	          </div>
		 </form>
	</div>
  <div class="form">
      
      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>Sign Up for Free</h1>
          
          <form action="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'add-watermark')); ?>" method="post" enctype="multipart/form-data">
          
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" id="first_name"  name="first_name" required autocomplete="off" />
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required id="email"  name="email"  autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
           <div class="field-wrap">
           <div class="uploader" onclick="$('#filePhoto').click()">
			    <img src="<?php echo $this->baseUrl();?>/images/broweimage.png"/>
			    <input type="file" name="filePhoto"  id="filePhoto" value='' />
			</div>
          </div>
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>

        </div>
        
        <div id="login">   
          <h1>Welcome Back!</h1>
          
          <form action="/" method="post">
          
            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="#">Forgot Password?</a></p>
          
          <button class="button button-block"/>Log In</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->

    <script src="<?php echo $this->baseUrl();?>/formpost/js/index.js"></script>

</body>
</html>
<script>
function isNumber(evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
        var msg='You can input only number.';
		alert(msg);
		return false;
    }
    return true;
}
var url_getControl = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'getform')); ?>';
function getControllByCate()
{
	category = $('#category').val();
	$.ajax({
		url: url_getControl,
		data: {category: category},
		type: "POST",
		success:function(data){
			var arrays = $.parseJSON(data);
			//alert(arrays.items);
			document.getElementById('blank').innerHTML = arrays.form;
			
		},
		error:function (e){
			alert(e);
			
		}
		});
}
var url_getCascad = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'get-cascade')); ?>';
function getCascadeValue(controlname){
	parent = $('#'+controlname).val();
	$.ajax({
		url: url_getCascad,
		data: {parent: parent},
		type: "POST",
		success:function(data){
			val = $.parseJSON(data);
			document.getElementById(val.fieldname).innerHTML= val.value;
		},
		error:function (e){
			alert(e);
			
		}
		});
	
}
var imageLoader = document.getElementById('filePhoto');
imageLoader.addEventListener('change', handleImage, false);

function handleImage(e) {
var reader = new FileReader();
reader.onload = function (event) {
    
    $('.uploader img').attr('src',event.target.result);
}
reader.readAsDataURL(e.target.files[0]);
}
</script>