<!DOCTYPE html>
<html lang="en-US">
<?php 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$profile = $this->client_info;
	if (!empty($profile['photo'])){
		$image = $profile['photo'];
	}else{
		$image = "profile.jpg";
	}
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Dashboard Management</title>	
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<?php 
		echo $this->render('header.phtml');
	?>
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="tab-left">
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal">
							<li class="active">
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myaccount')); ?>">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										My Account									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myads')); ?>">
									<span class="dash-title">
										<i class="fa fa-cart-plus" aria-hidden="true"></i>
										My Ads									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mystore')); ?>">
									<span class="dash-title">
										<i class="fa fa-university" aria-hidden="true"></i>
										 My Store							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										My Page						
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										Contact Us					
									</span>
								</a>
							</li>
							
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'banner')); ?>">
									<span class="dash-title">
										<i class="fa fa-picture-o" aria-hidden="true"></i>
										 Manage Banner							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'policy')); ?>">
									<span class="dash-title">
										<i class="fa fa-newspaper-o" aria-hidden="true"></i>
										Policy								
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'announce')); ?>">
									<span class="dash-title">
										<i class="fa fa-comment-o" aria-hidden="true"></i>
										Anouncement								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
				<div class="tab-content">
					<div class="tab-pane active " id="myAccount">
						<div class="blog-wrapper" >
							<div class="profile-info">
								<div class="data-info">
									<div class="title">
										<h4>Account Information
										<span class="right" ><a class="button right" id="edit_account" title="Edit">Edit</a>	</span>
										</h4> 
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">User Name <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="user_name_v"><?php echo $profile['user_name'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Email <span class="right">:</span> </label></div>
										<div class="label_value"><label class="value" id="email_v"><?php echo $profile['email'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Phone <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="phone_v"><?php echo $profile['phone'];?></label></div>
									</div>
									
									<div class="title"><h4>Additional Information <span class="right" ><a class="button right" id="edit_additional" title="Edit">Edit</a></span></h4></div>
									<div class="row_data">
										<div class="label_name"><label class="label">Address <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="address_v"><?php echo $profile['address'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Website <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="website_v"><?php echo $profile['website'];?></label></div>
									</div>
								</div>
								<div class="account-image">
									<div class="image-box">
										<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/'.$image;?>" alt=""  />
									</div>
									<div class="button_browse">
									<div id='preview'></div>	
										<form id="image_upload_form" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl();?>/dashboard/upload' utocomplete="off">
											<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
											<input class="btn_borwse_image" type="file" id="profile_image" name="profile_image"  onchange="loadFile(event)"/>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="myAds">
						<div class="title">
						<div data-dismiss="alert" class="alert mar_b20 msg_err">Delete Error
							<div class="close">
							<span aria-hidden="true">×</span>
							</div>
						</div>
						<h4>My Ads <span class="right" ><a class="button right" id="post-ads" title="Post Ads">Post Ads</a></h4></div>
						<?php if(!empty($this->myads))foreach($this->myads as $key =>$rsad){?>
						<div class="blog-wrapper">
							<div class="ads-left">
								<a class="ad-image box" href="#" title="Finance officer for hotel" >
										<?php if (!empty($rsad['images'])){?>
											<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rsad['images']; ?>" alt=""  />
										<?php }else{?>
											<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
										<?php }?>
								</a>
							</div>
							<div class="ads-description">
								<div class="title-ads"><h4><a target="_blank" href="<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'detail','ads'=>$rsad['alias']));?>"><?php echo $rsad['ads_title'];?></a></h4></div>
								<div class="categories-ads"><h5><a href="#"><?php echo $rsad['category_name']?></a></h5></div>
								<div class="description-ads"><p href="#">
								<?php
									$str1 = utf8_encode($rsad['description']);
									$description = substr($str1, 0, 600);
									echo utf8_decode($description); 
								?>
								</p></div>
								<div class="footer-ads">
									<span><i class="fa fa-calendar" aria-hidden="true"></i></span>
									<span class="value"><?php echo date("d, M Y",strtotime($rsad['publish_date']));?></span>
									<span><i class="fa fa-eye" aria-hidden="true"></i> </span>
									<span class="value"><?php echo $rsad['viewer']; ?> Views</span>
								</div>
							</div>
							<div class="icon_menu-right">
								<ul class="icon_menu">
									<li class="delete_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'dashboard','action'=>'delete','adsid'=>$rsad['id']));?>" title="Delete" onclick="return confirm('<?php echo $tr->translate("Do you sure to delete this ads ?");?>');"><?php echo $tr->translate('DELETE');?></a></li>
									<li class="edit_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'dashboard','action'=>'edit','adsid'=>$rsad['id']));?>" title="Edit"><?php echo $tr->translate('EDIT');?></a></li>
									<li class="renew_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'dashboard','action'=>'renew','adsid'=>$rsad['id']));?>" title="Renew"><?php echo $tr->translate('RENEW');?></a></li>
								</ul>
							</div>
						</div>
						<?php }?>
						
					</div>
				</div>
			</div>
		</div>
	</section>
	<div id="pop-acc-info" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-acc-info_content">
	    <div class="pop-acc-info_header">
	      <span id="close-acc-info" class="close">×</span>
	      <h2>Edit Account Information</h2>
	    </div>
	    <div class="pop-acc-info_body">
	     <form id="form-account-info" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label>User Name <span class="sign_req">*</span></label>
						<input type="text" placeholder="User Name"  name="user_name" id="user_name" value="<?php echo $profile['user_name'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Email <span class="sign_req">*</span></label>
						<input type="text" placeholder="Email" readOnly="readOnly" name="email" id="email" value="<?php echo $profile['email'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Phone <span class="sign_req">*</span></label>
						<input type="text" placeholder="Phone"  name="phone" id="phone" value="<?php echo $profile['phone'];?>" required="required" class="form-control custom" />
					</div>
				</div>
			</div>
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAccountInfo();"> Submit</button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
	<div id="pop-addtional" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-addtional_content">
	    <div class="pop-addtional_header">
	      <span id="close-pop-addtional" class="close">×</span>
	      <h2>Edit Additional Information</h2>
	    </div>
	    <div class="pop-addtional_body">
	     <form id="form-pop-addtional" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label>Address <span class="sign_req">*</span></label>
						<input type="text" placeholder="Address"  name="address" id="address" value="<?php echo $profile['address'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Website <span class="sign_req">*</span></label>
						<input type="text" placeholder="Website" name="website" id="website" value="<?php echo $profile['website'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
			</div>
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAdditional();"> Submit</button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
<?php 
	echo $this->render('sideright.phtml');
?>
<script>
	window.onload = function(e){ 
		getBaseUrl('<?php echo $this->baseUrl();?>');
	}
</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
</body>
</html>