<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->
<?php 
$profile = $this->client_info;
if (!empty($profile['photo'])){
	$image = $profile['photo'];
}else{
	$image = "profile.jpg";
}
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Dashboard Management</title>	
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="tab-left">
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal" id="tabs">
							<li class="active">
								<a href="#myAccount">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										My Account									
									</span>
								</a>
							</li>
							<li>
								<a href="#myAds">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										My Ads									
									</span>
								</a>
							</li>
							<li>
								<a href="#myAds">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										 My Store							
									</span>
								</a>
							</li>
							<li>
								<a href="#myAds">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										My Page						
									</span>
								</a>
							</li>
							<li>
								<a href="#myAds">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										 Manage Banner							
									</span>
								</a>
							</li>
							<li>
								<a href="#Trandom">
									<span class="dash-title">
										<i class="fa fa-home" aria-hidden="true"></i>
										Policy								
									</span>
								</a>
							</li>
							<li>
								<a href="#Trandom">
									<span class="dash-title">
										<i class="fa fa-home" aria-hidden="true"></i>
										Anouncement								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
				<div class="tab-content">
					<div class="tab-pane active " id="myAccount">
						<div class="blog-wrapper" >
							<div class="profile-info">
								<div class="data-info">
									<div class="title">
										<h4>Account Information
										<span class="right" ><a class="button right" id="edit_account" title="Edit">Edit</a>	</span>
										</h4> 
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">User Name <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="user_name_v"><?php echo $profile['user_name'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Email <span class="right">:</span> </label></div>
										<div class="label_value"><label class="value" id="email_v"><?php echo $profile['email'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Phone <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="phone_v"><?php echo $profile['phone'];?></label></div>
									</div>
									
									<div class="title"><h4>Additional Information <span class="right" ><a class="button right" id="edit_additional" title="Edit">Edit</a></span></h4></div>
									<div class="row_data">
										<div class="label_name"><label class="label">Address <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="address_v"><?php echo $profile['address'];?></label></div>
									</div>
									<div class="row_data">
										<div class="label_name"><label class="label">Website <span class="right">:</span> </label>	</div>
										<div class="label_value"><label class="value" id="website_v"><?php echo $profile['website'];?></label></div>
									</div>
								</div>
								<div class="account-image">
									<div class="image-box">
										<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/'.$image;?>" alt=""  />
									</div>
									<div class="button_browse">
									<div id='preview'></div>	
										<form id="image_upload_form" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl();?>/dashboard/upload' utocomplete="off">
											<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
											<input class="btn_borwse_image" type="file" id="profile_image" name="profile_image"  onchange="loadFile(event)"/>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="myAds">
						<div class="title"><h4>My Ads <span class="right" ><a class="button right" id="post-ads" title="Post Ads">Post Ads</a></h4></div>
						<div class="blog-wrapper">
							<div class="ads-left">
								<a class="ad-image box" href="../../2016/04/30/finance-officer-for-hotel/index.html" title="Finance officer for hotel" >
									<img src="<?php echo $this->baseUrl();?>/template/imagedemo/marketing21-30o7k73x9bx84ai65grdai-31dc2ug8a1r0mvrfgqd43u.jpg" alt=""  />
								</a>
							</div>
							<div class="ads-description">
								<div class="title-ads"><h4><a href="#">Photography Artistic Came...</a></h4></div>
								<div class="categories-ads"><h5><a href="#">Art & Photography</a></h5></div>
								<div class="description-ads"><p href="#">Morbi accumsan ipsum velit. Nam nec tellus a odio sit tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent permis conubia nostra, per inceptos himenaeos mauris inter erat justo. Nullam a</p></div>
								<div class="footer-ads"><span><i class="fa fa-calendar" aria-hidden="true"></i></span><span class="value">21-03-2016</span> <span><i class="fa fa-eye" aria-hidden="true"></i> </span><span class="value">200</span></div>
							</div>
							<div class="icon_menu-right">
								<ul class="icon_menu">
									<li class="delete_icon"><a href="#" title="Delete">Delete</a></li>
									<li class="edit_icon"><a href="#" title="Edit">Edit</a></li>
									<li class="renew_icon"><a href="#" title="Renew">Renew</a></li>
								</ul>
							</div>
						</div>
						<div class="blog-wrapper">
							<div class="ads-left">
								<a class="ad-image box" href="../../2016/04/30/finance-officer-for-hotel/index.html" title="Finance officer for hotel" >
									<img src="<?php echo $this->baseUrl();?>/template/imagedemo/marketing21-30o7k73x9bx84ai65grdai-31dc2ug8a1r0mvrfgqd43u.jpg" alt=""  />
								</a>
							</div>
							<div class="ads-description">
								<div class="title-ads"><h4><a href="#">Photography Artistic Came...</a></h4></div>
								<div class="categories-ads"><h5><a href="#">Art & Photography</a></h5></div>
								<div class="description-ads"><p href="#">Morbi accumsan ipsum velit. Nam nec tellus a odio sit tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent permis conubia nostra, per inceptos himenaeos mauris inter erat justo. Nullam a</p></div>
								<div class="footer-ads"><span><i class="fa fa-calendar" aria-hidden="true"></i></span><span class="value">21-03-2016</span> <span><i class="fa fa-eye" aria-hidden="true"></i> </span><span class="value">200</span></div>
							</div>
							<div class="icon_menu-right">
								<ul class="icon_menu">
									<li class="delete_icon"><a href="#" title="Delete">Delete</a></li>
									<li class="edit_icon"><a href="#" title="Edit">Edit</a></li>
									<li class="renew_icon"><a href="#" title="Renew">Renew</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	
	<footer  class="footer-style-4">
		<div class="container footer-grid-3">					
			<div class="row">
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">ABOUT CLASSIADS</h4>			
						<div class="textwidget">
							<p>
							Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop  professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern. 
							</p>
							<div class="widget-social footer-social-widget">
								<a href="#" target="_blank"><i class="fa fa-facebook"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-twitter"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-pinterest"></i></a>								
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-google-plus"></i></a>								
								<a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a>							
							</div>
							<a href="http://demo.designinvento.net/classiads4" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<div class="footer-logo">
							<a class="footer-about-us" href="#" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
						<div class="textwidget text-description">
							<p>
									Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern.						

							</p>
						</div>
					</div>
				</div>
				
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">Get In Touch</h4>			
						<div class="textwidget">
							<div role="form" class="wpcf7" id="wpcf7-f4333-o1" lang="en-US" dir="ltr">
								<div class="screen-reader-response"></div>
								<form action="#" method="post" class="wpcf7-form" novalidate="novalidate">
									<div style="display: none;">
										<input type="hidden" name="_wpcf7" value="4333" />
										<input type="hidden" name="_wpcf7_version" value="4.6" />
										<input type="hidden" name="_wpcf7_locale" value="en_US" />
										<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4333-o1" />
										<input type="hidden" name="_wpnonce" value="c4cd5f3f04" />
									</div>
									<p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Your Name" /></span> </p>
									<p><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="Email Address" /></span>  </p>
									<p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Type Your message here..."></textarea></span>  </p>
									<p><input type="submit" value="Submit Message" class="wpcf7-form-control wpcf7-submit" /></p>
									<div class="wpcf7-response-output wpcf7-display-none"></div>
								</form>
							</div>
						</div>
					</div>
				</div>			
			</div>			
		</div>			
	</footer>
	<section class="socket"  style="background-color:#262626;">
		<div class="container">
			<div class="site-info"  style="color:#999999;">
								 All copyrights reserved &#x00040; 2017 - Design &AMP; Development by <a href="http://cam-app.com/">Cam App Technology</a>
			</div><!-- .site-info -->
			<div class="footer-menu">
				<ul id="menu-footer" class="menu"><li id="menu-item-4384" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4384"><a>Home</a></li>
					<li id="menu-item-4328" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4328"><a href="blog/index.html">BLOG</a></li>
					<li id="menu-item-4331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4331"><a href="pricing-plans/index.html">PRICING PLANS</a></li>
					<li id="menu-item-4330" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4330"><a href="contact/index.html">CONTACT</a></li>
				</ul>					
			</div>
		</div>
	</section>
	
	<div id="pop-acc-info" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-acc-info_content">
	    <div class="pop-acc-info_header">
	      <span id="close-acc-info" class="close">×</span>
	      <h2>Edit Account Information</h2>
	    </div>
	    <div class="pop-acc-info_body">
	     <form id="form-account-info" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label>User Name <span class="sign_req">*</span></label>
						<input type="text" placeholder="User Name"  name="user_name" id="user_name" value="<?php echo $profile['user_name'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Email <span class="sign_req">*</span></label>
						<input type="text" placeholder="Email" readOnly="readOnly" name="email" id="email" value="<?php echo $profile['email'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Phone <span class="sign_req">*</span></label>
						<input type="text" placeholder="Phone"  name="phone" id="phone" value="<?php echo $profile['phone'];?>" required="required" class="form-control custom" />
					</div>
				</div>
			</div>
			 
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAccountInfo();"> Submit</button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
	
	<div id="pop-addtional" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-addtional_content">
	    <div class="pop-addtional_header">
	      <span id="close-pop-addtional" class="close">×</span>
	      <h2>Edit Additional Information</h2>
	    </div>
	    <div class="pop-addtional_body">
	     <form id="form-pop-addtional" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label>Address <span class="sign_req">*</span></label>
						<input type="text" placeholder="Address"  name="address" id="address" value="<?php echo $profile['address'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label>Website <span class="sign_req">*</span></label>
						<input type="text" placeholder="Website" name="website" id="website" value="<?php echo $profile['website'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
			</div>
			 
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAdditional();"> Submit</button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
<script>

window.onload = function(e){ 
	getBaseUrl('<?php echo $this->baseUrl();?>');
}
</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>

	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>

	<!-- softable -->
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
</body>
</html>