<!DOCTYPE html>
<html lang="en-US">
<?php 	
$session_lang=new Zend_Session_Namespace('lang');
$currentlang = $session_lang->lang_id;

	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$profile = $this->client_info;
	if (!empty($profile['photo'])){
		$image = $profile['photo'];
	}else{
		$image = "profile.jpg";
	}
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Dashboard Management</title>	
	
	<script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
	<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
	<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
	<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />
	<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>
	<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
	
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<?php 
		//echo $this->render('header.phtml');
	?>
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div  class="logo-left-side">
					<div class="logo-left-blog">
							<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
						</div>
				</div>
				<div class="tab-left">
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal">
							<li class="active">
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myaccount')); ?>">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										My Account									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myads')); ?>">
									<span class="dash-title">
										<i class="fa fa-cart-plus" aria-hidden="true"></i>
										My Ads									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mystore')); ?>">
									<span class="dash-title">
										<i class="fa fa-university" aria-hidden="true"></i>
										 My Store							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										My Page						
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										Contact Us					
									</span>
								</a>
							</li>
							
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'banner')); ?>">
									<span class="dash-title">
										<i class="fa fa-picture-o" aria-hidden="true"></i>
										 Manage Banner							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'policy')); ?>">
									<span class="dash-title">
										<i class="fa fa-newspaper-o" aria-hidden="true"></i>
										Policy								
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'announce')); ?>">
									<span class="dash-title">
										<i class="fa fa-comment-o" aria-hidden="true"></i>
										Anouncement								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
				<div class="tab-content">
					<div class="tab-pane active " id="myAccount">
						<div class="blog-wrapper" >
							<div class="profile-info">
								<div class="data-info">
									<div class="title">
										<h4><?php echo $tr->translate("Account Information");?>
										</h4> 
										<span class="right" ><a class="button right" id="edit_account" title="<?php echo $tr->translate("EDIT");?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php echo $tr->translate("EDIT");?></a></span>
									</div>
									<div class="profile">
										<ul class="profile list">
											<li><span class="field-title"><?php echo $tr->translate("User Name");?></span> : <span class="field-value" id="user_name_v"><?php echo $profile['user_name'];?></span></li>
											<li><span class="field-title"><?php echo $tr->translate("Email");?></span> : <span class="field-value" id="email_v"><?php echo $profile['email'];?></span></li>
											<li><span class="field-title"><?php echo $tr->translate("Phone");?></span> : <span class="field-value" id="phone_v"><?php echo $profile['phone'];?></span></li>
										</ul>
									</div>
									
									
									<div class="title"><h4><?php echo $tr->translate("Additional Information");?> </h4>
									<span class="right" ><a class="button right" id="edit_additional" title="<?php echo $tr->translate("EDIT");?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php echo $tr->translate("EDIT");?></a></span>
									</div>
									<div class="profile">
										<ul class="profile list">
											<li><span class="field-title"><?php echo $tr->translate("Address");?></span> : <span class="field-value" id="address_v"><?php echo $profile['address'];?></span></li>
											<li><span class="field-title"><?php echo $tr->translate("Website");?></span> : <span class="field-value" id="website_v"><?php echo $profile['website'];?></span></li>
										</ul>
									</div>
								</div>
								<div class="account-image">
									<div class="image-box">
										<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/'.$image;?>" alt=""  />
									</div>
									<div class="button_browse">
									<div id='preview'></div>	
										<form id="image_upload_form" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl();?>/dashboard/upload' utocomplete="off">
											<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
											<input class="btn_borwse_image" type="file" id="profile_image" name="profile_image"  onchange="loadFile(event)"/>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<div id="pop-acc-info" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-acc-info_content">
	    <div class="pop-acc-info_header">
	      <span id="close-acc-info" class="close">×</span>
	      <h2><?php echo $tr->translate("Edit Account Information");?></h2>
	    </div>
	    <div class="pop-acc-info_body">
	     <form id="form-account-info" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label><?php echo $tr->translate("User Name");?> <span class="sign_req">*</span></label>
						<input type="text" placeholder="User Name"  name="user_name" id="user_name" value="<?php echo $profile['user_name'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label><?php echo $tr->translate("Email");?> <span class="sign_req">*</span></label>
						<input type="text" placeholder="Email" readOnly="readOnly" name="email" id="email" value="<?php echo $profile['email'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label><?php echo $tr->translate("Phone");?> <span class="sign_req">*</span></label>
						<input type="text" placeholder="Phone"  name="phone" id="phone" value="<?php echo $profile['phone'];?>" required="required" class="form-control custom" />
					</div>
				</div>
			</div>
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAccountInfo();"> <?php echo $tr->translate("Submit");?></button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
	<div id="pop-addtional" class="pop-acc-info">
	  <!-- popup content -->
	  <div class="pop-addtional_content">
	    <div class="pop-addtional_header">
	      <span id="close-pop-addtional" class="close">×</span>
	      <h2><?php echo $tr->translate("Edit Additional Information");?></h2>
	    </div>
	    <div class="pop-addtional_body">
	     <form id="form-pop-addtional" method="post">
     		<div class="form-row">
     			<div class="row_data">
					<div>
						<label><?php echo $tr->translate("Address");?> <span class="sign_req">*</span></label>
						<input type="text" placeholder="Address"  name="address" id="address" value="<?php echo $profile['address'];?>" required="required" class="form-control custom" />
					</div>
				</div>
				<div class="row_data">
					<div>
						<label><?php echo $tr->translate("Website");?> <span class="sign_req">*</span></label>
						<input type="text" placeholder="Website" name="website" id="website" value="<?php echo $profile['website'];?>"  required="required" class="form-control custom" />
					</div>
				</div>
			</div>
	     </form>
	     <div class="form-row botton">
				<button class="loginBtn register" onclick="editAdditional();"> <?php echo $tr->translate("Submit");?></button>
			</div>
	    </div>
	    <div class="popup_footer">
	    </div>
	  </div>
	</div>
<?php 
	echo $this->render('sideright.phtml');
	echo $this->render('frontbottom.phtml');
?>
<script>		
		<?php if ($currentlang==1){?>
			var monthNames = [
			                  "Jan", "Feb", "Mar",
			                  "Apr", "May", "Jun", "Jul",
			                  "Aug", "September", "Oct",
			                  "Nov", "Dec"
			                ];
	      <?php }else{?>
	      var monthNames = [
		                  "មករា", "កុម្ភៈ", "មិនា",
		                  "មេសា", "ឧសភា", "មិថុនា", "កក្កដា",
		                  "សីហា", "កញ្ញា", "តុលា",
		                  "វិច្ឆិការ", "ធ្នូ"
		                ];
	      <?php }?>
	      var baseurl = '<?php echo $this->baseUrl();?>';
	</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
</body>
</html>