<!DOCTYPE html>
<html lang="en-US">
<?php 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$profile = $this->client_info;
	if (!empty($profile['photo'])){
		$image = $profile['photo'];
	}else{
		$image = "profile.jpg";
	}
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Dashboard Management</title>	
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<?php 
		echo $this->render('header.phtml');
	?>
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="tab-left">
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal">
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myaccount')); ?>">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										My Account									
									</span>
								</a>
							</li>
							<li class="active">
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myads')); ?>">
									<span class="dash-title">
										<i class="fa fa-cart-plus" aria-hidden="true"></i>
										My Ads									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mystore')); ?>">
									<span class="dash-title">
										<i class="fa fa-university" aria-hidden="true"></i>
										 My Store							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										My Page						
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										Contact Us					
									</span>
								</a>
							</li>
							
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'banner')); ?>">
									<span class="dash-title">
										<i class="fa fa-picture-o" aria-hidden="true"></i>
										 Manage Banner							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'policy')); ?>">
									<span class="dash-title">
										<i class="fa fa-newspaper-o" aria-hidden="true"></i>
										Policy								
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'announce')); ?>">
									<span class="dash-title">
										<i class="fa fa-comment-o" aria-hidden="true"></i>
										Anouncement								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
				<div class="tab-content">
						<div class="title">
						<div data-dismiss="alert" class="alert mar_b20 msg_err">Delete Error
							<div class="close">
							<span aria-hidden="true">×</span>
							</div>
						</div>
						<h4>My Ads <span class="right" ><a href="<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'choose-category'));?>" class="button right" title="Post Ads"><i class="fa fa-plus-circle" aria-hidden="true"></i><?php echo $tr->translate("Post Ads");?></a></h4></div>
						<?php if(!empty($this->myads))foreach($this->myads as $key =>$rsad){?>
						<div class="blog-wrapper <?php if(count($this->myads)==$key+1){echo"last_record";}?>">
							<div class="ads-left">
								<a class="ad-image box" href="#" title="Finance officer for hotel" >
										<?php if (!empty($rsad['images'])){?>
											<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rsad['image_feature']; ?>" alt=""  />
										<?php }else{?>
											<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
										<?php }?>
								</a>
							</div>
							<div class="ads-description">
								<div class="title-ads"><h4><a target="_blank" href="<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'detail','ads'=>$rsad['alias']));?>"><?php echo $rsad['ads_title'];?></a></h4></div>
								<div class="categories-ads"><h5><a href="#"><?php echo $rsad['category_name']?></a></h5></div>
								<div class="description-ads"><p href="#">
								<?php
									$str1 = utf8_encode($rsad['description']);
									$description = substr($str1, 0, 850);
									echo utf8_decode($description); 
								?>
								</p></div>
								<div class="footer-ads">
									<span><i class="fa fa-calendar" aria-hidden="true"></i></span>
									<span class="value"><?php echo date("d, M Y",strtotime($rsad['publish_date']));?></span>
									<span><i class="fa fa-eye" aria-hidden="true"></i> </span>
									<span class="value"><?php echo $rsad['viewer']; ?> Views</span>
								</div>
							</div>
							<div class="icon_menu-right" style="margin-top:-5px;">
								<ul class="icon_menu">
									<li class="delete_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'dashboard','action'=>'delete','adsid'=>$rsad['id']));?>" title="Delete" onclick="return confirm('<?php echo $tr->translate("Do you sure to delete this ads ?");?>');"><i class="fa fa-times" aria-hidden="true"></i><?php echo $tr->translate('DELETE');?></a></li>
									<li class="edit_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'update-post','adsid'=>$rsad['id']));?>" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php echo $tr->translate('EDIT');?></a></li>
									<li class="renew_icon"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'dashboard','action'=>'renew','adsid'=>$rsad['id']));?>" title="Renew"><i class="fa fa-refresh" aria-hidden="true"></i><?php echo $tr->translate('RENEW');?></a></li>
								</ul>
							</div>
						</div>
					<?php }?>
					<div class="pager-section">
							<ul class="pagination ">
								<li <?php if($this->currentPage==1){echo 'class="disable"';}?> ><a  href="<?php echo $this->baseUrl()."/dashboard/myads/pages/".$this->previousPage;?>"><i class="fa fa-chevron-left"></i></a></li>
								 <?php if (!empty($this->countPages)) $i=0; for( $i=1; $i<=$this->countPages; $i++){?>
										<li <?php if($i==$this->currentPage){ echo 'class="active"';?> <?php } else {}?>><a   href="<?php echo $this->baseUrl()."/dashboard/myads/pages/".$i;?>"><?php echo $i;?></a></li>
								 <?php }?>
								<li <?php if($this->countPages==$this->currentPage){echo 'class="disable"';}?>><a href="<?php echo $this->baseUrl()."/dashboard/myads/pages/".$this->nextPage;?>"><i class="fa fa-chevron-right"></i></a></li>
							</ul>
						</div><!-- pager-section -->
				</div>
			</div>
		</div>
	</section>
<?php 
	echo $this->render('sideright.phtml');
?>
<script>
	window.onload = function(e){ 
		getBaseUrl('<?php echo $this->baseUrl();?>');
	}
</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
</body>
</html>