<!DOCTYPE html>
<html lang="en-US">
<?php 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$profile = $this->client_info;
	if (!empty($profile['photo'])){
		$image = $profile['photo'];
	}else{
		$image = "profile.jpg";
	}
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title><?php echo $tr->translate("My Store Management");?></title>	
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<?php 
		echo $this->render('header.phtml');
	?>
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="tab-left">
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal">
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myaccount')); ?>">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										<?php echo $tr->translate("My Account");?>									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myads')); ?>">
									<span class="dash-title">
										<i class="fa fa-cart-plus" aria-hidden="true"></i>
										<?php echo $tr->translate("My Ads");?>									
									</span>
								</a>
							</li>
							<li class="active">
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mystore')); ?>">
									<span class="dash-title">
										<i class="fa fa-university" aria-hidden="true"></i>
										 <?php echo $tr->translate("My Store");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										<?php echo $tr->translate("My Page");?>						
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										<?php echo $tr->translate("Contact Us");?>					
									</span>
								</a>
							</li>
							
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'banner')); ?>">
									<span class="dash-title">
										<i class="fa fa-picture-o" aria-hidden="true"></i>
										 <?php echo $tr->translate("Manage Banner");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'policy')); ?>">
									<span class="dash-title">
										<i class="fa fa-newspaper-o" aria-hidden="true"></i>
										<?php echo $tr->translate("Policy");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'announce')); ?>">
									<span class="dash-title">
										<i class="fa fa-comment-o" aria-hidden="true"></i>
										<?php echo $tr->translate("Anouncement");?>								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
				<div class="tab-content">
					<div class="title">
						<h4><?php echo $tr->translate("My Store");?> <span class="right" ><a href="<?php echo $this->baseUrl()."/dashboard/store?change=add";?>" class="button right" title="Post Ads"><i class="fa fa-plus-circle" aria-hidden="true"></i><?php echo $tr->translate("Add More Store");?></a></span></h4>
					</div>
						<?php if(!empty($this->mystore))foreach($this->mystore as $key =>$rsad){?>
						<div class="blog-wrapper <?php //if(count($this->myads)==$key+1){echo"last_record";}?>">
							<div class="ads-left">
								<a class="ad-image box" href="#">
										<?php if (!empty($rsad['image_theme'])){?>
											<img src="<?php echo $this->baseUrl()."/images/theme/".$rsad['image_theme']; ?>" alt=""  />
										<?php }else{?>
											<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt=""  />
										<?php }?>
								</a>
							</div>
							<div class="ads-description">
								<div class="title-ads"><h4><a href="<?php //echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'detail','ads'=>$rsad['alias']));?>"><?php echo $rsad['store_title'];?></a></h4></div>
								<div class="categories-ads"><h5><a href="#"><?php echo $rsad['template_title']?></a></h5></div>
								<div class="description-ads"><p href="#">
								<?php
									//$str1 = utf8_encode($rsad['description']);
									//$description = substr($str1, 0, 850);
									//echo utf8_decode($description); 
								?>
								</p></div>
								
							</div>
							
							<div class="icon_menu-right" style="margin-top:-5px;">
								<ul class="icon_menu">
									<li><a href="<?php echo $this->baseUrl()."/dashboard/store?change=edit&store=".$rsad['alias_store'];?>" title="<?php echo $tr->translate('Change Theme');?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i><?php echo $tr->translate('Change Theme');?></a></li>
									<li><a href="<?php echo $this->baseUrl()."/store/index?store=".$rsad['alias_store'].".html";?>" title="<?php echo $tr->translate('View Store');?>"><i class="fa fa-paper-plane-o" aria-hidden="true"></i><?php echo $tr->translate('View Store');?></a></li>
								</ul>
							</div>
						</div>
					<?php }?>
				</div>
			</div>
		</div>
	</section>
	<?php 
	echo $this->render('sideright.phtml');
	echo $this->render('frontbottom.phtml');
?>
<script>
</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
</body>
</html>