<!DOCTYPE html>
<html lang="en-US">
<?php 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$param = $this->param;
	$temp = explode(".", $param['page']);
	$title='';
	if ($temp[0]=="add"){
		$title = $tr->translate("Add New Store");
	}else if ($temp[0]=="edit"){
		$title = $tr->translate("Edite/Update Store");
	}
	
	
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title><?php echo $title;?></title>	
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/template/colorpicker/css/colorpicker.css" type="text/css" />
		
	<script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
	<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
	<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
	<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />
	<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>
	<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
		
</head>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="tab-left">
					<div  class="logo-left-side">
						<div class="logo-left-blog">
								<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
							</div>
					</div>
					<div  class="pos-relative">
						<ul class="nav nav-tabs tabs horizontal">
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myaccount')); ?>">
									<span class="dash-title">
										<i class="fa fa-user" aria-hidden="true"></i>
										<?php echo $tr->translate("My Account");?>									
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'myads')); ?>">
									<span class="dash-title">
										<i class="fa fa-cart-plus" aria-hidden="true"></i>
										<?php echo $tr->translate("My Ads");?>									
									</span>
								</a>
							</li>
							<li class="active">
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mystore')); ?>">
									<span class="dash-title">
										<i class="fa fa-university" aria-hidden="true"></i>
										 <?php echo $tr->translate("My Store");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-bullhorn" aria-hidden="true"></i>
										<?php echo $tr->translate("My Page");?>						
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'mypage')); ?>">
									<span class="dash-title">
										<i class="fa fa-map-marker" aria-hidden="true"></i>
										<?php echo $tr->translate("Contact Us");?>					
									</span>
								</a>
							</li>
							
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'banner')); ?>">
									<span class="dash-title">
										<i class="fa fa-picture-o" aria-hidden="true"></i>
										 <?php echo $tr->translate("Manage Banner");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'policy')); ?>">
									<span class="dash-title">
										<i class="fa fa-newspaper-o" aria-hidden="true"></i>
										<?php echo $tr->translate("Policy");?>							
									</span>
								</a>
							</li>
							<li>
								<a href="<?php echo $this->url(array("module"=>'default','controller'=>'dashboard','action'=>'announce')); ?>">
									<span class="dash-title">
										<i class="fa fa-comment-o" aria-hidden="true"></i>
										<?php echo $tr->translate("Anouncement");?>								
									</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="conten-body-center right">
					<div class="title">
						<h4><?php echo $title;?> 
						<span class="right" ><a href="<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'choose-category'));?>" class="button right" title="Post Ads"><i class="fa fa-chevron-left" aria-hidden="true"></i><?php echo $tr->translate("Back");?></a></span>
						</h4>
					</div>
					<div class="store_menu">
						<div  class="pos-relative">
							<ul class="nav nav-tabs tabs store-menu" id="tabs">
								<li class='active'>
									<a href="#template" onclick="return false;">
										<span class="cat-tit">
											<i class="fa fa-sticky-note"></i><br /><?php echo $tr->translate("Choose Template");?>
										</span>
									</a>
								</li>
								<li >
									<a href="#storeinfo">
										<span class="cat-tit">
										<i class="fa fa-university"></i><br />
											<?php echo $tr->translate("Store Information");?>
										</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<?php 	if ($temp[0]=="add"){?>
					<form id="form-store-info" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl();?>/dashboard/addstore' autocomplete="off">
						<div class="tab-content">
							<div class="tab-pane store-temp active" id="template">
								<div class="sub-template">
									<div>
										<div class="title">
											<h4 class="sub-title"><?php echo $tr->translate("Click to set your template Store");?></h4>
										</div>
										<ul class="sub-template">
										<?php if (!empty($this->template)) foreach($this->template as $rs){?>
											<li class="list-thum">
												<figure>
													<a id="theme<?php echo $rs['id'];?>" onClick="selectTemplate(<?php echo $rs['id'];?>);" title="<?php echo $rs['template_title'];?>" <?php if ($rs['id']==1){echo 'class="active"';}?>><!--  <span class="name">Acidus</span> -->
													<img class="template-image"  src="<?php echo $this->baseUrl()."/images/theme/".$rs['image_theme']; ?>" alt="Acidus Free Website Template" title="View the Acidus Template Details"> 
													<span class="posted"><?php echo $rs['template_title'];?></span></a>
													<input type="hidden" id="font-col<?php echo $rs['id'];?>" name="font-col<?php echo $rs['id'];?>" value="<?php echo $rs['template_main_color'];?>" />
													<input type="hidden" id="them-col<?php echo $rs['id'];?>" name="them-col<?php echo $rs['id'];?>" value="<?php echo $rs['template_main_font_color'];?>" />
													</figure>
												<!--  <div class="thum-image">
													<img class="template-image" src="<?php echo $this->baseUrl()."/images/theme/".$rs['image_theme']; ?>" alt="" />
												</div>-->
											</li>
											<?php }?>
										</ul>
									</div>
									<div>
										<div class="title">
											<h4 class="sub-title"><?php echo $tr->translate("Click to change color your template");?></h4>
										</div>
										<div class="blog-store-color">
											<div class="span-title">
												<span><?php echo $tr->translate("Template Color For Store");?> : </span>
											</div>
											<div class="span-value">
												 <a onclick="showcolorbox(1);" ><span class="color" id="theme-olor"  style=" background: #2a328d;"></span></a>
											</div>
										</div>
										<div class="blog-store-color">
											<div class="span-title">
												<span><?php echo $tr->translate("Font Color For Store");?> : </span>
											</div>
											<div class="span-value">
												 <a onclick="showcolorbox(2);"><span class="color" id="fonts-color" style=" background: #2a328d;"></span></a>
											</div>
										</div>
									</div>
									<div id="slide-blog">
										<div class="title">
												<h4 class="sub-title"><?php echo $tr->translate("Slide Image in store");?> (650 X 350px)</h4>
											</div>
										<div class="store-slide">
										<?php for ($l=1; $l<=3; $l++){?>
											<div class="row_form">
												<div class="image_slidview">
													<img id="slide_view<?php echo $l;?>" src="<?php echo $this->baseUrl();?>/images/blankslide.jpg"/>
												</div>
												<div class="button-browse-image">
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="slideimage<?php echo $l;?>" name="slideimage<?php echo $l;?>"  onchange="uploadbanner('<?php echo $l;?>')"/>
												</div>
											</div>
										<?php }?>
										</div>
									</div>
								</div>
								<input type="hidden" id="templatess" name="templatess" value="1" />
							</div>
							
							<div class="tab-pane store-temp  " id="storeinfo">
								<div class="form-template-info">
									<div class="form-row">
										<div class="form-label">
											<label><?php echo $tr->translate("Store Name");?> <span class="sign_req">*</span></label>
										</div>
										<div class="form-value">
											<input type="text" placeholder="Store Name"  value="" required="required" name="store_title" id="store_title" class="form-control" style="    width: 500px;" />
										</div>
									</div>
									<div class="form-row">
										<div class="form-label">
											<label><?php echo $tr->translate("Store Phone");?> <!-- <span class="sign_req">*</span> --></label>
										</div>
										<div class="form-value">
											<input type="text" placeholder="Phone Number"   name="phone" id="phone" class="form-control" style="width: 170px;" />
										</div>
										<div class="form-label">
											<label><?php echo $tr->translate("Store Email");?> <!-- <span class="sign_req">*</span> --></label>
										</div>
										<div class="form-value">
											<input type="text" placeholder="Email"   name="email" id="email" class="form-control" style=" width: 170px;" />
										</div>
									</div>
									<div class="form-row">
										<div class="form-label">
											<label><?php echo $tr->translate("Store Address");?> <!-- <span class="sign_req">*</span> --></label>
										</div>
										<div class="form-value">
											<textarea id="address"  name="address" class="form-control form-store" style="margin: 0px 0px 10px; max-width: 500px; min-width: 500px; max-height: 131px; height: 102px; width: 500px;"></textarea>
										</div>
									</div>
									<div class="form-row">
										<div class="form-label">
											<label><?php echo $tr->translate("About Store");?> <!-- <span class="sign_req">*</span> --></label>
										</div>
										<div class="form-value">
											<textarea id="abouts"  name="abouts" class="form-control form-store" style="margin: 0px 0px 10px; max-width: 500px; min-width: 500px; max-height: 131px; height: 102px; width: 500px;"></textarea>
										</div>
									</div>
								</div>
								<div class="account-image">
										<div class="image-box">
											<img id="logo_view" src="<?php echo $this->baseUrl().'/images/no_logo.jpg'?>" alt=""  />
										</div>
										<div class="button_browse">
										<div id='preview'></div>	
											
												<span><?php echo $tr->translate("Upload");?> <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
												<input class="btn_borwse_image" type="file" id="logo_image" name="logo_image"  onchange="loadLogo(event)"/>
										
										</div>
										<div>
											<span>(220px X 100px)</span>
										</div>
								</div>
							</div>
							
						</div>
					<div class="form-row botton">
						<input type="hidden" id="templatesscolor" name="templatesscolor" value="#2a328d" />
						<input type="hidden" id="fontsscolor" name="fontsscolor" value="#2a328d" />
							<input type="submit" class="button" name="submit-bt" value="<?php echo $tr->translate("Save");?>" />
						</div>
					</form>
					<?php }else if ($temp[0]=="edit"){ ?>
						<form id="form-store-info" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl()."/dashboard/updatestore?store=".$param['store'];?>' autocomplete="off">
							<div class="tab-content">
								<div class="tab-pane store-temp active" id="template">
									<div class="sub-template">
										<div>
											<div class="title">
												<h4 class="sub-title"><?php echo $tr->translate("Click to set your template Store");?></h4>
											</div>
											<ul class="sub-template">
											<?php if (!empty($this->template)) foreach($this->template as $rs){?>
												<li class="list-thum">
													<figure>
														<a id="theme<?php echo $rs['id'];?>" onClick="selectTemplate(<?php echo $rs['id'];?>);" title="<?php echo $rs['template_title'];?>" <?php if ($rs['id']==$this->store['template_id']){echo 'class="active"';}?>><!--  <span class="name">Acidus</span> -->
														<img class="template-image"  src="<?php echo $this->baseUrl()."/images/theme/".$rs['image_theme']; ?>" alt="Acidus Free Website Template" title="View the Acidus Template Details"> 
														<span class="posted"><?php echo $rs['template_title'];?></span></a>
														<input type="hidden" id="font-col<?php echo $rs['id'];?>" name="font-col<?php echo $rs['id'];?>" value="<?php echo $rs['template_main_color'];?>" />
														<input type="hidden" id="them-col<?php echo $rs['id'];?>" name="them-col<?php echo $rs['id'];?>" value="<?php echo $rs['template_main_font_color'];?>" />
														</figure>
													<!--  <div class="thum-image">
														<img class="template-image" src="<?php echo $this->baseUrl()."/images/theme/".$rs['image_theme']; ?>" alt="" />
													</div>-->
												</li>
												<?php }?>
											</ul>
										</div>
										<div>
											<div class="title">
												<h4 class="sub-title"><?php echo $tr->translate("Click to change color your template");?></h4>
											</div>
											<div class="blog-store-color">
												<div class="span-title">
													<span><?php echo $tr->translate("Template Color For Store");?> : </span>
												</div>
												<div class="span-value">
													 <a onclick="showcolorbox(1);" ><span class="color" id="theme-olor"  style=" background: <?php echo $this->store['template_color'];?>;"></span></a>
												</div>
											</div>
											<div class="blog-store-color">
												<div class="span-title">
													<span><?php echo $tr->translate("Font Color For Store");?> : </span>
												</div>
												<div class="span-value">
													 <a onclick="showcolorbox(2);"><span class="color" id="fonts-color" style=" background: <?php echo $this->store['font_color'];?>;"></span></a>
												</div>
											</div>
										</div>
										<div id="slide-blog" style="<?php if ($this->store['template_id']==2){ echo "display:none;";}?>">
										<div class="title">
												<h4 class="sub-title"><?php echo $tr->translate("Slide Image in store");?> (650 X 350px)</h4>
											</div>
										<div class="store-slide" >
										<?php 
										if (!empty($this->store['images_slide'])){
											$slide= explode(",", $this->store['images_slide']);
											$l=0;
											foreach ($slide as $sli){$l++;
											?>
											<div class="row_form">
												<div class="image_slidview">
													<img id="slide_view<?php echo $l;?>" src="<?php echo $this->baseUrl()."/images/store/slide/".$sli;?>"/>
												</div>
												<div class="button-browse-image">
													<span><?php echo $tr->translate("Upload");?> <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="slideimage<?php echo $l;?>" name="slideimage<?php echo $l;?>"  onchange="uploadbanner('<?php echo $l;?>')"/>
												</div>
											</div>
											<?php }?>
											<?php if (count($this->store['images_slide'])<3){  while($l<3){ $l++;?>
												<div class="row_form">
													<div class="image_slidview">
														<img id="slide_view<?php echo $l;?>" src="<?php echo $this->baseUrl();?>/images/blankslide.jpg"/>
													</div>
													<div class="button-browse-image">
														<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
														<input class="btn_borwse_image" type="file" id="slideimage<?php echo $l;?>" name="slideimage<?php echo $l;?>"  onchange="uploadbanner('<?php echo $l;?>')"/>
													</div>
												</div>
											<?php }
											}?>
										<?php 
										}else{
											for ($l=1; $l<=3; $l++){?>
											<div class="row_form">
												<div class="image_slidview">
													<img id="slide_view<?php echo $l;?>" src="<?php echo $this->baseUrl();?>/images/blankslide.jpg"/>
												</div>
												<div class="button-browse-image">
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="slideimage<?php echo $l;?>" name="slideimage<?php echo $l;?>"  onchange="uploadbanner('<?php echo $l;?>')"/>
												</div>
											</div>
										<?php }
										}?>
										</div>
									</div>
									</div>
									
									<input type="hidden" id="templatess" name="templatess" value="<?php echo $this->store['template_id'];?>" />
								</div>
								
								<div class="tab-pane store-temp  " id="storeinfo">
									<div class="form-template-info">
										<div class="form-row">
											<div class="form-label">
												<label><?php echo $tr->translate("Store Name");?> <!-- <span class="sign_req">*</span> --></label>
											</div>
											<div class="form-value">
												<input type="text" placeholder="Store Name"  value="<?php echo $this->store['store_title'];?>"  name="store_title" id="store_title" class="form-control" style="    width: 500px;" />
											</div>
										</div>
										<div class="form-row">
											<div class="form-label">
												<label><?php echo $tr->translate("Store Phone");?> <!-- <span class="sign_req">*</span> --></label>
											</div>
											<div class="form-value">
												<input type="text" placeholder="Phone Number"  value="<?php echo $this->store['store_phone'];?>"  name="phone" id="phone" class="form-control" style="    width: 170px;" />
											</div>
											<div class="form-label">
												<label><?php echo $tr->translate("Store Email");?> <!-- <span class="sign_req">*</span> --></label>
											</div>
											<div class="form-value">
												<input type="text" placeholder="Email" value="<?php echo $this->store['store_email'];?>"   name="email" id="email" class="form-control" style=" width: 170px;" />
											</div>
										</div>
										<div class="form-row">
											<div class="form-label">
												<label><?php echo $tr->translate("Store Address");?> <!-- <span class="sign_req">*</span> --></label>
											</div>
											<div class="form-value">
												<textarea id="address"  name="address" class="form-control form-store" style="margin: 0px 0px 10px; max-width: 500px; min-width: 350px; max-height: 131px; height: 102px; width: 500px;"><?php echo $this->store['store_address'];?></textarea>
											</div>
										</div>
										<div class="form-row">
											<div class="form-label">
												<label><?php echo $tr->translate("About Store");?> <!-- <span class="sign_req">*</span> --></label>
											</div>
											<div class="form-value">
												<textarea id="abouts" name="abouts" class="form-control form-store" style="margin: 0px 0px 10px; max-width: 500px; min-width: 350px; max-height: 131px; height: 102px; width: 500px;"><?php echo $this->store['store_about_us'];?></textarea>
											</div>
										</div>
									</div>
									<div class="account-image">
											<div class="image-box">
												<?php if (!empty($this->store['logo_store'])){?>
												<img id="logo_view" src="<?php echo $this->baseUrl().'/images/store/'.$this->store['logo_store'];?>" alt=""  />
												<?php }else{?>
												<img id="logo_view" src="<?php echo $this->baseUrl().'/images/no_logo.jpg'?>" alt=""  />
												<?php }?>
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
												
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" value="<?php echo $this->store['logo_store'];?>" type="file" id="logo_image" name="logo_image"  onchange="loadLogo(event)"/>
											
											</div>
										</div>
								</div>
								
							</div>
						<div class="form-row botton">
							<input type="hidden" id="templatesscolor" name="templatesscolor" value="<?php echo $this->store['template_color'];?>" />
							<input type="hidden" id="fontsscolor" name="fontsscolor" value="<?php echo $this->store['font_color'];?>" />
								<input type="submit" class="button" name="submit-bt" value="<?php echo $tr->translate("Save");?>" />
							</div>
						</form>
					<?php }?>
					<div id="choose-color-pop" class="popup" style="display:none;">
					
						<div class="pop-content">
							<div class="pop-content_header">
						      <span id="close-color" class="close">×</span>
						      <h2 id="pop-titlebar"><?php echo $tr->translate("Choose Color");?></h2>
						    </div>
							<p id="colorpickerHolder">
	               		  				</p> 
	               		  	<input type="hidden" id="collllll" name="collllll" value="#ffff" />
	               		  		<a onclick="setColorTo();" class="button" title="Ok"><?php echo $tr->translate("Ok");?></a>	
	               		  </div>
					</div>
					
			</div>
		</div>
	</section>
	<?php 
	echo $this->render('sideright.phtml');
	echo $this->render('frontbottom.phtml');
	?>
<script>

</script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/javascript/custome.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
	
	<script>

	var loadLogo = function(event) {
	    var output = document.getElementById('logo_view');
	    output.src = URL.createObjectURL(event.target.files[0]);
	  };
		var alltem = <?php echo count($this->template);?>;
		var optioncol=1;
		function selectTemplate(index){
			for(var i=1; i<= alltem; i++){
				$("#theme"+i).removeClass("active");
			}
			$("#theme"+index).addClass("active");
			
			$("#templatess").val(index);
			$("#templatesscolor").val($("#them-col"+index).val());
			$("#fontsscolor").val($("#font-col"+index).val());
		 	$("#theme-olor").css("background", $("#them-col"+index).val());
		 	$("#fonts-color").css("background", $("#font-col"+index).val());
		 	if(index!=2){
		 		$("#slide-blog").css("display", "block");
		 	}else{
		 		$("#slide-blog").css("display", "none");
		 	}
		}
		function showcolorbox(index){
			$("#choose-color-pop").css("display", "block");
			optioncol =index;
		}
		function closecolorbox() {
			
			 $("#choose-color-pop").css("display", "none");
		}
		
		jQuery("#close-color").live("click", closecolorbox);
		window.onclick = function(event) {//When the user clicks anywhere outside of the modal, close it
			if (event.target == document.getElementById("choose-color-pop")) {
					closecolorbox();
				}
		}
		
		var sds='00ff1e';
		function getColor(){
			var lastcolor = $("#main_color").val();
			$("#collllll").val('#'+lastcolor);
			
		}

		function setColorTo(){
			var lastcolor = $("#main_color").val();
			sds = lastcolor;
			if(optioncol==1){
			 $("#theme-olor").css("background", '#'+sds);
			 $("#templatesscolor").val('#'+sds);
			}else{
				 $("#fonts-color").css("background", '#'+sds);
				 $("#fontsscolor").val('#'+sds);
			}
			 closecolorbox();
		}
		function uploadbanner (index) {
		    	var output = document.getElementById('slide_view'+index);
		    	output.src = URL.createObjectURL(event.target.files[0]);
			
	  }
	</script>

	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/template/colorpicker/js/colorpicker.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl();?>/template/colorpicker/js/eye.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl();?>/template/colorpicker/js/layout.js?ver=1.0.2"></script>
	<script>
			jQuery(function ($) {
				
				 getColor();
			});
	</script>
</body>
</html>