<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate('EDIT_JOB');?></title>
<form id='add_job' action="<?php echo $this->url(array('module'=>'other','controller'=>'job','action'=>'edit')); ?>" enctype="application/x-www-form-urlencoded" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
		return true;
	}else {
		return false;
	}
</script>
<table  width="100%" style="margin-top:5px;">
	<tr class="header">
			<td><?php echo $tr->translate('EDIT_JOB');?></td>
	</tr>
	<tr>
		<td>
		<fieldset>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate('JOB_TITLE');?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="job_title" name="job_title" value="<?php echo $this->row['job_title'];?>" type="text">
								<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="id" name="id" value="<?php echo $this->row['id'];?>" type="hidden">
							</td>
							<td><?php echo $tr->translate('JOB_TYPE');?></td>
							<td><select name="job_type" id="job_type" dojoType="dijit.form.FilteringSelect" class="fullside" Onchange="getFunction();">
								    <option value="1"><?php echo $tr->translate('FULL_TIME');?></option>
								    <option value="2"><?php echo $tr->translate('PART_TIME');?></option>
								    <option value="3"><?php echo $tr->translate('FULL_AND_PART_TIME');?></option>
								</select></td>		
							<td><?php echo $tr->translate('SALARY');?></td>
						   <td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="salary" name="salary" value="<?php echo $this->row['salary'];?>" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('HIRING');?></td>
							<td><input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="hiring" name="hiring" value="<?php echo $this->row['hiring'];?>" type="text"></td>
							<td><?php echo $tr->translate('POSTING_DATE');?></td>
							<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="posting_date" name="posting_date" value="<?php echo $this->row['posting_date'];?>" type="text"></td>
							<td><?php echo $tr->translate('CLOSING_DATE');?></td>
							<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="closing_date" name="closing_date" value="<?php echo $this->row['closting_date'];?>" type="text"></td>
						</tr>
						<tr>
							<td colspan="3"><?php echo $tr->translate('INTRODUCTION');?><textarea dojoType="dijit/Editor" height="150px" style="min-height:60px;"  id="introduction" name="introduction"><?php echo $this->row['introduction'];?></textarea></td>
							<td colspan="3"><?php echo $tr->translate('JOB_DESCRIPTION');?><textarea dojoType="dijit/Editor"  height="150px" style="min-height:60px;" id="job_purpose" name="job_purpose"><?php echo $this->row['job_purpose'];?></textarea></td>
						</tr>
						<tr>
							<td colspan="3"><?php echo $tr->translate('JOB_RESPON');?><textarea dojoType="dijit/Editor" height="150px" style="min-height:60px;"  id="job_respone" name="job_respone"><?php echo $this->row['job_respone'];?></textarea></td>
							<td colspan="3"><?php echo $tr->translate('JOB_REQUIR');?><textarea dojoType="dijit/Editor" height="150px" style="min-height:60px;"  id="job_requirement" name="job_requirement"><?php echo $this->row['job_requirement'];?></textarea></td>
						</tr>
						<tr>
							<td colspan="3"><?php echo $tr->translate('DUTY_STATION');?><textarea dojoType="dijit/Editor" height="150px" style="min-height:60px;"  name="job_duty"><?php echo $this->row['job_duty'];?></textarea></td>
							<td colspan="3"><?php echo $tr->translate('SALARY_BENIFIT');?><textarea dojoType="dijit/Editor" height="150px" style="min-height:60px;"  name="benifit"><?php echo $this->row['benifit'];?></textarea></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('HOW_TO_APPLY');?></td>
							<td><textarea dojoType="dijit.form.SimpleTextarea" class="fullside" style="width:96%;min-height:35px;" id="how_apply" name="how_apply"><?php echo $this->row['how_applay'];?></textarea></td>
							<td><?php echo $tr->translate('STATUS');?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1" <?php if($this->row['status']==1){echo'selected="selected"';}?> ><?php echo $tr->translate('ACTIVE');?></option>
								    <option value="0" <?php if($this->row['status']==0){echo'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE');?></option>
								</select></td>
							<td></td>
							<td></td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
	<tr class="footer_button">
		<td  align="center">
			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
				 iconClass="dijitIconClear" /> 
			<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
				iconClass="dijitEditorIcon dijitEditorIconSave"/> 
						    
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea"); 
dojo.require("dijit.form.DateTextBox");  
require(["dijit/Editor"]);
</script>
				