<?php $db = new Application_Model_DbTable_DbVdGlobal();
$db_select = new Application_Model_DbTable_DbGlobalselect();
$lang =$db->getLaguage();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<head>
<meta charset="UTF-8">
	<script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
	<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
	<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
	<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />
	<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>
	<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<section id="static-imageheader" class=" static-imageheader" >
	<div class="banner-cat-container">
		<div class="container">		
			<div id="main-category">
				<div  class="pos-relative">
					<div class="banner-left-blog">
							<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
						</div>
				</div>
			</div>
			
		</div>
	</div>
	</section>
	<script>		
		var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
		function changeLange(lang){
			$.ajax({
				url: url_changelang,
				type: "post",
				data:{'lange':lang},
				success: function(data){
					location.reload();
				},
				error:function(err){
				}
			});
		}
		<?php if ($lang==1){?>
			var monthNames = [
			                  "Jan", "Feb", "Mar",
			                  "Apr", "May", "Jun", "Jul",
			                  "Aug", "September", "Oct",
			                  "Nov", "Dec"
			                ];
	      <?php }else{?>
	      var monthNames = [
		                  "មករា", "កុម្ភៈ", "មិនា",
		                  "មេសា", "ឧសភា", "មិថុនា", "កក្កដា",
		                  "សីហា", "កញ្ញា", "តុលា",
		                  "វិច្ឆិការ", "ធ្នូ"
		                ];
	      <?php }?>
	      var baseurl = '<?php echo $this->baseUrl();?>';
	</script>