<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_BRANCH​​_INFO')); 
?>
<script>
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextbox");
</script>
<?php  $frm = $this->frm_branch;?>
<form action="<?php echo $this->url(array('module'=>'group','controller'=>'project','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("UPDATE_BRANCH​​_INFO");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("PROJECT_CODE")?></td>
										<td><?php echo $frm->getElement("branch_code");?></td>
										<td><?php echo $tr->translate("PROJECT_NAME")?></td>
										<td><?php echo $frm->getElement("branch_namekh");?></td>
										<!-- <td><?php //echo $tr->translate("Project Type")?></td>
										<td><?php //echo $frm->getElement("project_type");?></td> -->
										<td><?php echo $tr->translate("PREFIX_CODE");?></td>
									    <td><?php echo $frm->getElement("prefix_code");?></td>
									</tr>
									<tr>
										<td valign="top"><?php echo $tr->translate("THE_CREDENTAIL_NO")?></td>
										<td valign="top"><?php  echo $frm->getElement('credentail_no');?></td>
										<td><?php echo $tr->translate("ISSUE_DATE")?></td>
										<td><?php  echo $frm->getElement('issue_date');?></td>
										<td><?php echo $tr->translate("REGISTER_BY")?></td>
										<td><?php  echo $frm->getElement('register_by');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("PHONE")?></td>
										<td><?php echo $frm->getElement("branch_tel");?></td>
										<td><?php echo $tr->translate("BRNACH_FAX")?></td>
										<td><?php echo $frm->getElement("fax");?></td>	
										<td><?php echo $tr->translate("BRANCH_STATUS")?></td>
										<td><?php echo $frm->getElement("branch_status");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("LOCATION")?></td>
										<td colspan="5"><?php echo $frm->getElement("br_address");?></td>
									</tr>
									<tr>		
										<td><?php echo $tr->translate("BRANCH_NOTE")?></td>
										<td colspan="5"><?php echo $frm->getElement("branch_note");?></td>
										<!-- <td><?php //echo $tr->translate("BRANCH_DISPLAY")?></td>
										<td><?php //echo $frm->getElement("branch_display");?></td> -->
									</tr>
									<tr>
										<td colspan="4"></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
										  <input type="reset" label="<?php echo $tr->translate('clear');?>" id="" dojoType="dijit.form.Button"
				                              iconClass="dijitIconClear" />
										  <input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
									          iconClass="dijitEditorIcon dijitEditorIconSave"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>