<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("BRANCH_LIST"));
	
	$url_delete =$this->url(array('module'=>'group','controller'=>'project','action'=>'delete'));
	$url_copy =$this->url(array('module'=>'group','controller'=>'project','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
?>	
<?php $frm =  $this->frm_branch;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'project','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table>
	  <tr>	
	  		<td><button onclick="copyRecord('<?php echo $url_copy;?>')" iconclass="dijitIconCopy" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("COPY");?></button></td>
	  		<td><?php echo $frm->getElement('adv_search') ?></td>
	  		<td><?php echo $frm->getElement('status_search');?></td>
	  		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	  		<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
	  		</td>
	  </tr>
  	</table>
</form>
<style>
		.btn-action{
			padding: 3px 10px;
   			    background: #3a3a5d;
			    border: none;
			    font-size: 10pt;
			    float: left;
			    color: #fff;
			    padding-left: 15px;
			    -webkit-border-radius: 5px;
			    -moz-border-radius: 5px;
			    border-radius: 5px;
		}
	
	</style>
<?php echo $this->list;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.Dialog");
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 //alert(url);
		 window.location.href = url+'/id/'+id;
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var recordid ='';
	function  resetForm(){
		var datenow = '<?php echo date("Y-m-d");?>';
		dijit.byId('adv_search').attr('value','');
		dijit.byId('status_search').set('value','-1');
	}
	function deleteRecord(url){
		 id = recordid;
		 window.location.href = url+'/id/'+id;
	}
	function showDeleteForm(id){
		//id = dijit.byId('recorddelete').get('value');
		if(id==''){
			alert("No record selected for delete.");
			dijit.byId('deleteForm').hide();
		}else{
			dijit.byId('deleteForm').show();
			recordid = id;
		}
	}
	function closeForm(){
		dijit.byId('deleteForm').hide();
	}
</script> 
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4>តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?</h4>
			<button onclick="deleteRecord('<?php echo $url_delete;?>')" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
			<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
		</div>
	</div>
</div>