<!DOCTYPE html>
<html lang="en-US">
<?php $parentcate = $this->parentcate;
$db = new Application_Model_DbTable_DbVdGlobal();
?>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<!--<h4 class="title-content"><span class="title">Choose category :</span></h4>-->
				<div class="step-blog">
					<ul class="SteppedProgress Vertical">
						<li class="complete boxed"><span>Post Ads</span></li>
						<li class="complete current"><span>Choose category</span></li>
						<li class=" boxed"><span>Description</span></li>
						<li class=" boxed"><span>Finish</span></li>
					
					</ul>
				</div>
			</div>
			<div class="conten-body-center right post-ads">
				<div class="choose-category-blog">
					<div class="main-category-blog">
						<h4 class="title-content"><span class="number_list">1</span> <span class="title">Select a category :</span></h4>
						<div class="tab-left">
							<div  class="pos-relative">
								<ul class="nav nav-tabs tabs horizontal" id="tabs">
									<?php if (!empty($parentcate)) foreach ($parentcate as $parent){ ?>
									<li class="<!--active-->">
										<a href="<?php echo "#c".$parent['alias_category'];?>">
											<span class="dash-title">
												<?php if (!empty($parentcate)){?>
												<i class="fa <?php echo $parent['fontawsome_icon'];?>" aria-hidden="true"></i>
												<?php } echo $parent['name'];?>							
											</span>
										</a>
									</li>
									<?php }?>
									
								</ul>
							</div>
						</div>
					</div>
					<div class="sub-categories-blog">
						<h4 class="title-content"><span class="number_list">2</span> <span class="title">Select a subcategory :</span></h4>
						<div class="tab-content">
							<?php if (!empty($parentcate)) foreach ($parentcate as $parent){ 
								$subcate = $db->getSubCateByParent($parent['id']);
								?>
								<div class="tab-pane <!--active--> " id="<?php echo "c".$parent['alias_category'];?>">
									<div class="sub-categories-list">
										<ul class="sub-cate">
											<?php if (!empty($subcate)) foreach ($subcate as $cate){?>
											<li class="cate-list"><a href="<?php echo $this->baseUrl()."/postsads/write-post/category/".$cate['alias_category'];?>"><?php  echo $cate['name'];?></a></li>
											<?php }?>
										</ul>
									</div>
								</div>
							<?php }?>
						</div>
					 </div>
				</div>
			</div>
		</div>
		</section>

	
	<footer  class="footer-style-4">
		<div class="container footer-grid-3">					
			<div class="row">
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">ABOUT CLASSIADS</h4>			
						<div class="textwidget">
							<p>
							Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop  professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern. 
							</p>
							<div class="widget-social footer-social-widget">
								<a href="#" target="_blank"><i class="fa fa-facebook"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-twitter"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-pinterest"></i></a>								
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-google-plus"></i></a>								
								<a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a>							
							</div>
							<a href="http://demo.designinvento.net/classiads4" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<div class="footer-logo">
							<a class="footer-about-us" href="#" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
						<div class="textwidget text-description">
							<p>
									Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern.						

							</p>
						</div>
					</div>
				</div>
				
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">Get In Touch</h4>			
						<div class="textwidget">
							<div role="form" class="wpcf7" id="wpcf7-f4333-o1" lang="en-US" dir="ltr">
								<div class="screen-reader-response"></div>
								<form action="#" method="post" class="wpcf7-form" novalidate="novalidate">
									<div style="display: none;">
										<input type="hidden" name="_wpcf7" value="4333" />
										<input type="hidden" name="_wpcf7_version" value="4.6" />
										<input type="hidden" name="_wpcf7_locale" value="en_US" />
										<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4333-o1" />
										<input type="hidden" name="_wpnonce" value="c4cd5f3f04" />
									</div>
									<p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Your Name" /></span> </p>
									<p><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="Email Address" /></span>  </p>
									<p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Type Your message here..."></textarea></span>  </p>
									<p><input type="submit" value="Submit Message" class="wpcf7-form-control wpcf7-submit" /></p>
									<div class="wpcf7-response-output wpcf7-display-none"></div>
								</form>
							</div>
						</div>
					</div>
				</div>			
			</div>			
		</div>			
	</footer>
	<section class="socket"  style="background-color:#262626;">
		<div class="container">
			<div class="site-info"  style="color:#999999;">
								 All copyrights reserved &#x00040; 2017 - Design &AMP; Development by <a href="http://cam-app.com/">Cam App Technology</a>
			</div><!-- .site-info -->
			<div class="footer-menu">
				<ul id="menu-footer" class="menu"><li id="menu-item-4384" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4384"><a>Home</a></li>
					<li id="menu-item-4328" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4328"><a href="blog/index.html">BLOG</a></li>
					<li id="menu-item-4331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4331"><a href="pricing-plans/index.html">PRICING PLANS</a></li>
					<li id="menu-item-4330" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4330"><a href="contact/index.html">CONTACT</a></li>
				</ul>					
			</div>
		</div>
	</section>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	
	
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>

	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	
	<!-- softable -->
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
	
</body>
</html>