<!DOCTYPE html>
<html lang="en-US">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Write Posts</title>
</head>
<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="step-blog">
					<ul class="SteppedProgress Vertical">
						<li class="complete boxed"><span>Post Ads</span></li>
						<li class="complete boxed"><span>Choose category</span></li>
						<li class=" complete current"><span>Description</span></li>
						<li class=" boxed"><span>Finish</span></li>
					</ul>
				</div>
			</div>
			<div class="conten-body-center right post-ads">
			 <?php $rsads = $this->rs_ads;?>
				<div class="title">
					<h4><span style='border: 1px dashed #b0c2d8;padding: 5px;font-size: 14px;'>
						<?php if (!empty($this->cate['parent_name'])){ echo $this->cate['parent_name'].'<i class="fa fa-angle-double-right" aria-hidden="true"></i>';} echo $this->cate['name']?>
						<a style="background:#e2c636;color:#fff;padding:5px;" href="<?php echo $this->baseUrl()."/postsads/choose-category/cateid/".$rsads['id'];?>"> Change Category</a></span></h4> 
				</div>
				<div class="form-post-ads">
				<div id="alert" class="alert message">
				  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
				  <span id="alertMessage"></span>
				</div><!-- return validateFormAds(this); -->
					<form id="postads_form" onsubmit="return validateFormAds(this)" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl()."/postsads/update-post";?>">
						<?php if(count($this->rsstore)>1){?>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Choose My Store");?><span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<select id="store" name="store" class="form-select" >
									<?php if(!empty($this->rsstore) AND count($this->rsstore)>1)foreach($this->rsstore as $rstore){?>
									<option <?php if($rsads['store_id']==$rstore['id']){echo "selected";}?> <?php echo $rstore['id'];?>><?php echo $rstore['store_name'];?></option>
									<?php }?>
								</select>
							</div>
						</div>
						<?php }?>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Title");?><span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Title" value="<?php echo $rsads['ads_title'];?>"  name="title" id="title"  class="form-control" />
								<input type="hidden" name="adsid" id="adsid" value="<?php echo $rsads['id'];?>"/>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Ads Code");?></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Your Product Code" value="<?php echo $rsads['ads_code'];?>" name="ads_code" id="ads_code" class="form-control" />
							</div>
						</div>
						<?php echo $this->form;?>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Price");?> <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Price"  value="<?php echo $rsads['price'];?>" name="price" id="price"   class="form-control" onkeypress="return isNumber(event);" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Description");?> <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<textarea id="description" required="1" name="description" class="form-control textareadesc" placeholder="Description..."><?php echo $rsads['description'];?></textarea>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Link");?></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Your Website"  name="link" id="link" value="<?php echo $rsads['link'];?>" class="form-control" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Image");?> </label>
							</div>
							<div class="form-value">
								<ul class="sortable grid">
								<?php 
								$images = $rsads['images'];
								$image = explode(',', $images);
								$string=''; 
								$imageview="";
								$imageloadin = '<img src="'.$this->baseUrl().'/images/loader.gif" alt="Uploading...."/>';
								for ($i=0; $i<=6; $i++){ 
									$string.="
										jQuery('#filePhoto$i').change(function() {
											var file = this.files[0];
											var imagefile = file.type;
											var match= ['image/jpeg','image/png','image/jpg'];
											if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2])))
											{
												alert('Please Select A valid Image File! Only jpeg, jpg and png Images type allowed.');
												return false;
											}
											else
											{
												var reader = new FileReader();
												reader.readAsDataURL(this.files[0]);
											}
											jQuery('#indexcol').val($i);
											uploadimageajax();
											});
									";
									$imageview.="var loadFile$i = function(event) {
									var output = document.getElementById('image_wiew$i');
									output.src = URL.createObjectURL(event.target.files[0]);
										$('#image_rotate$i').removeClass('hidden');
									};";
									?>
									<li>
										<?php 
											$str_img='images/broweimage.png';
											$image_name='';
											if(!empty($image[$i])){
												$image_name = $image[$i];
												$str_img = "images/adsimg/".$image_name;
											}?>
										<a href="javascript:;" id="image_rotate<?php echo $i;?>" class="image_rotate <?php if (empty($image_name)){echo "hidden";}?>" data-img="" onClick="rotateImage('<?php echo $i;?>')" target="_self">R</a>
										<div id="uploader<?php echo $i;?>" class="uploader">
											<div id='preview<?php echo $i;?>'></div>
											<img id="image_wiew<?php echo $i;?>" src="<?php echo $this->baseUrl()."/".$str_img;?> "/>
											<input type="hidden" id="ads-image<?php echo $i;?>" name="ads-image<?php echo $i;?>" value="<?php echo $image_name;?>" />
											<input class="filephoto" type="file" name="filePhoto<?php echo $i;?>"  id="filePhoto<?php echo $i;?>" accept="image/jpeg,image/gif,image/png" value='' onchange="loadFile<?php echo $i;?>(event)" />
										</div>
									</li>
									<?php }
									echo "<script>jQuery(document).ready(function() { jQuery(function() {".$string." }); }); $imageview</script>";?>
								</ul>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("Location");?><span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<select id="location" name="location" class="form-select" onchange="getAllDistrict();">
									<option value="-1" selected="selected"><?php echo $tr->translate("Choose Location");?></option>
									<?php 
										if(!empty($this->rslocation)){
											foreach($this->rslocation as $rsl){
										?>
											<option <?php if($rsads['province_id']==$rsl['id']){echo"selected";}?> value="<?php echo $rsl['id'];?>" ><?php echo $rsl['province_name'];?></option>
										<?php }
										} 
									?>
								</select>
								<input type="hidden"  name="category" id="category" value="<?php echo $this->cate['id'];?>" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label><?php echo $tr->translate("District");?><span class="sign_req"></span></label>
							</div>
							<div class="form-value">
								<label id="lbl_district">
									<select id="district" name="district" class="form-select">
										<option value="-1" ><?php echo $tr->translate("Choose Distict");?></option>
									</select>
								</label>
								<label><?php echo $tr->translate("Commune");?><span class="sign_req"></span></label>
								<label id="lbl_commune">
									<select id="commune" name="commune" class="form-select">
										<option value="-1" selected="selected"><?php echo $tr->translate("Choose Commune");?></option>
									</select>
								</label>
							</div>
						</div>
						<div class="col-md-12">
							<h2 style="text-align: center;"><?php echo $tr->translate("Contact Information");?></h2>
						</div>
						<div class="col-md-12">
							<div class="col-md-2">
								<label><?php echo $tr->translate("Contact Name");?><span class="sign_req">*</span></label>
							</div>
							<div class="col-md-3">
								<input type="hidden"  name="indexcol" id="indexcol"  />
								<input type="text" placeholder="Name" name="name" id="name" value="<?php echo $rsads['contact_name'];?>" class="form-control" />
							</div>
							<div class="col-md-2">
								<label><?php echo $tr->translate("Phone 1");?><span class="sign_req">*</span></label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Phone"  name="phone1" id="phone1" value="<?php echo $rsads['phone1'];?>"  required="required" class="form-control" />
							</div>
							<div class="col-md-2">
							</div>
						</div>
						<div class="col-md-12">
							<div class="col-md-2">
								<label><?php echo $tr->translate("Phone 2");?></label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Phone"  name="phone2" id="phone2" value="<?php echo $rsads['phone2'];?>" class="form-control" />
							</div>
							<div class="col-md-2">
								<label><?php echo $tr->translate("Email");?></label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Email"  name="email" id="email" value="<?php echo $rsads['email'];?>"  class="form-control" />
							</div>
							<div class="col-md-2"></div>
						</div>
						<div class="form-row">
							<div class="col-md-2">
								<label><?php echo $tr->translate("Address");?></label>
								<input type="hidden"  name="rotates" id="rotates" value="0"  />
							</div>
							<div class="col-md-8">
								<textarea id="adress" name="adress"  class="form-control " placeholder="Address..."><?php echo $rsads['address'];?></textarea>
							</div>
						</div>
						<div class="form-row ">
							<div class="col-md-3">
							</div>
							<div class="col-md-3">
								<input type="button" name='saveclose' class="loginBtn register" value='<?php echo $tr->translate('Cancle');?>' label='Submit My Ads'>
							</div>
							<div class="col-md-3">
								<input type="submit" name='savenew' class="loginBtn register" value='<?php echo $tr->translate('Update');?>' label='Submit My Ads'>
							</div>
							<div class="col-md-3">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	
</body>
<script src="<?php echo $this->baseUrl();?>/template/javascript/validate.js"></script>
<script src="<?php echo $this->baseUrl();?>/template/javascript/custome.js"></script>
<script>
jQuery(document).ready(function($){
	<?php if($rsads['province_id']>0){ ?>
		getAllDistrict();
		var district_id = $('#district').val();
		//if(district_id>0){
			
		//}
	<?php }?>
	});
	
var url_district = '<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'get-districtbyid'));?> ';
function getAllDistrict(){
	var pro_id = $('#location').val();
		$.ajax({
			url: url_district,
			type: "post",
			data:{'pro_id':pro_id},
			success: function(data){
				datars = $.parseJSON(data);
				stringhtml='<select onchange="getCommuneById()" id="district" name="district" class="form-select">';
				stringhtml+='<option value="0" selected="selected"><?php echo $tr->translate("Choose Distict");?></option>';
				for(j=0;j<datars.length;j++){
					stringhtml+='<option value="'+datars[j].id+'">'+datars[j].district_name+'</option>';
				}
				stringhtml+='</select';
				document.getElementById('lbl_district').innerHTML=stringhtml;
				
				stringcommune='<select id="commune" name="commune" class="form-select"><option><?php echo $tr->translate("Choose Commune");?></option></select>';
				document.getElementById('lbl_commune').innerHTML=stringcommune;
				
				$('#district').val(<?php echo $rsads['district_id'];?>);
				var noResult = jQuery(".form-select").data('noResult');
				jQuery(".form-select").chosen({});
				
				getCommuneById();
				
			},
			error:function(err){
				alert(err);
			}
		});
}
var url_commune = '<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'get-communebyid'));?> ';
function getCommuneById(){
	var commune_id = $('#district').val();
	if(commune_id==0){return false;}
	$.ajax({
		url: url_commune,
		type: "post",
		data:{'distict_id':commune_id},
		success: function(data){
			datars = $.parseJSON(data);
			stringhtml='<select id="commune" name="commune" class="form-select">';
			stringhtml+='<option value="0" selected="selected"><?php echo $tr->translate("Choose Commune");?></option>';
			for(j=0;j<datars.length;j++){
				stringhtml+='<option value="'+datars[j].id+'">'+datars[j].commune_name+'</option>';
			}
			stringhtml+='</select';
			document.getElementById('lbl_commune').innerHTML=stringhtml;

			$('#commune').val(<?php echo $rsads['commune_id'];?>);
			var noResult = jQuery(".form-select").data('noResult');
			jQuery(".form-select").chosen({});
		},
		error:function(xhr){
		}
	});
}
</script>
</html>