<!DOCTYPE html>
<html lang="en-US">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<title>Write Posts</title>
</head>
<script>
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'postsads','action'=>'get-districtbyid'));?> ';
function getAllDistrict(){
	var pro_id = $('#location').val();
		lang=1;
		$.ajax({
			url: url_changelang,
			type: "post",
			data:{'pro_id':pro_id},
			success: function(data){

				
				/*for(j=0;j<data.length;j++){
					alert(222)
				}*/
				HTML='<option>testing</option>';
				$('#district').html(HTML).select2();
			},
			error:function(err){
				alert(err);
			   
			}
		});
		
		/*dojo.xhrPost({
			url: url_changelang,
		    content :{ 
				    'lange':lang,
			},	
			handleAs:"json",
			load: function(data) {
				
			},
			error: function(err) {
				
			}
		});*/
	
}
</script>
<body  class="home page-template page-template-template-homepage-v1 page-template-template-homepage-v1-php page page-id-1291 single-author">
	<section class="container">
		<div class="conten-body">
			<div class="conten-body-left">
				<div class="step-blog">
					<ul class="SteppedProgress Vertical">
						<li class="complete boxed"><span>Post Ads</span></li>
						<li class="complete boxed"><span>Choose category</span></li>
						<li class=" complete current"><span>Description</span></li>
						<li class=" boxed"><span>Finish</span></li>
					</ul>
				</div>
			</div>
			<div class="conten-body-center right post-ads">
				<div class="title">
					<h4><span style='border: 1px dashed #b0c2d8;padding: 5px;font-size: 14px;'>
						<?php if (!empty($this->cate['parent_name'])){ echo $this->cate['parent_name'].'<i class="fa fa-angle-double-right" aria-hidden="true"></i>';} echo $this->cate['name']?>
						<a style="background:#ff8c07;color:#fff;padding:3px;" href="<?php echo $this->baseUrl()."/postsads/choose-category";?>"> Change Category</a></span></h4> 
				</div>
				<div class="form-post-ads">
				<div id="alert" class="alert message">
				  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
				  <span id="alertMessage"></span>
				</div><!-- return validateFormAds(this); -->
					<form id="postads_form" onsubmit="return validateFormAds(this)" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl()."/postsads/write-post";?>">
						<div class="form-row">
							<div class="form-label">
								<label>Title <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Title"  name="title" id="title"  class="form-control" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Ads Code <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Your Product Code"  name="ads_code" id="ads_code" class="form-control" />
							</div>
						</div>
						<?php echo $this->form;?>
						<div class="form-row">
							<div class="form-label">
								<label>Price <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Price"  name="price" id="price"   class="form-control" onkeypress="return isNumber(event);"/>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Description <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<textarea id="description" name="description" class="form-control textareadesc" placeholder="Description..."></textarea>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Link <span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<input type="text" placeholder="Your Website"  name="link" id="link" class="form-control" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Image </label>
							</div>
							<div class="form-value">
								<ul class="sortable grid">
								<?php $string=''; 
								$imageview="";
								$imageloadin = '<img src="'.$this->baseUrl().'/images/loader.gif" alt="Uploading...."/>';
								for ($i=0; $i<=6; $i++){ 
// 										$string.="
// 										jQuery('#filePhoto$i').click(function(e){
// 										var imageLoader$i = document.getElementById('filePhoto$i');
// 											imageLoader$i.addEventListener('change', handleImage$i, false);
										
// 											function handleImage$i(e) {
// 											var reader = new FileReader();
// 											reader.onload = function (event) {
// 												jQuery('#uploader$i img').attr('src',event.target.result);
// 												}
// 											reader.readAsDataURL(e.target.files[0]);
// 											}
// 										})";
									$string.="
										jQuery('#filePhoto$i').change(function() {
											var file = this.files[0];
											var imagefile = file.type;
											var match= ['image/jpeg','image/png','image/jpg'];
											if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2])))
											{
												alert('Please Select A valid Image File! Only jpeg, jpg and png Images type allowed.');
												return false;
											}
											else
											{
												var reader = new FileReader();
												reader.readAsDataURL(this.files[0]);
											}
											jQuery('#index').val($i);
											jQuery('#postads_form').submit();
											});
									";
									$imageview.="var loadFile$i = function(event) {
									var output = document.getElementById('image_wiew$i');
									output.src = URL.createObjectURL(event.target.files[0]);
									};";
									?>
									<li>
										
										<div id="uploader<?php echo $i;?>" class="uploader">
											<div id='preview<?php echo $i;?>'></div>
												<img id="image_wiew<?php echo $i;?>" src="<?php echo $this->baseUrl();?>/images/broweimage.png"/>
												<input type="hidden" id="ads-image<?php echo $i;?>" name="ads-image<?php echo $i;?>" />
												<input class="filephoto" type="file" name="filePhoto<?php echo $i;?>"  id="filePhoto<?php echo $i;?>" accept="image/jpeg,image/gif,image/png" value='' onchange="loadFile<?php echo $i;?>(event)" />
										</div>
										
									</li>
									<?php }
									echo "<script>jQuery(document).ready(function() { jQuery(function() {".$string." }); }); $imageview</script>";?>
								</ul>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Location<span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<select id="location" name="location" class="form-select" onchange="getAllDistrict();">
									<option value="-1" selected="selected">Select Location</option>
									<?php 
										if(!empty($this->rslocation)){
											foreach($this->rslocation as $rsl){
										?>
											<option value="<?php echo $rsl['id'];?>" ><?php echo $rsl['province_en_name'];?></option>
										<?php }
										} 
									?>
								</select>
								<input type="hidden"  name="category" id="category" value="<?php echo $this->cate['id'];?>" />
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>District<span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<select id="district" name="district" class="form-select">
									<option value="-1" selected="selected">Select District</option>
								</select>
							</div>
						</div>
						<div class="form-row">
							<div class="form-label">
								<label>Commune<span class="sign_req">*</span></label>
							</div>
							<div class="form-value">
								<select id="commune" name="commune" class="form-select col-md-10">
									<option value="-1" selected="selected">Select Commune</option>
								</select>
							</div>
						</div>
						<div class="col-md-12">
							<h2 style="text-align: center;">Contact Information</h2>
						</div>
						<div class="col-md-12">
							<div class="col-md-2">
								<label>Name <span class="sign_req">*</span></label>
							</div>
							<div class="col-md-3">
								<input type="hidden"  name="index" id="index"  />
								<input type="text" placeholder="Name" name="name" id="name" class="form-control" />
							</div>
							<div class="col-md-2">
								<label>Phone 1 <span class="sign_req">*</span></label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Phone"  name="phone1" id="phone1" value="<?php echo $this->client_info['phone'];?>"  required="required" class="form-control" />
							</div>
							<div class="col-md-2">
							
							</div>
						</div>
						<div class="col-md-12">
							<div class="col-md-2">
								<label>Phone 2</label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Phone"  name="phone2" id="phone2" class="form-control" />
							</div>
							<div class="col-md-2">
								<label>Email <span class="sign_req">*</span></label>
							</div>
							<div class="col-md-3">
								<input type="text" placeholder="Email"  name="email" id="email" value="<?php echo $this->client_info['email'];?>"  required="required" class="form-control" />
							</div>
							<div class="col-md-2"></div>
						</div>
						<div class="form-row">
							<div class="col-md-2">
								<label>Address <span class="sign_req">*</span></label>
							</div>
							<div class="col-md-8">
								<textarea id="adress" name="adress"  class="form-control " placeholder="Address..."><?php echo $this->client_info['address'];?></textarea>
							</div>
						</div>
						<div class="form-row ">
							<div class="form-label">
							</div>
							<div class="form-value">
								<input type="submit" class="loginBtn register" value='SUBMIT' label='SUBMIT'>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	<footer  class="footer">
		<div class="container footer-grid-3">					
			<div class="row">
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">ABOUT CLASSIADS</h4>			
						<div class="textwidget">
							<p>
							Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop  professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern. 
							</p>
							<div class="widget-social footer-social-widget">
								<a href="#" target="_blank"><i class="fa fa-facebook"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-twitter"></i></a>				
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-pinterest"></i></a>								
								<a href="https://www.facebook.com/" target="_blank"><i class="fa fa-google-plus"></i></a>								
								<a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a>							
							</div>
							<a href="http://demo.designinvento.net/classiads4" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<div class="footer-logo">
							<a class="footer-about-us" href="#" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo">
							</a>
						</div>
						<div class="textwidget text-description">
							<p>
									Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern.						

							</p>
						</div>
					</div>
				</div>
				
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="block-content clearfix">
						<h4 class="block-title">Get In Touch</h4>			
					</div>
				</div>			
			</div>			
		</div>			
	</footer>
	<section class="socket"  style="background-color:#262626;">
		<div class="container">
			<div class="site-info"  style="color:#999999;">
								 All copyrights reserved &#x00040; 2017 - Design &AMP; Development by <a href="http://cam-app.com/">Cam App Technology</a>
			</div><!-- .site-info -->
			<div class="footer-menu">
				<ul id="menu-footer" class="menu"><li id="menu-item-4384" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4384"><a>Home</a></li>
					<li id="menu-item-4328" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4328"><a href="blog/index.html">BLOG</a></li>
					<li id="menu-item-4331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4331"><a href="pricing-plans/index.html">PRICING PLANS</a></li>
					<li id="menu-item-4330" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4330"><a href="contact/index.html">CONTACT</a></li>
				</ul>					
			</div>
		</div>
	</section>
	
</body>
<script>
//$('#city, #commune, #office').select2({ width: '100%' });
//	changeProvince();
		
		/*$('#commune').change(function () {
			changeCommune();
		});*/
		function getAllDistrict() {
			//var pro_id = jQuery('#location').val();
			alert(2777);
			var pro_id = $('#location').val();
			alert(pro_id);
			if (pro_id == '' OR pro_id==-1) {
				//var temHTML = "<option value=''></option>";
				//$('#commune').html(temHTML).select2({ width: '100%' });
				//$('#office').html(temHTML).select2({ width: '100%' });
			}
			else {
				lang=1;
				/*var url_changelang = '<?php //echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
				$.ajax({
						url: url_changelang,
						type: "post",
						data:{'lange':lang},
						success: function(data){
							location.reload();
						},
						error:function(err){
						}
					});*/
				}
				
			/*var list = commune['p' + id];
			var HTML = "<option value=''>-- សូមជ្រើសរើស --</option>";
			$.each(list, function (key, data) {
				var comName = data.name;
				var comList = data.list;
				var optGroup = '<optgroup label="' + comName + '">';
				var temHTML = "";
				$.each(comList, function (k, v) {
					temHTML += '<option value="' + key + "||" + v.com_id + '">' + v.com_name + '</option>';
				});
				HTML += optGroup + temHTML + '</optgroup>';
			})
			$('#commune').html(HTML).select2({ width: '100%' });*/
			
		}
</script>
</html>