<?php 
	$feature = $this->myadsfeature;
	$store = $this->store;
	
	$db = new Application_Model_DbTable_DbStore();
?>
<?php if ($store['template_id']==1){ //check template?>
<title>Store <?php echo $store['alias_store'];?></title>
    <div id="content-block">
        <div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">                            
							 <div class="page-selector">
                                <div class="shop-grid-controls">
                                    <div class="entry">
                                        <div class="view-button active grid"><i class="fa fa-th"></i></div>
                                        <div class="view-button list"><i class="fa fa-list"></i></div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="row shop-grid grid-view">
								<?php if (!empty($feature)) foreach ($feature as $rr){?>
                                <div class="col-md-3 col-sm-4 shop-grid-item">
                                    <div class="product-slide-entry shift-image">
                                       <div class="product-image">
											<?php if (!empty($rr['image_feature'])){?>
												<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rr['image_feature']; ?>" alt="<?php echo $rr['ads_title'];?>" />
											<?php }else{?>
												<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rr['ads_title'];?>" />
											<?php }?>
											
										</div>
										<a class="tag" href="#"><?php echo $rr['category_name'];?></a>
										<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rr['alias'].".html";?>"><?php echo $rr['ads_title'];?></a>
                                        <div class="article-container style-1">
                                            <p>
                                            <?php 
												$str1 = utf8_encode($rr['description']);
												$description = substr($str1, 0, 600);
												echo utf8_decode($description); 
												
												?>
                                            </p>
                                        </div>
	                                    <div class="price">
											<div class="current">$ <?php echo number_format($rr['price'],2);?></div>
										</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
								<?php }?>
                            </div>
                            <div class="page-selector">
                                <div class="pages-box">
                                    <a href="#" class="square-button active">1</a>
                                    <a href="#" class="square-button">2</a>
                                    <a href="#" class="square-button">3</a>
                                    <div class="divider">...</div>
                                    <a href="#" class="square-button"><i class="fa fa-angle-right"></i></a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        <div class="col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8 blog-sidebar">
                            <div class="information-blocks categories-border-wrapper">
                                <div class="block-title size-3">Categories</div>
                                <div class="accordeon">
                                <?php if (!empty($this->parent_cate)) foreach ($this->parent_cate as $rss){ 
                                		$child = $db->getChildCategory($rss['parent']);
                                	?>
                                    <div class="accordeon-title"><?php echo $rss['title'];?></div>
                                    <div class="accordeon-entry">
                                        <div class="article-container style-1">
                                            <ul>
                                            	<?php if (!empty($child)) foreach ($child as $ch){?>
                                                <li><a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=".$ch['alias_category'].".html";?>"><?php echo $ch['title']?></a></li>
                                                <?php }?>
                                            </ul>
                                        </div>
                                    </div>
                               <?php }?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 <?php }else if ($store['template_id']==2){ //check template?>
 	<div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">                            
							 <div class="page-selector">
                                <div class="shop-grid-controls">
                                    <div class="entry">
                                        <div class="view-button active grid"><i class="fa fa-th"></i></div>
                                        <div class="view-button list"><i class="fa fa-list"></i></div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="row shop-grid grid-view">
								<?php if (!empty($feature)) foreach ($feature as $rr){?>
                                <div class="col-md-3 col-sm-4 shop-grid-item">
                                    <div class="product-slide-entry shift-image">
                                       <div class="product-image">
											<?php if (!empty($rr['image_feature'])){?>
												<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rr['image_feature']; ?>" alt="<?php echo $rr['ads_title'];?>" />
											<?php }else{?>
												<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rr['ads_title'];?>" />
											<?php }?>
											
										</div>
										<a class="tag" href="#"><?php echo $rr['category_name'];?></a>
										<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rr['alias'].".html";?>"><?php echo $rr['ads_title'];?></a>
                                        <div class="article-container style-1">
                                            <p>
                                            <?php 
												$str1 = utf8_encode($rr['description']);
												$description = substr($str1, 0, 600);
												echo utf8_decode($description); 
												
												?>
                                            </p>
                                        </div>
	                                    <div class="price">
											<div class="current">$ <?php echo number_format($rr['price'],2);?></div>
										</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
								<?php }?>
                            </div>
                            <div class="page-selector">
                                <div class="pages-box">
                                    <a href="#" class="square-button active">1</a>
                                    <a href="#" class="square-button">2</a>
                                    <a href="#" class="square-button">3</a>
                                    <div class="divider">...</div>
                                    <a href="#" class="square-button"><i class="fa fa-angle-right"></i></a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        <div class="col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8 blog-sidebar">
                            <div class="information-blocks categories-border-wrapper">
                                <div class="block-title size-3">Categories</div>
                                <div class="accordeon">
                                <?php if (!empty($this->parent_cate)) foreach ($this->parent_cate as $rss){ 
                                		$child = $db->getChildCategory($rss['parent']);
                                	?>
                                    <div class="accordeon-title"><?php echo $rss['title'];?></div>
                                    <div class="accordeon-entry">
                                        <div class="article-container style-1">
                                            <ul>
                                            	<?php if (!empty($child)) foreach ($child as $ch){?>
                                                <li><a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=".$ch['alias_category'].".html";?>"><?php echo $ch['title']?></a></li>
                                                <?php }?>
                                            </ul>
                                        </div>
                                    </div>
                               <?php }?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 <?php }?>
