<?php 
	$ads = $this->ads_detail;
	$store = $this->store;
	$db = new Application_Model_DbTable_DbStore();
	
?>
<?php if ($store['template_id']==1){ //check template?>
  	<title><?php echo $ads['ads_title'];?></title>
    <div id="content-block">
        <div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-5 col-md-4 col-lg-5 information-entry">
                            <div class="product-preview-box">
                                <div class="swiper-container product-preview-swiper" data-autoplay="0" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="1">
                                    <div class="swiper-wrapper">
                                      <?php $images = explode(',', $ads['images']);
										
									if (!empty($images))    foreach ($images as $i){
									    ?>
                                        <div class="swiper-slide">
                                            <div class="product-zoom-image">
                                                <img src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" alt="" data-zoom="<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/product-main-1-zoom.jpg" />
                                            </div>
                                        </div>
                                        <?php }?>
                                    </div>
                                    <div class="pagination"></div>
                                </div>
                                <div class="swiper-hidden-edges">
                                    <div class="swiper-container product-thumbnails-swiper" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="3" data-int-slides="3" data-sm-slides="3" data-md-slides="4" data-lg-slides="4" data-add-slides="4">
                                        <div class="swiper-wrapper">
                                        <?php if (!empty($images))  foreach ($images as $k=> $i){?>
                                            <div class="swiper-slide <?php if ($k==0){echo "selected"; }?>">
                                                <div class="paddings-container">
                                                    <img src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" alt="" />
                                                </div>
                                            </div>
                                         <?php }?>
                                          
                                        </div>
                                        <div class="pagination"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-7 col-md-4 information-entry">
                            <div class="product-detail-box">
                                <h1 class="product-title"><?php echo $ads['ads_title'];?></h1>
                                <h3 class="product-subtitle"><?php echo $ads['category_name'];?></h3>
                                <?php if(!empty($this->rsattr))foreach ($this->rsattr as $attr){?>
                                <div class="rating-box">
                                 <div class="rating-number"><?php echo $attr['control_value'];?></div>
                                 </div>
                                 <?php }?>
                                <div class="product-description detail-info-entry"><?php echo $ads['description'];?></div>
                                <div class="price detail-info-entry">
                                    <div class="current">$<?php echo number_format($ads['price'],2);?></div>
                                </div>
                               
                              
                                <div class="share-box detail-info-entry">
                                    <div class="title">Share in social media</div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                        <div class="clear visible-xs visible-sm"></div>
                        <div class="col-md-4 col-lg-3 information-entry product-sidebar">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="information-blocks production-logo">
                                        <div class="background">
                                            <div class="logo"><img src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/production-logo.png" alt="" /></div>
                                            <a href="#">Review this producent</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="information-blocks">
                                        <div class="information-entry products-list">
                                            <h3 class="block-title inline-product-column-title">Featured products</h3>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if (!empty($this->relate_pro)){?>
	               <div class="information-blocks">
						<div class="tabs-container">
							<div class="swiper-tabs tabs-switch">
								<div class="title">Products</div>
								<div class="list">
									<a class="block-title tab-switcher active">Related Ads</a> 
									<div class="clear"></div>
								</div>
							</div>
							<div>
								<div class="tabs-entry">
									<div class="products-swiper">
										<div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
											<div class="swiper-wrapper">
												<?php 	foreach ($this->relate_pro as $relate){ ?>
												<div class="swiper-slide"> 
													<div class="paddings-container">
														<div class="product-slide-entry shift-image">
															<div class="product-image">
																<?php if (!empty($relate['image_feature'])){?>
																	<img src="<?php echo $this->baseUrl()."/images/adsimg/".$relate['image_feature']; ?>" alt="<?php echo $relate['ads_title'];?>" />
																<?php }else{?>
																	<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $relate['ads_title'];?>" />
																<?php }?>
																
															</div>
															<a class="tag" href="#"><?php echo $relate['category_name'];?></a>
															<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$relate['alias'].".html";?>"><?php echo $relate['ads_title'];?></a>
														
															<div class="price">
																<!-- <div class="prev">$199,99</div> -->
																<div class="current">$ <?php echo number_format($relate['price'],2);?></div>
															</div>
														</div>
													</div>
												</div>
												<?php }?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php }?>
            </div>
        </div>
 <?php }else if ($store['template_id']==2){ //check template?>
 <div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-5 col-md-4 col-lg-5 information-entry">
                            <div class="product-preview-box">
                                <div class="swiper-container product-preview-swiper" data-autoplay="0" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="1">
                                    <div class="swiper-wrapper">
                                      <?php $images = explode(',', $ads['images']);
										
									if (!empty($images))    foreach ($images as $i){
									    ?>
                                        <div class="swiper-slide">
                                            <div class="product-zoom-image">
                                                <img src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" alt="" data-zoom="<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/product-main-1-zoom.jpg" />
                                            </div>
                                        </div>
                                        <?php }?>
                                    </div>
                                    <div class="pagination"></div>
                                </div>
                                <div class="swiper-hidden-edges">
                                    <div class="swiper-container product-thumbnails-swiper" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="3" data-int-slides="3" data-sm-slides="3" data-md-slides="4" data-lg-slides="4" data-add-slides="4">
                                        <div class="swiper-wrapper">
                                        <?php if (!empty($images))  foreach ($images as $k=> $i){?>
                                            <div class="swiper-slide <?php if ($k==0){echo "selected"; }?>">
                                                <div class="paddings-container">
                                                    <img src="<?php echo $this->baseUrl()."/images/adsimg/".$i; ?>" alt="" />
                                                </div>
                                            </div>
                                         <?php }?>
                                          
                                        </div>
                                        <div class="pagination"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-7 col-md-4 information-entry">
                            <div class="product-detail-box">
                                <h1 class="product-title"><?php echo $ads['ads_title'];?></h1>
                                <h3 class="product-subtitle"><?php echo $ads['category_name'];?></h3>
                                <?php if(!empty($this->rsattr))foreach ($this->rsattr as $attr){?>
                                <div class="rating-box">
                                 <div class="rating-number"><?php echo $attr['control_value'];?></div>
                                 </div>
                                 <?php }?>
                                <div class="product-description detail-info-entry"><?php echo $ads['description'];?></div>
                                <div class="price detail-info-entry">
                                    <div class="current">$<?php echo number_format($ads['price'],2);?></div>
                                </div>
                               
                              
                                <div class="share-box detail-info-entry">
                                    <div class="title">Share in social media</div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                        <div class="clear visible-xs visible-sm"></div>
                        <div class="col-md-4 col-lg-3 information-entry product-sidebar">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="information-blocks production-logo">
                                        <div class="background">
                                            <div class="logo"><img src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/production-logo.png" alt="" /></div>
                                            <a href="#">Review this producent</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="information-blocks">
                                        <div class="information-entry products-list">
                                            <h3 class="block-title inline-product-column-title">Featured products</h3>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if (!empty($this->relate_pro)){?>
	               <div class="information-blocks">
						<div class="tabs-container">
							<div class="swiper-tabs tabs-switch">
								<div class="title">Products</div>
								<div class="list">
									<a class="block-title tab-switcher active">Related Ads</a> 
									<div class="clear"></div>
								</div>
							</div>
							<div>
								<div class="tabs-entry">
									<div class="products-swiper">
										<div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
											<div class="swiper-wrapper">
												<?php 	foreach ($this->relate_pro as $relate){ ?>
												<div class="swiper-slide"> 
													<div class="paddings-container">
														<div class="product-slide-entry shift-image">
															<div class="product-image">
																<?php if (!empty($relate['image_feature'])){?>
																	<img src="<?php echo $this->baseUrl()."/images/adsimg/".$relate['image_feature']; ?>" alt="<?php echo $relate['ads_title'];?>" />
																<?php }else{?>
																	<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $relate['ads_title'];?>" />
																<?php }?>
																
															</div>
															<a class="tag" href="#"><?php echo $relate['category_name'];?></a>
															<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$relate['alias'].".html";?>"><?php echo $relate['ads_title'];?></a>
														
															<div class="price">
																<!-- <div class="prev">$199,99</div> -->
																<div class="current">$ <?php echo number_format($relate['price'],2);?></div>
															</div>
														</div>
													</div>
												</div>
												<?php }?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php }?>
            </div>
        </div>
 <?php }?>