
<?php $most_view = $this->myadsmostview;
	$feature = $this->myadsfeature;
	$store = $this->store;
	$param = $this->param;
	$page = array();
	$page[0]='';
	if (!empty($param['page'])){
	$page = explode(".", $param['page']);
	}
	$db = new Application_Model_DbTable_DbStore();
?>	
<?php if ($store['template_id']==1){ //check template?>
	<?php if ($page[0]=="contacts-us"){?>
	<title><?php echo "Contact | Store ".$store['alias_store'];?></title>
	  <div id="content-block">
	  		<div class="content-center fixed-header-margin">
            <div class="content-push">
                <div class="contact-spacer"></div>
                <div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-6 information-entry">
                            <div class="map-box type-3">
                                <div class="addresses-block">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7817.600432922891!2d104.87604612254583!3d11.566175167154226!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3b0684563cfa307f!2z4Z6c4Z634Z6R4Z-S4Z6Z4Z624Z6f4Z-S4Z6Q4Z624Z6T4Z6W4Z6g4Z674Z6U4Z6F4Z-S4Z6F4Z-B4Z6A4Z6R4Z-B4Z6f4Z6W4Z-S4Z6a4Z-H4Z6A4Z674Z6f4Z674Z6Y4Z-I!5e0!3m2!1skm!2skh!4v1493090692530" width="800" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry">
                       		<h3 class="block-title main-heading">Contacts Us</h3>
                            <div class="article-container style-1">
                               <!--  <p> laudantium.</p> -->
                               <!--  <h5>Company address</h5> -->
                                <p>Address : <?php echo $store['store_address'];?><br/>
                               	Phone : <?php echo $store['store_phone'];?><br/>
                               <!--  CA 90896<br/> 
                                United States<br/> --></p>
                            </div>
                            
                        </div>
                    </div>
                </div>
			</div>
		</div>
	  </div>
	  <?php }else if($page[0]=="about-us"){?>
	<?php }else{?>
	<title>Store | <?php echo $store['alias_store'];?></title>
    <div id="content-block">
        <div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
						 <div class="navigation-banner-swiper">
                                <div class="swiper-container" data-autoplay="5000" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="1">
                                    <div class="swiper-wrapper">
                                        <div class="swiper-slide active" data-val="0"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/images/borey.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Earrings</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <div class="swiper-slide" data-val="1"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/images/borey.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Wedding</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <div class="swiper-slide" data-val="2"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/images/borey.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Earrings</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                    <div class="pagination"></div>
                                </div>
                            </div>
                            
							 
                        </div>
                        <div class="col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8 blog-sidebar">
                            <div class="information-blocks categories-border-wrapper">
                                <div class="block-title size-3">Categories</div>
                                <div class="accordeon">
                                 <?php if (!empty($this->parent_cate)) foreach ($this->parent_cate as $rss){
                                 	$child = $db->getChildCategory($rss['parent']);
                                 	?>
                                    <div class="accordeon-title"><?php echo $rss['title'];?></div>
                                    <div class="accordeon-entry">
                                        <div class="article-container style-1">
                                            <ul>
                                                <?php if (!empty($child)) foreach ($child as $ch){?>
                                                <li><a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=".$ch['alias_category'].".html";?>"><?php echo $ch['title']?></a></li>
                                                <?php }?>
                                            </ul>
                                        </div>
                                    </div>
                               <?php }?>
                                </div>
                            </div>

                             
                        </div>
                    </div>
                </div>
				<div class="information-blocks">
					<div class="tabs-container">
						<div class="swiper-tabs tabs-switch">
							<div class="title">Products</div>
							<div class="list">
								<a class="block-title tab-switcher active">The Most Views</a> 
								<div class="clear"></div>
							</div>
						</div>
						<div>
							<div class="tabs-entry">
								<div class="products-swiper">
									<div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
										<div class="swiper-wrapper">
											<?php if (!empty($most_view)) foreach ($most_view as $rs){?>
											<div class="swiper-slide"> 
												<div class="paddings-container">
													<div class="product-slide-entry shift-image">
														<div class="product-image">
															<?php if (!empty($rs['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rs['image_feature']; ?>" alt="<?php echo $rs['ads_title'];?>" />
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rs['ads_title'];?>" />
															<?php }?>
															
														</div>
														<a class="tag" href="#"><?php echo $rs['category_name'];?></a>
														<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rs['alias'].".html";?>"><?php echo $rs['ads_title'];?></a>
													
														<div class="price">
															<!-- <div class="prev">$199,99</div> -->
															<div class="current">$ <?php echo number_format($rs['price'],2);?></div>
														</div>
													</div>
												</div>
											</div>
											<?php }?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="information-blocks">
					<div class="tabs-container">
						<div class="swiper-tabs tabs-switch">
							<div class="list">
								<a class="block-title tab-switcher active">Featured Ads</a>
								<div class="clear"></div>
							</div>
						</div>
						<div>
							<div class="tabs-entry feature-ads home-page ">
								<div class="products-swiper">
									<div class="swiper-container">
										<div class="swiper-wrapper">
											<?php if (!empty($feature)) foreach ($feature as $rr){?>
											<div class="swiper-slide"> 
												<div class="paddings-container">
													<div class="product-slide-entry shift-image">
														<div class="product-image">
															<?php if (!empty($rr['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rr['image_feature']; ?>" alt="<?php echo $rr['ads_title'];?>" />
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rr['alias'];?>" />
															<?php }?>
															
														</div>
														<a class="tag" href="#"><?php echo $rr['category_name'];?></a>
														<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rr['alias'].".html";?>"><?php echo $rr['ads_title'];?></a>
													
														<div class="price">
															<div class="current">$ <?php echo number_format($rr['price'],2);?></div>
														</div>
													</div>
												</div>
											</div>
											<?php }?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
            </div>

        </div>
      </div>
      <?php }?>
 <?php }else if ($store['template_id']==2){ //check template?>
 		<?php if ($page[0]=="contacts-us"){?>
	<title><?php echo "Contact | Store ".$store['alias_store'];?></title>
	  <div id="content-block">
            <div class="content-push">
                <div class="contact-spacer"></div>
                <div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-6 information-entry">
                            <div class="map-box type-3">
                                <div class="addresses-block">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7817.600432922891!2d104.87604612254583!3d11.566175167154226!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3b0684563cfa307f!2z4Z6c4Z634Z6R4Z-S4Z6Z4Z624Z6f4Z-S4Z6Q4Z624Z6T4Z6W4Z6g4Z674Z6U4Z6F4Z-S4Z6F4Z-B4Z6A4Z6R4Z-B4Z6f4Z6W4Z-S4Z6a4Z-H4Z6A4Z674Z6f4Z674Z6Y4Z-I!5e0!3m2!1skm!2skh!4v1493090692530" width="800" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry">
                       		<h3 class="block-title main-heading">Contacts Us</h3>
                            <div class="article-container style-1">
                               <!--  <p> laudantium.</p> -->
                               <!--  <h5>Company address</h5> -->
                                <p>Address : <?php echo $store['store_address'];?><br/>
                               	Phone : <?php echo $store['store_phone'];?><br/>
                               <!--  CA 90896<br/> 
                                United States<br/> --></p>
                            </div>
                            
                        </div>
                    </div>
                </div>
			</div>
	  </div>
	  <?php }else if($page[0]=="about-us"){?>
	<?php }else{?>
	<title><?php echo "Store | ".$store['alias_store'];?></title>
   <div class="content-push">
   		<div class="information-blocks">
            <div class="row">
                 <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
					 <div class="information-blocks">
						<div class="tabs-container">
							<div class="swiper-tabs tabs-switch">
								<div class="title">Products</div>
									<div class="list">
										<a class="block-title tab-switcher active">The Most Views</a> 
										<div class="clear"></div>
									</div>
								</div>
								<div>
									<div class="tabs-entry">
										<div class="products-swiper">
											<div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="4" data-add-slides="5">
												<div class="swiper-wrapper">
												<?php if (!empty($most_view)) foreach ($most_view as $rs){?>
												<div class="swiper-slide"> 
													<div class="paddings-container">
														<div class="product-slide-entry shift-image">
															<div class="product-image">
																<?php if (!empty($rs['image_feature'])){?>
																	<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rs['image_feature']; ?>" alt="<?php echo $rs['ads_title'];?>" />
																<?php }else{?>
																	<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rs['ads_title'];?>" />
																<?php }?>
																
															</div>
															<a class="tag" href="#"><?php echo $rs['category_name'];?></a>
															<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rs['alias'].".html";?>"><?php echo $rs['ads_title'];?></a>
														
															<div class="price">
																<div class="current">$ <?php echo number_format($rs['price'],2);?></div>
															</div>
														</div>
													</div>
												</div>
										<?php }?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
               </div>
               <div class="col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8 blog-sidebar">
                    <div class="information-blocks categories-border-wrapper">
                         <div class="block-title size-3">Categories</div>
                         <div class="accordeon">
                         <?php if (!empty($this->parent_cate)) foreach ($this->parent_cate as $rss){
                           	$child = $db->getChildCategory($rss['parent']);
                           ?>
               		        <div class="accordeon-title"><?php echo $rss['title'];?></div>
                                <div class="accordeon-entry">
                                    <div class="article-container style-1">
                                       <ul>
                                          <?php if (!empty($child)) foreach ($child as $ch){?>
                                           <li><a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=".$ch['alias_category'].".html";?>"><?php echo $ch['title']?></a></li>
                                           <?php }?>
                                       </ul>
                                    </div>
                               </div>
                            <?php }?>
                          </div>
                      </div>
                  </div>
              </div>
        </div>
        <div class="information-blocks">
			<div class="tabs-container">
				<div class="swiper-tabs tabs-switch">
					<div class="list">
						<a class="block-title tab-switcher active">Featured Ads</a>
						<div class="clear"></div>
					</div>
				</div>
				<div>
					<div class="tabs-entry feature-ads ">
						<div class="products-swiper">
							<div class="swiper-container">
							<?php if (!empty($feature)) foreach ($feature as $rr){?>
								<div class="swiper-slide"> 
									<div class="paddings-container">
										<div class="product-slide-entry shift-image">
											<div class="product-image">
												<?php if (!empty($rr['image_feature'])){?>
													<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rr['image_feature']; ?>" alt="<?php echo $rr['ads_title'];?>" />
												<?php }else{?>
													<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rr['alias'];?>" />
												<?php }?>
												
											</div>
											<a class="tag" href="#"><?php echo $rr['category_name'];?></a>
											<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rr['alias'].".html";?>"><?php echo $rr['ads_title'];?></a>
										
											<div class="price">
												<div class="current">$ <?php echo number_format($rr['price'],2);?></div>
											</div>
										</div>
									</div>
								</div>
								<?php }?>
							</div>
								
						</div>
					</div>
				</div>
			</div>
		</div>
		 <div class="column-article-wrapper">
                    <div class="row nopadding">
                        <div class="col-sm-6 information-entry left-border nopadding">
                            <div class="column-article-entry">
                                <a class="title" href="<?php echo $this->baseUrl()."/store/index?store=".$store['alias_store']."&page=about-us.html";?> ">About Store</a>
                                <div class="description">
                                  <?php 
									$str1 = utf8_encode($store['store_about_us']);
									$description = substr($str1, 0, 600);
									echo utf8_decode($description); 
									?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry left-border nopadding">
                            <div class="column-article-entry">
                                <a class="title" href="<?php echo $this->baseUrl()."/store/index?store=".$store['alias_store']."&page=contacts-us.html";?>">Contact Us</a>
                                <div class="description">
                                  <p>Address : <?php echo $store['store_address'];?><br/>
                               		Phone : <?php echo $store['store_phone'];?><br/></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
	</div>
	<?php }?>
 <?php }?>
