<!DOCTYPE html>
<?php $most_view = $this->myadsmostview;
	$feature = $this->myadsfeature;
	$store = $this->store;
	
	$db = new Application_Model_DbTable_DbStore();
?>
<html>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <link href="<?php echo $this->baseUrl();?>/template/subtemplate/template1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl();?>/template/subtemplate/template1/css/idangerous.swiper.css" rel="stylesheet" type="text/css" />
    <!-- <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" /> -->
    <link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
    <link href="<?php echo $this->baseUrl();?>/template/subtemplate/template1/css/style.css" rel="stylesheet" type="text/css" />
    <!--[if IE 9]>
        <link href="css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
  <!--   <link rel="shortcut icon" href="img/favicon-6.ico" /> -->
  	<title>Store | <?php echo $store['alias_store'];?></title>
<body class="style-10">
 <!-- HEADER -->
            <div class="header-wrapper style-10">
                <header class="type-1">

                    <div class="header-product">
                        <div class="logo-wrapper">
                            <a href="<?php echo $this->baseUrl()."/store/index?store=".$store['alias_store'].".html";?>" id="logo">
                            <?php if (!empty($store['logo_store'])){?>
                           	 <img alt="" src="<?php echo $this->baseUrl()."/images/store/".$store['logo_store'];?>">
                           	 <?php }else{?>
                           	 	<h2 class="logo_charecter"><?php echo $store['customer_name'];?></h2>
                           	 <?php }?>
                            </a>
                        </div>
						  <div class="product-header-message">
                            FREE SHIPPING ON ALL UK ORDERS this week
                        </div>
                       <div class="product-header-content">
                            <div class="line-entry">
                                <div class="header-top-entry increase-icon-responsive">
                                    <div class="title"><i class="fa fa-facebook"></i></div>
                                </div>
								<div class="header-top-entry increase-icon-responsive">
                                    <div class="title"><i class="fa fa-twitter"></i> </div>
                                </div>
								<div class="header-top-entry increase-icon-responsive">
                                    <div class="title"><i class="fa fa-google-plus"></i> </div>
                                </div>
								<div class="header-top-entry increase-icon-responsive">
                                    <div class="title"><i class="fa fa-youtube"></i> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="close-header-layer"></div>
                    <div class="navigation">
                        <div class="nav-overflow">
                            <nav>
                                <ul>
                                    <li class="full-width">
                                        <a href="<?php echo $this->baseUrl()."/store/index?store=".$store['alias_store'].".html";?>" class="active">Home</a>
                                    </li>
									<li class="full-width">
                                        <a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=allads.html";?>" class="">All Ads</a>
                                    </li>
                                    <li class="simple-list">
                                        <a href="<?php echo $this->baseUrl()."/store/index?page=about-us.html";?>">About Us</a>
                                    </li>
                                    <li class="full-width-columns">
                                        <a href="<?php echo $this->baseUrl()."/store/index?page=contacts-us.html";?>">Contact Us</a>
                                    </li>
                                </ul>

                                <div class="clear"></div>
                            </nav>                           
                           
                        </div>
                    </div>
                </header>
                <div class="clear"></div>
            </div>
    <!-- LOADER -->
    <div id="loader-wrapper">
        <div class="bubbles">
            <div class="title">loading</div>
            <span></span>
            <span id="bubble2"></span>
            <span id="bubble3"></span>
        </div>
    </div>

    <div id="content-block">
        <div class="content-center ">
            <div class="content-push">
				<div class="information-blocks">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
						 <div class="navigation-banner-swiper">
                                <div class="swiper-container" data-autoplay="5000" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="1">
                                    <div class="swiper-wrapper">
                                        <div class="swiper-slide active" data-val="0"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/jewellery-1.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Earrings</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <div class="swiper-slide" data-val="1"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/jewellery-2.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Wedding</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                        <div class="swiper-slide" data-val="2"> 
                                            <div class="navigation-banner-wrapper light-text align-1" style="background-image: url(<?php echo $this->baseUrl();?>/template/subtemplate/template1/img/jewellery-3.jpg);">
                                                <div class="navigation-banner-content">
                                                    <div class="cell-view">
                                                        <h2 class="subtitle">New special collection</h2>
                                                        <h1 class="title">Earrings</h1>
                                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipiscing  elit, sed do eiusmod tempor incididunt.</div>
                                                        <div class="info">
                                                            <a class="button style-1" href="#">Shop Now</a>
                                                            <a class="button style-1" href="#">Features</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="clear"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                    <div class="pagination"></div>
                                </div>
                            </div>
                            
							 
                        </div>
                        <div class="col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8 blog-sidebar">
                            <div class="information-blocks categories-border-wrapper">
                                <div class="block-title size-3">Categories</div>
                                <div class="accordeon">
                                 <?php if (!empty($this->parent_cate)) foreach ($this->parent_cate as $rss){
                                 	$child = $db->getChildCategory($rss['parent']);
                                 	?>
                                    <div class="accordeon-title"><?php echo $rss['title'];?></div>
                                    <div class="accordeon-entry">
                                        <div class="article-container style-1">
                                            <ul>
                                                <?php if (!empty($child)) foreach ($child as $ch){?>
                                                <li><a href="<?php echo $this->baseUrl()."/store/ads?store=".$store['alias_store']."&page=".$ch['alias_category'].".html";?>"><?php echo $ch['title']?></a></li>
                                                <?php }?>
                                            </ul>
                                        </div>
                                    </div>
                               <?php }?>
                                </div>
                            </div>

                             
                        </div>
                    </div>
                </div>
				<div class="information-blocks">
					<div class="tabs-container">
						<div class="swiper-tabs tabs-switch">
							<div class="title">Products</div>
							<div class="list">
								<a class="block-title tab-switcher active">The Most Views</a> 
								<div class="clear"></div>
							</div>
						</div>
						<div>
							<div class="tabs-entry">
								<div class="products-swiper">
									<div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
										<div class="swiper-wrapper">
											<?php if (!empty($most_view)) foreach ($most_view as $rs){?>
											<div class="swiper-slide"> 
												<div class="paddings-container">
													<div class="product-slide-entry shift-image">
														<div class="product-image">
															<?php if (!empty($rs['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rs['image_feature']; ?>" alt="<?php echo $rs['ads_title'];?>" />
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rs['ads_title'];?>" />
															<?php }?>
															
														</div>
														<a class="tag" href="#"><?php echo $rs['category_name'];?></a>
														<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rs['alias'].".html";?>"><?php echo $rs['ads_title'];?></a>
													
														<div class="price">
															<!-- <div class="prev">$199,99</div> -->
															<div class="current">$ <?php echo number_format($rs['price'],2);?></div>
														</div>
													</div>
												</div>
											</div>
											<?php }?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="information-blocks">
					<div class="tabs-container">
						<div class="swiper-tabs tabs-switch">
							<div class="list">
								<a class="block-title tab-switcher active">Featured Ads</a>
								<div class="clear"></div>
							</div>
						</div>
						<div>
							<div class="tabs-entry feature-ads home-page ">
								<div class="products-swiper">
									<div class="swiper-container">
										<div class="swiper-wrapper">
											<?php if (!empty($feature)) foreach ($feature as $rr){?>
											<div class="swiper-slide"> 
												<div class="paddings-container">
													<div class="product-slide-entry shift-image">
														<div class="product-image">
															<?php if (!empty($rr['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/adsimg/".$rr['image_feature']; ?>" alt="<?php echo $rr['ads_title'];?>" />
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimagefound.jpg"; ?>" alt="<?php echo $rr['alias'];?>" />
															<?php }?>
															
														</div>
														<a class="tag" href="#"><?php echo $rr['category_name'];?></a>
														<a class="title" href="<?php echo $this->baseUrl()."/store/details?store=".$store['alias_store']."&ads=".$rr['ads_title'].".html";?>"><?php echo $rr['ads_title'];?></a>
													
														<div class="price">
															<div class="current">$ <?php echo number_format($rr['price'],2);?></div>
														</div>
													</div>
												</div>
											</div>
											<?php }?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
            </div>

        </div>
        <div class="clear"></div>
		  <!-- FOOTER -->
            <div class="footer-wrapper style-9">
                <footer class="type-2">
                    <div class="position-center">
                      <?php if (!empty($store['logo_store'])){?>
                        <img alt="" src="<?php echo $this->baseUrl()."/images/store/".$store['logo_store'];?>" class="footer-logo">
                           	 <?php }else{?>
                           	 <h2 class="logo_charecter footer"><?php echo $store['customer_name'];?></h2>
                         <?php }?>
                        <div class="footer-links">
                            <a href="<?php echo $this->baseUrl()."/store/index?store=".$store['alias_store'].".html";?>">Home</a>
                            <a href="<?php echo $this->baseUrl()."/store/index?page=about-us.html";?>">About us</a>
                            <a href="<?php echo $this->baseUrl()."/store/index?page=contacts-us.html";?>">Contact Us</a>
                        </div>
                        <div class="copyright">Created with by <a href="#">8theme</a>. All right reserved</div>
                    </div>
                </footer>
            </div>
       </div>

  
    <!-- <script src="js/jquery-2.1.3.min.js"></script> -->
    <script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
    <script src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/js/idangerous.swiper.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/js/global.js"></script>

    <!-- custom scrollbar -->
    <script src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/js/jquery.mousewheel.js"></script>
    <script src="<?php echo $this->baseUrl();?>/template/subtemplate/template1/js/jquery.jscrollpane.min.js"></script>
</body>
</html>
