<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate('ADD_NEW_SLIDE_SHOW');?></title>
<form id='add_slide' action="<?php echo $this->url(array('module'=>'other','controller'=>'slideshow','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="70%" style="margin-top:5px;margin: 0 auto;">
	<tr class="header">
		<td><?php echo $tr->translate('Add New Banner');?></td>
	</tr>
	<tr>
		<td>
		<fieldset>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate('Banner Title');?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="title" name="title" value="" type="text"></td>
							<td><?php echo $tr->translate('Banner Image');?></td>
							<td><input required="true" class="fullside" id="photo" name="photo" type="file"></td>	
						</tr>
						<tr>
							<td><?php echo $tr->translate('Position');?></td>
							<td>
								<select name="position" id="position" dojoType="dijit.form.FilteringSelect">
									<?php if(!empty($this->postion))foreach($this->postion as $rs){?>
										<option value="<?php echo $rs['key_code'];?>"><?php echo $rs['name_en'];?></option>
									<?php }?>
								</select>
							</td>
							<td><?php echo $tr->translate('Page Asign');?></td>
							<td><select name="page_asign" id="page_asign" dojoType="dijit.form.FilteringSelect">
									<?php if(!empty($this->page))foreach($this->page as $rs){?>
										<option value="<?php echo $rs['key_code'];?>"><?php echo $rs['name_en'];?></option>
									<?php }?>
								</select></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('Start Date'); ?></td>
							<td><input constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo date("d-m-Y");?>" dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="start_date" name="start_date" type="text"></td>
							<td><?php echo $tr->translate('End Date');?></td>
							<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('Ordering');?></td>
							<td><input dojoType="dijit.form.TextBox" value="1" required="true" class="fullside" id="ordering" name="ordering" type="text"></td>
							<td><?php echo $tr->translate('Category');?></td>
							<td>
								<select id="category" name="category" dojoType="dijit.form.FilteringSelect">
									<option value="-1">Select Category</option>
								<?php 
									if(!empty($this->rscate))foreach($this->rscate as $cate){
								?>
										<option value="<?php echo $cate['id'];?>"><?php echo $cate['name'];?></option>
								<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('Link Url');?></td>
							<td><input dojoType="dijit.form.TextBox" class="fullside" id="link" name="link" type="text"></td>
							<td><?php echo $tr->translate('Status');?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1"><?php echo $tr->translate('ACTIVE');?></option>
								    <option value="0"><?php echo $tr->translate('DEACTIVE');?></option>
								</select>
							</td>
						
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
	<tr class="footer_button">
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
				 iconClass="dijitIconClear" />
			 <input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
				 iconClass="dijitEditorIcon dijitEditorIconSave" />  
			<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVE_NEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
				 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		</td> 
	</tr>
</table>	
</form>
<script>
	require(["dijit/form/DateTextBox"]);
</script>