<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>Slide Show</title>
<style>
.slideshow a{color: #333333;}
</style>
<?php 
		$stringPagination = '<script type="text/javascript">
		$(document).ready(function(){
		$("#exportExcel").tablesorter();
		 
		$("#exportExcel").tablesorter().tablesorterPager({container: $("#pagination_exportExcel"),size: 50});
		$("input:.pagedisplay").focus(function(){ this.blur(); });
		 
		function changeColor(){
		alert("change color on mouse over");
		}
		});
		</script>
		<div id="pagination_exportExcel" class="pager" >
		<form >
		<table  style="width: 200px;"><tr>
		<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
		<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
		<td><input type="text" class="pagedisplay"/></td>
		<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
		<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
		<td><select class="pagesize" >
		<option value="10">10</option>
		<option value="20">20</option>
		<option value="30">30</option>
		<option value="40">40</option>
		<option selected="selected" value="50">50</option>
		<option value="60">60</option>
		<option value="70">70</option>
		<option value="80">80</option>
		<option value="90">90</option>
		<option value="100">100</option>
		</select>
		</td>
		</tr>
		</table>
		</form>
		</div> ';
?>
<form name="list">
 <div >
  <table class="collape tablesorter" id="exportExcel" width="100%">
	   <thead>
		    <tr>
			    <th class="tdheader header"><?php echo $tr->translate('No');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Title');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Ordering');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Photo');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Start Date');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('End Date');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Position');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Asign');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Status');?></th>
		      </tr>
	     </thead>
     	</tbody>
     <?php $r=0; if(!empty($this->rows)){foreach ($this->rows as $key =>$row){
	      if($r%2==0)$attb='normal';
	      else $attb='alternate';
      $r++;
      	?>
	       <tr align="center" class='slideshow <?php echo $attb; ?>'>
			  	<td style="border:1px solid #ccc;padding:1px;" align="center"><?php echo $key+1;?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a href="<?php echo $this->baseUrl().'/other/slideshow/edit/id/'.$row['id'];?>"><?php echo $row['banner_name'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a href="<?php echo $this->baseUrl().'/other/slideshow/edit/id/'.$row['id'];?>"><?php echo $row['ordering'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;text-align: center;" ><a href="<?php echo $this->baseUrl().'/other/slideshow/edit/id/'.$row['id'];?>"><img src="<?php echo $this->baseUrl().'/images/slideshow/'.$row['image'];?>"  style="max-height:50px;"/></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo date("d/m/Y",strtotime($row['start_date']));?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo date("d/m/Y",strtotime($row['end_date']));?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['position'];?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['asign_page'];?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['status'];?></td>
		  </tr>
      <?php }?>
     </tbody>
     </table>
   </div>
  </form>
  <div class="footer_list"><?php echo $stringPagination; ?><span class="row_num"><?php echo $tr->translate('NUM-RECORD')." ".count($this->row)?></span></div>
    <?php }else{?>
    	</table></div><center style="font-size:18pt;"><label id="data_table">No record</label></center></form>
    <?php }?> 