<?php 
$db = new Application_Model_DbTable_DbVdGlobal();
$db_select = new Application_Model_DbTable_DbGlobalselect();
$lang =$db->getLaguage();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$menu_items = $db_select->getMenuItems();

$sess_search=new Zend_Session_Namespace('homesearch');
$keywork_search = $sess_search->keywork_search;
if(empty($sess_search)){
	$keywork_search= $sess_search->keywork_search='';
	$category_search = $sess_search->category_search=-1;
	$location_search = $sess_search->location_search=-1;
}else{
	$keywork_search=@$this->search['keywork_search'];
	$category_search = $this->search['category_search'];
	$location_search = $this->search['location_search'];
}
	$request=Zend_Controller_Front::getInstance()->getRequest()->getParam("cateid");
	$db = new Application_Model_DbTable_DbGlobalselect();
	$maincatealia = $db->getCategoryInfo($request);
	$parent_alia = $maincatealia['parent_alias_category']; 
	
	$session_lang=new Zend_Session_Namespace('lang');
	$currentlang = $session_lang->lang_id;
?>
<head>
<meta charset="UTF-8">
	<script type='text/javascript' src="<?php echo $this->baseurl()."/js/jquery.min.js";?>"></script>
	<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
	<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
	<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
	<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />
	<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>
	<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<section id="static-image2" class=" static-image-2" >
			<div class="container search-bar search-bar-version4">
				<div id="advanced-search-widget-version2" class="home-search">
					<div class="">
						<div class="advanced-search-widget-content">
							<form action="<?php echo $this->url(array("module"=>'default','controller'=>'listads','action'=>'result'));?>" method="post" id="views-exposed-form-search-view-other-ads-page" accept-charset="UTF-8">
								<div id="edit-search-api-views-fulltext-wrapper" class="views-exposed-widget views-widget-filter-search_api_views_fulltext">
									<div class="views-widget">
										<div class="control-group form-type-textfield form-item-search-api-views-fulltext form-item">
											<div class="controls"> 
												<input placeholder="<?php echo $tr->translate("Search your keyword here");?>..." type="text" id="edit-search-api-views-fulltext" name="keywork_search" value="<?php echo $keywork_search;?>" size="30" maxlength="128" class="form-text">
											</div>
										</div>
									</div>
								</div>
								<div id="edit-field-category-wrapper" class="views-exposed-widget views-widget-filter-field_category">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-field-category form-item">
											<div class="controls"> 
												<select id="edit-field-category" name="category_search" class="form-select">												
													<option value="-1" selected="selected"><?php echo $tr->translate("Choose Category");?></option>
													<?php 
														$db = new Application_Model_DbTable_DbVdGlobal();
														$rscate = $db->getCategory();
														if(!empty($rscate)){
															foreach($rscate as $rsc){
														?>
															<option value="<?php echo $rsc['id'];?>" <?php if($category_search==$rsc['id']){ echo'selected="selected"';}?> ><?php echo $rsc['name'];?></option>
														<?php }
														} 
													?>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div id="edit-ad-location-wrapper" class="views-exposed-widget views-widget-filter-field_ad_location">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-ad-location form-item">
											<div class="controls"> 
												<select id="edit-ad-location" name="location_search" class="form-select locationRadius" style="display: none;">
													<option value="-1"><?php echo $tr->translate("Choose Location");?></option>
													<?php 
														$db = new Application_Model_DbTable_DbGlobalselect();
														$rslocation = $db->getAllLocation();
														if(!empty($rslocation)){
															foreach($rslocation as $rsl){
														?>
															<option value="<?php echo $rsl['id'];?>" <?php if($location_search==$rsl['id']){ echo'selected="selected"';}?>><?php echo $rsl['province_name'];?></option>
														<?php }
														} 
													?>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div id="edit-ad-location-wrapper" class="views-exposed-widget views-widget-filter-field_ad_location">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-ad-location form-item">
											<button class="btn btn-primary form-submit" id="edit-submit-search-view" name="submit_search" value="Search Now" type="submit"><span><?php echo $tr->translate("Search Now");?><i class="fa fa-search"></i></span></button>
										</div>
									</div>
								</div>
								<div class="views-exposed-widget views-submit-button">
									<button class="btn btn-primary form-submit" id="edit-submit-search-view" name="advance_search" value="Search Now" type="button" onclick="window.location ='<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'advancesearch'),null,true);?>'" ><span><?php echo $tr->translate("Advance Search");?><i class="fa fa-search"></i></span></button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>	
			<div class="banner-cat-container">
				<div class="container">		
					<div id="main-category">
						<div  class="pos-relative">
							<ul class="nav nav-tabs tabs cat-list" id="tabs">
								<li class='<?php if($parent_alia=='')echo"active";?>'>
									<a href="#homepage">
										<span class="cat-tit">
										<i class="fa fa-home" aria-hidden="true"></i><br />
											<?php 
											$tr = Application_Form_FrmLanguages::getCurrentlanguage();
											echo $tr->translate("HOME");?>
										</span>
									</a>
								</li>
								<?php 
								$db = new Application_Model_DbTable_DbVdGlobal();
								$rscate = $db->getCategoryParent();
								if(!empty($rscate)){foreach($rscate as $index => $rs){
										$class='';
										if($parent_alia==$rs['alias_category']){$class='active';}
								?>
								<li class="<?php echo $class;?>">
									<a href="<?php echo "#".$rs['alias_category']?>" onclick="return false;">
										<span class="cat-tit">
											<i class="fa <?php echo $rs['fontawsome_icon'];?>"></i>
											<br />
											<?php echo $rs['name'];?>									
										</span>
									</a>
								</li>
								<?php }
								}?>
							</ul>
						</div>
					</div>
					<div class="tab-content">
						<div class="tab-pane subcategory-menu <?php if($parent_alia=='')echo"active";?>" id="homepage">
							<div class="list-dropdow-category" >
								<div class="banner-left-blog">
									<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
								</div>
								<div class="blog-sub-categories-cener">
									<ul class="menu-list-cate">
										<?php if (!empty($menu_items)) foreach ($menu_items as $rs){?>
										<li class="menu-list-cate"><a href="<?php echo $this->baseUrl()."/page/index?param=".$rs['alias_menu'].".html";?>"><?php echo $rs['title'];?></a></li>
										<?php }?>
										
									 </ul>
								</div>
								<div class="banner-right-blog">
								</div>
							</div>
						</div>
						<?php 
								$db = new Application_Model_DbTable_DbVdGlobal();
								$rscate = $db->getCategoryParent(1);
								$parent = '';
								
								if(!empty($rscate)){foreach($rscate as $index => $rs){
									$classactive='';
									if($parent_alia==$rs['parent_alias']){
										$classactive='active';
									}
								?>
								<?php if($parent!=$rs['parent']){
								       if($index >0 ){
									?>
									 </ul><!-- close 1 -->
									</div>
								  </div>
							 	</div>
							 	<div class="tab-pane subcategory-menu <?php echo $classactive;?>" id="<?php echo $rs['parent_alias'];?>">
									<div class="list-dropdow-category" >
									<!-- <div class="banner-left-blog">
										<img src="images/camapplogo.png" alt="Logo">
									</div> -->
									<?php 
									$classli='blog-sub-categories';
									if($rs['parent_alias']=='Jobs'){
										$classli='blog-sub-categoriesjob';
									}
									?>
									<div class="<?php echo $classli;?>">
										<ul class="menu-list-cate">
								<?php }else{?>
								<div class="tab-pane subcategory-menu <?php echo $classactive;?>" id="<?php echo $rs['parent_alias']?>">
									<div class="list-dropdow-category" >
									<div class="banner-left-blog">
										<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
									</div>
									<div class="blog-sub-categories">
										<ul class="menu-list-cate"><!-- open 1 -->
								<?php }
 								}?>
									<li class="menu-list-cate"><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$rs['alias_category'].".html";?>"><?php echo $rs['name'];?></a></li>
								<?php 
								$parent=$rs['parent'];
								}//end loop
								?>
								 	<span style="clear: both;"></span></ul><!-- close 1 -->
									</div><span style="clear: both;"></span>
								  </div>
							 	</div>
								<?php 
							}//end if?>
					</div>
				</div>
				<span style="clear: both;"></span>
			</div>	
				<span style="clear: both;"></span>			
	</section>
	<span style="clear: both;"></span>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
	<script>		
		var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
		function changeLange(lang){
			$.ajax({
				url: url_changelang,
				type: "post",
				data:{'lange':lang},
				success: function(data){
					location.reload();
				},
				error:function(err){
				}
			});
		}
		<?php if ($currentlang==1){?>
			var monthNames = [
			                  "Jan", "Feb", "Mar",
			                  "Apr", "May", "Jun", "Jul",
			                  "Aug", "September", "Oct",
			                  "Nov", "Dec"
			                ];
	      <?php }else{?>
	      var monthNames = [
		                  "មករា", "កុម្ភៈ", "មិនា",
		                  "មេសា", "ឧសភា", "មិថុនា", "កក្កដា",
		                  "សីហា", "កញ្ញា", "តុលា",
		                  "វិច្ឆិការ", "ធ្នូ"
		                ];
	      <?php }?>
	      var baseurl = '<?php echo $this->baseUrl();?>';
	</script>