<?php $db = new Application_Model_DbTable_DbVdGlobal();
$lang =$db->getLaguage();
?>
<head>
	<meta charset="UTF-8">
	<title>Cam App Technology</title>	
	<link rel="shortcut icon" href="wp-content/uploads/2016/04/favicon.jpg" type="image/x-icon" />
<!--[if lt IE 9]>
<link rel='stylesheet' id='classiads-ie-css'  href='http://demo.designinvento.net/classiads5/wp-content/themes/classiads/css/ie.css?ver=2013-11-08' type='text/css' media='all' />
<![endif]-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='awesomefont-style-css'  href='<?php echo $this->baseUrl();?>/template/css/font-awesome/css/font-awesome.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />

<link rel='stylesheet' id='bxslider-style-css'  href='<?php echo $this->baseUrl();?>/template/css/jquery.bxslider.css' type='text/css' media='all' />
<link rel='stylesheet' id='owl-carousel-css'  href='<?php echo $this->baseUrl();?>/template/css/owl.carousel.css' type='text/css' media='all' />

<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />


<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/include/js/jquery/jquery-migrate.min.js'></script>

<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fancybox.packe.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/fitvidse.js'></script>

<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />
</head>
<section id="static-image2" class=" static-image-2" >
			<div class="container search-bar search-bar-version4">
				<div id="advanced-search-widget-version2" class="home-search">
					<div class="">
						<div class="advanced-search-widget-content">
							<form action="#" method="get" id="views-exposed-form-search-view-other-ads-page" accept-charset="UTF-8">
								<div id="edit-search-api-views-fulltext-wrapper" class="views-exposed-widget views-widget-filter-search_api_views_fulltext">
									<div class="views-widget">
										<div class="control-group form-type-textfield form-item-search-api-views-fulltext form-item">
											<div class="controls"> 
												<input placeholder="Search your keyword here..." type="text" id="edit-search-api-views-fulltext" name="s" value="" size="30" maxlength="128" class="form-text">
												<input type="hidden" id="hidden-keyword" name="s" value="all" size="30" maxlength="128" class="form-text">
											</div>
										</div>
									</div>
								</div>
								<div id="edit-field-category-wrapper" class="views-exposed-widget views-widget-filter-field_category">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-field-category form-item">
											<div class="controls"> 
												<select id="edit-field-category" name="category_name" class="form-select" style="display: none;">												
													<option value="-1" selected="selected">Select Category</option>
													<?php 
														$db = new Application_Model_DbTable_DbVdGlobal();
														$rscate = $db->getCategory();
// 														print_r($rscate);exit();
														if(!empty($rscate)){
															foreach($rscate as $rsc){
														?>
															<option value="<?php echo $rsc['id'];?>" ><?php echo $rsc['name'];?></option>
														<?php }
														} 
													?>
													
												</select>
											</div>
										</div>
									</div>
								</div>
								<div id="edit-ad-location-wrapper" class="views-exposed-widget views-widget-filter-field_ad_location">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-ad-location form-item">
											<div class="controls"> 
												<select id="edit-ad-location" name="geo-radius" class="form-select locationRadius" style="display: none;">
													<option value="-1" selected="selected">Select Location</option>
													<?php 
														$db = new Application_Model_DbTable_DbGlobalselect();
														$rslocation = $db->getAllLocation();
														if(!empty($rslocation)){
															foreach($rslocation as $rsl){
														?>
															<option value="<?php echo $rsl['id'];?>" ><?php echo $rsl['province_en_name'];?></option>
														<?php }
														} 
													?>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div id="edit-ad-location-wrapper" class="views-exposed-widget views-widget-filter-field_ad_location">
									<div class="views-widget">
										<div class="control-group form-type-select form-item-ad-location form-item">
											<button class="btn btn-primary form-submit" id="edit-submit-search-view" name="" value="Search Now" type="submit"><span>Search Now<i class="fa fa-search"></i></span></button>
										</div>
									</div>
								</div>
								<input type="text" name="geo-location" id="geo-location" value="off" data-default-value="off">
								<input type="hidden" name="post_location" id="hid_post_location" value="All" >
								<input type="text" name="geo-radius-search" id="geo-radius-search" value="500" data-default-value="500">
								<input type="text" name="geo-search-lat" id="geo-search-lat" value="0" data-default-value="0">
								<input type="text" name="geo-search-lng" id="geo-search-lng" value="0" data-default-value="0">
								
								<div class="views-exposed-widget views-submit-button">
									<button class="btn btn-primary form-submit" id="edit-submit-search-view" name="" value="Search Now" type="submit"><span>Advance Search<i class="fa fa-search"></i></span></button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>	
			<div class="banner-cat-container">
				<div class="container">		
					<div id="main-category">
						<div  class="pos-relative">
							<ul class="nav nav-tabs tabs cat-list" id="tabs">
								<?php 
								$db = new Application_Model_DbTable_DbVdGlobal();
								$rscate = $db->getCategoryParent();
								if(!empty($rscate)){foreach($rscate as $index => $rs){
										$class='';
										if($index==0){$class='active';}
								?>
								<li class="<?php echo $class;?>">
									<a href="<?php echo "#".$rs['alias_category']?>">
										<span class="cat-tit">
											<i class="fa fa-home"></i><br />
											<?php echo $rs['name'];?>									
										</span>
									</a>
								</li>
								<?php }
								}?>
								<li>
									<a href="#Trandom">
										<span class="cat-tit">
											<?php 
												$tr = Application_Form_FrmLanguages::getCurrentlanguage();
											echo $tr->translate("STATUS");?>
										</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="tab-content">
						<div class="tab-pane active subcategory-menu" id="Tlatest">
							<div class="list-dropdow-category" >
								<div class="banner-left-blog">
									<a href="<?php echo $this->baseUrl();?>/index"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="Logo"></a>
								</div>
								<div class="blog-sub-categories-cener">
									<ul class="menu-list-cate">
										<li class="menu-list-cate"><a href="#">Private Policy</a></li>
										<li class="menu-list-cate"><a href="#">Ads Posting Rule</a></li>
										<li class="menu-list-cate"><a href="#">How To Use</a></li>
										<li class="menu-list-cate"><a href="#">About Us</a></li>
										<li class="menu-list-cate"><a href="#">Contacts Us</a></li>
									 </ul>
								</div>
								<div class="banner-right-blog">
									<div class="language">
										<?php if (!empty($lang)) foreach ($lang as $rs){?>
										<a class="lang <?php echo $rs['class'];?>" href="#" title="<?php echo $rs['title'];?>" onclick="changeLange(<?php echo $rs['id'];?>);"><img src="<?php echo $this->baseUrl();?>/images/<?php echo $rs['iconImage'];?>" > <?php echo $rs['title'];?></a>
										<?php }?>
									</div>
									<div class="login-register">
										<button class="loginBtn loginBtn-normal">
										  Login
										</button>
										<button class="loginBtn register" onclick="window.location.href='<?php echo $this->baseUrl();?>/index/register'">
										  Register
										</button>
									</div>
									<div class="button-facebook">
										<button class="loginBtn loginBtn--facebook">
										  Login with Facebook
										</button>
									</div>
									<div class="button-postads">
										<button class="loginBtn loginBtn-postads-free" onclick="window.location.href='<?php echo $this->baseUrl();?>/postsads/choose-category'">
										  Post Free Ads
										</button>
									</div>
								</div>
							</div>
						</div>
						<?php 
								$db = new Application_Model_DbTable_DbVdGlobal();
								$rscate = $db->getCategoryParent(1);
								$parent = '';
								if(!empty($rscate)){foreach($rscate as $index => $rs){
								?>
								<?php if($parent!=$rs['parent']){
								       if($index >0 ){
									?>
									 </ul><!-- close 1 -->
									</div>
								  </div>
							 	</div>
							 	<div class="tab-pane subcategory-menu" id="<?php echo $rs['parent_alias'];?>">
									<div class="list-dropdow-category" >
									<!-- <div class="banner-left-blog">
										<img src="images/camapplogo.png" alt="Logo">
									</div> -->
									<?php 
									$classli='blog-sub-categories';
									if($rs['parent_alias']=='Jobs'){
										$classli='blog-sub-categoriesjob';
									}
									?>
									<div class="<?php echo $classli;?>">
										<ul class="menu-list-cate">
								<?php }else{?>
								<div class="tab-pane subcategory-menu" id="<?php echo $rs['parent_alias']?>">
									<div class="list-dropdow-category" >
									<div class="banner-left-blog">
									<img src="images/camapplogo.png" alt="Logo">
									</div>
									<div class="blog-sub-categories">
										<ul class="menu-list-cate"><!-- open 1 -->
								<?php }
 								}?>
									<li class="menu-list-cate"><a href="<?php echo $this->baseUrl()."/listads/index/cateid/".$rs['alias_category'];?>"><?php echo $rs['name'];?></a></li>
								<?php 
								$parent=$rs['parent'];
								}//end loop
								?>
								 	<span style="clear: both;"></span></ul><!-- close 1 -->
									</div><span style="clear: both;"></span>
								  </div>
							 	</div>
								<?php 
							}//end if?>
					</div>
				</div>
				<span style="clear: both;"></span>
			</div>	
				<span style="clear: both;"></span>			
	</section>
	<span style="clear: both;"></span>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/bootstrap.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.bxslider.mine.js'></script> <!--form search-->
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/custome.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.isotope.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/owl.carousel.mine.js'></script>
	<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/jquery.tools.mine.js'></script>
	<script src="<?php echo $this->baseUrl();?>/template/javascript/jquery.sortable.js"></script>
	<script>		
		var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
		function changeLange(lang){
			$.ajax({
				url: url_changelang,
				type: "post",
				data:{'lange':lang},
				success: function(data){
					location.reload();
				},
				error:function(err){
					
				   
				}
			});
			
			/*dojo.xhrPost({
				url: url_changelang,
			    content :{ 
					    'lange':lang,
				},	
				handleAs:"json",
				load: function(data) {
					
				},
				error: function(err) {
					
				}
			});*/
		}
	</script>