<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<footer  class="footer">
		<div class="container">					
			<div class="row">
				<div class="col-md-4 col-sm-6 left-blog">
					<div class="block-content ">
						<h4><span class="footer-title"><?php echo $tr->translate("About Us");?></span></h4>
						<p>
						<span class="value">Cam App Technology is the company provide the best IT solutions in Cambodia it was found by professional humane resource of information technology members.Moreover we have many experience with design and develop  professional website.We are focus on the following:Reliability,Security,Competitive market price. Flexibility,Accessibility ,Competence and skillful human resource,Quantity is our concern. </span></p>
					</div>
				</div>			
				<div class="col-md-4 col-sm-6  center-blog">
					<div class="block-content ">
						<div class="footer-logo">
							<a class="footer-about-us" href="#" title="Home">
								<img src="<?php echo $this->baseUrl();?>/images/camapplogo.png" alt="Logo">
							</a>
						</div>
						<div class="textwidget text-description">
							<p>
							<?php echo $tr->translate("All copyrights reserved");?> &#x00040; <?php echo $tr->translate("2017");?> <a href="http://cam-app.com/">Cam App Technology</a>					

							</p>
						</div>
						<div class="footer-social-media">
							<ul class="social">
								<li><a class="facebook" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a class="google-plus"  href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
								<li><a class="twitter" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
								<li><a class="youtube" href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>		
				<div class="col-md-4 col-sm-6 right-blog">
					<div class="block-content ">
						<h4><span class="footer-title"><?php echo $tr->translate("Contats Us");?></span></h4>
						<p>
							<span class="value">info@cam-app.com </span>
							<br>
							<span class="value">012 404 192 / 070 756 457 </span>
						</p>
					</div>
					<div class="block-content ">
						<h4><span class="footer-title"><?php echo $tr->translate("Address");?></span></h4>
						<p>
						<span class="value">#188ZB, Street 156,Sangkat Teuk Laak II, Khan Toul Kork ,Phnom Penh </span></p>
					</div>
				</div>		
			</div>			
		</div>			
	</footer>
	