<?php $db = new Application_Model_DbTable_DbVdGlobal();
$lang =$db->getLaguage();
$session_lang=new Zend_Session_Namespace('lang');
$session_lang->lang_id;
?>
	<div class="widget block block-static-block">
    <div class="float-bar hidden-xs hidden-sm hidden-md">
			<div class="float-bar-content">
				<ul class="items">
					<li class="item"><a href=""><span class="fa fa-plus-square">&nbsp;</span><span>Posts Ads</span></a></li>
					<li class="item"><a href=""><span class="fa fa-sign-in">&nbsp;</span><span>Login</span></a></li>
					<li class="item"><a href=""><span class="fa fa-user">&nbsp;</span><span>Register</span></a></li>
					<li class="item">
					<?php if (!empty($lang)) foreach ($lang as $rs){ 
					if ($session_lang->lang_id!=$rs['id']){
					?>
						<a href="" href="#" title="<?php echo $rs['title'];?>" onclick="changeLange(<?php echo $rs['id'];?>);" >
							<img src="<?php echo $this->baseUrl();?>/images/<?php echo $rs['iconImage'];?>" > 
						</a>
					<?php }
						}?>
					</li>
					<li class="item"><a href="#"><span class="fa fa-comments-o">&nbsp;</span><span>Live Chat</span></a></li>
				</ul>
			</div>
		</div>
	</div>