<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate('ADD_NEW_PROMOTION');?></title>
<form id='add_slide' action="<?php echo $this->url(array('module'=>'other','controller'=>'promotion','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:5px;">
	<tr class="header">
			<td><?php echo $tr->translate('ADD_NEW_PROMOTION');?></td>
	</tr>
	<tr>
		<td>
		<fieldset>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate('TITLE');?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="title" name="title" value="" type="text"></td>
							<td><?php echo $tr->translate('PHOTO');?> (width:970px)</td>
							<td><input required="true" class="fullside" id="photo" name="photo" type="file"></td>	
							</tr>
						<tr>
							<td><?php echo $tr->translate('STATUS');?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1"><?php echo $tr->translate('ACTIVE');?></option>
								    <option value="0"><?php echo $tr->translate('DEACTIVE');?></option>
								</select></td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
	<tr class="footer_button">
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
					iconClass="dijitIconClear" />
			<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
					iconClass="dijitEditorIcon dijitEditorIconSave" />  
			<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVE_NEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
					iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox"); 
require(["dijit/Editor"]);
</script>
				