<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<title><?php echo $tr->translate('ADD_NEW_TERM_CONDICTION');?></title>
<form id='add_help' action="<?php echo $this->url(array('module'=>'other','controller'=>'help','action'=>'add')); ?>" enctype="application/x-www-form-urlencoded" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr class="header">
			<td><?php echo $tr->translate('ADD_NEW_TERM_CONDICTION');?></td>
	</tr>
	<tr>
		<td>
		<fieldset>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td valign="top"><?php echo $tr->translate('TITLE');?></td>
							<td valign="top" ><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="help_title" name="help_title" value="" type="text"></td>
							<td valign="top"><?php echo $tr->translate('STATUS');?></td>
							<td valign="top"><select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
								    <option value="1"><?php echo $tr->translate('ACTIVE');?></option>
								    <option value="0"><?php echo $tr->translate('DEACTIVE');?></option>
								</select>
						    </td>
						</tr>
						<tr>
							<td colspan="4">
								<textarea class="ckeditor" dojoType="dijit.form.SimpleTextarea" id="description" name="description"></textarea>
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
	<tr class="footer_button">
		<td align="center">
			<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
				iconClass="dijitIconClear" /> 
			<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
				iconClass="dijitEditorIcon dijitEditorIconSave" /> 
			<input type="submit" value="<?php echo $tr->translate('SAVE_NEW');?>" label="Save&New" id="save_new" dojoType="dijit.form.Button" name="save_new"
				iconClass="dijitEditorIcon dijitEditorIconSave"/> 
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
dojo.require("dijit.form.Textarea"); 
</script>
				