<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('EDIT_ARTICLE')); 
echo $this->headTitle();
$frm = $this->frm;
$db = new MenuManager_Model_DbTable_DbArticle();
$countlang = count($this->lang);
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<style>
div.cke_contents.cke_reset {
    height: 600px !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form action="<?php echo $this->url(array('module'=>'menu-manager','controller'=>'article','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				if(alias_require==0){ alert("Please check your title alias again.");return false;}
				return true;
			}

			return false;
	</script>
		
	<table cellspacing="20" style="margin: 0 auto; width: 100%">
		<tr>
			<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('EDIT_ARTICLE')?></strong></legend>
					<table cellspacing="20" width="100%">
						<tr>
							<td align="left" valign="top" width="70%">
							<?php if ($countlang>1){?>
								<div id="mainTabContainer" style=" position:relative; width:750px; display:block; height: 820px;" dojoType="dijit.layout.TabContainer" region="center" >
					      	<?php }?>		
					      	<?php $alias=''; foreach($this->lang as $key=> $rs){ if ($key<1){ $alias = str_replace(' ','',$rs['title']);} $lang = $db->getArticleTitleByLang($this->id, $rs['id']);?>
					      			<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate(strtoupper($rs['title']));?>" selected="true">
										<table cellspacing="5" width="100%">
											<tr>
												<td><?php echo $tr->translate('TITLE')?></td>
												<td>
													<input   type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title'];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
													<?php //echo $frm->getElement('title');?>
												</td>
											</tr>
											<tr><td colspan="2"><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?></td></tr>
											<tr>
												<td colspan="2" style="height: 500px; vertical-align: top;">
													<textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $lang['description'];?></textarea>
												</td>
											</tr>
										</table>
									</div>
								<?php }?>
							<?php if ($countlang>1){?>
								</div>
							<?php }?>
							</td>
							<td width="30%" style=" vertical-align: top;">
								<table cellspacing="5" width="100%">
									<tr>
										<td><label id="message" style="color: red;"></label>
										<?php echo $frm->getElement('title_alias');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate('CHOOSE_CATEGORY')?></td>
									</tr>
									<tr>
										<td><?php echo $frm->getElement('category');?></td>
									</tr>
									<tr><td><?php echo $tr->translate('STATUS')?></td></tr>
									<tr>
										<td><?php echo $frm->getElement('status');?></td>
									</tr>
								</table>
							</td>								
						</tr>
						<tr>
							<td>
					
						
						</td>
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
			<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
				iconClass="dijitIconUndo" onclick="window.history.back();"/>
				<input class="button_success" type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>	
	<input type="hidden" id="agent" name="agent" value="0" />	
</form>
<script>
var alias_require=0;
	var old_alias="<?php echo $this->row['alias_article'];?>";
	function generateAlias(alias){
		title = dijit.byId('title'+alias).get('value');
		var title_alias = title.split(' ').join('-');
		title_alias = (title_alias.split('?').join('-')).split('"').join('-');
		dijit.byId("title_alias").attr('value',title_alias);
		//if(old_alias!=""){
			//dijit.byId('title_alias').set('value',old_alias);
		//}
		checkTitle();
	}
	url_CheckTitle = '<?php echo $this->url(array('module'=>'menu-manager','controller'=>'article','action'=>'check-title-alias'));?>';
	function checkTitle(){
		title_alias = dijit.byId('title_alias').get('value');
		if(title_alias==old_alias){
			document.getElementById('message').innerHTML ='';
			alias_require=1;
			return false;
		}
		dojo.xhrPost({
			url:url_CheckTitle,	
			content:{ 
				'title_alias': title_alias
			},
			handleAs:"json",
			load: function(data) {	
				if(data !== false ){
			   		document.getElementById('message').innerHTML ='Alias is duplicated you can set new alias or clear alias will auto generate.';
			   		dijit.byId('title_alias').focus();
			   		alias_require=0;
				}else{
					document.getElementById('message').innerHTML ='';
					alias_require=1;
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function checkSpcialCharFortitle(event){
        if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 34 || event.keyCode == 32 || event.keyCode == 63 || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
            event.returnValue = true;
            return;
         }
         event.returnValue = false;
      }
	 function checkSpcialChar(event){
         if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
             event.returnValue = true;
             return;
          }
          event.returnValue = false;
       }
</script>
