<title>Add Package</title>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>	
<?php  $package= $this->frm_package;?>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'menu-manager','controller'=>'package','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
	<table cellspacing="10" width="45%" style="margin: 0 auto;">
		<tr>
			<td>
			<fieldset>
						<legend align="center" ><strong><?php echo $tr->translate("New Package");?></strong></legend>
						<table style="margin: 0 auto; width: 95%;" cellspacing="10">
							<tr>
								<td><?php echo $tr->translate("Package Name")?></td>
								<td><?php  echo $package->getElement('package_name');?>
									<?php  echo $package->getElement('id');?>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Date")?></td>
								<td><?php  echo $package->getElement('date');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Allow Post")?></td>
								<td><?php  echo $package->getElement('allow_post');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Price")?></td>
								<td><?php  echo $package->getElement('price');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Allow Show")?></td>
								<td><?php  echo $package->getElement('allow_show');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Amount Store")?></td>
								<td><?php  echo $package->getElement('amount_store');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Is Free")?></td>
								<td><?php  echo $package->getElement('is_free');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Description")?></td>
								<td><?php  echo $package->getElement('note');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("Status")?></td>
								<td><?php  echo $package->getElement('status');?></td>
							</tr>
							<tr>
								<td colspan="2" align="center">
										<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
										<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('Edit');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</table>	
			</fieldset>		
			</td>
		</tr>
	</table>	
</form>