<div style="clear: both;"></div>
<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>Slide Show</title>
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
<script type='text/javascript' src='<?php echo $this->baseUrl();?>/template/js/chosen.jquery.mine.js'></script>
<link href="https://fonts.googleapis.com/css?family=Hanuman|Montserrat" rel="stylesheet">
<link rel='stylesheet' id='boostrat-style-css'  href='<?php echo $this->baseUrl();?>/template/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='boostrat-chosen-css'  href='<?php echo $this->baseUrl();?>/template/css/chosen.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='main-style-custom-css'  href='<?php echo $this->baseUrl();?>/template/css/custom.css' type='text/css' media='all' />
<link rel='stylesheet' href='<?php echo $this->baseUrl();?>/template/css/style.css' type='text/css' />

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<style>
td {
    font-size: 16px;
    padding: 0px; 
    border-left: none;
    border-top: none;
    text-align: center;
}
</style>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
var district_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete: true,
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		//class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
		 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete: true,
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		//class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
	  }
		}, "commune");
		new dijit.form.FilteringSelect({
		store: village_store,
		autoComplete: true,
		required: false,		           
		name: "village",
		id: "village",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				vill = dijit.byId('village').get('value');
				if(vill==-1){
					showPopupVillage();
				}
			}
		}, "village");
});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
		dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>
<style>
.slideshow a{color: #333333;}
</style>
<?php 
		$stringPagination = '<script type="text/javascript">
		$(document).ready(function(){
		$("#exportExcel").tablesorter();
		 
		$("#exportExcel").tablesorter().tablesorterPager({container: $("#pagination_exportExcel"),size: 50});
		$("input:.pagedisplay").focus(function(){ this.blur(); });
		 
		function changeColor(){
		alert("change color on mouse over");
		}
		});
		</script>
		<div id="pagination_exportExcel" class="pager" >
		<form >
		<table  style="width: 200px;"><tr>
		<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
		<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
		<td><input type="text" class="pagedisplay"/></td>
		<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
		<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
		<td><select class="pagesize" >
		<option value="10">10</option>
		<option value="20">20</option>
		<option value="30">30</option>
		<option value="40">40</option>
		<option selected="selected" value="50">50</option>
		<option value="60">60</option>
		<option value="70">70</option>
		<option value="80">80</option>
		<option value="90">90</option>
		<option value="100">100</option>
		</select>
		</td>
		</tr>
		</table>
		</form>
		</div>';
?>
<form method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%" >
		<tr>
			<?php $search = $this->search;
			?>
			<td><input dojoType="dijit.form.TextBox"  placeholder="Search..." id="advance_search" name="advance_search" value="<?php echo $search['advance_search'];?>" type="text" class='fullside'></td>
			<td>
				<select onchange="getControll();" dojoType="dijit.form.FilteringSelect" id="category_search" name="category_search" class='fullside'>												
					<option value="-1" selected="selected"><?php echo $tr->translate("Choose Category");?></option>
					<?php 
						if(!empty($this->rscate)){
							foreach($this->rscate as $rsc){
						?>
							<option <?php if($search['category_search']==$rsc['id']){echo "selected";}?> value="<?php echo $rsc['id'];?>" ><?php echo $rsc['name'];?></option>
						<?php }
						} 
					?>
				</select>
			</td>
			<td><input dojoType="dijit.form.DateTextBox"  id="start_date" name="start_date" value="<?php echo $search['start_date'];?>" type="text" class='fullside'></td>
			<td><input dojoType="dijit.form.DateTextBox"  id="end_date" name="end_date" value="<?php echo $search['end_date'];?>" type="text" class='fullside'></td>
      		<td></td>
      	</tr>
		<tr>
			<td>
				<select dojoType="dijit.form.FilteringSelect" id="status_used" name="status_used" class='fullside'>
					<option value="-1"><?php echo $tr->translate("Choose Status");?></option>
					<option <?php if($search['status_used']==1){echo "selected";}?> value="1"><?php echo $tr->translate("Publish");?></option>
					<option <?php if($search['status_used']==0){echo "selected";}?> value="0"><?php echo $tr->translate("Suspended");?></option>
				</select>
			</td>
			<td>
				<select dojoType="dijit.form.FilteringSelect" id="province" name="province" onchange="filterDistrict();" class='fullside'>
					<option value="-1"><?php echo $tr->translate("Choose Location");?></option>
					<?php 
						if(!empty($this->rslocation)){
							foreach($this->rslocation as $rsl){
						?>
							<option <?php if($search['province']==$rsl['id']){echo'selected="selected"';}?> value="<?php echo $rsl['id'];?>"><?php echo $rsl['province_name'];?></option>
						<?php }
						} 
					?>
				</select>
			</td>
			<td><input id="district" ></td>
      		<td><input id="commune" ></td>
      		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit">Search</button></td>
		</tr>
		<tr>
			<td colspan="5">
				<div class="form-value" style="width:100%; margin-left: -25px;"><label id="lbl_controlsearch" style="width:100%"></label></div>
			</td>
		</tr>
	</table>
	
</form>
 <div >
  <table class="collape tablesorter" id="exportExcel" width="100%">
	   <thead>
		    <tr>
			    <th class="tdheader header"><?php echo $tr->translate('No');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Ads Code');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Title');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Price');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('User');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Phone');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Category');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Location');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Start Date');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('End Date');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Status');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Image');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Publish');?></th>
			    <th class="tdheader header"><?php echo $tr->translate('Viewer');?></th>
		      </tr>
	     </thead>
     	</tbody>
     <?php $r=0; if(!empty($this->rsads)){foreach ($this->rsads as $key =>$row){
	      if($r%2==0)$attb='normal';
	      else $attb='alternate';
     	  $r++;
      	?>
	       <tr align="center" class='slideshow <?php echo $attb; ?>'>
			  	<td style="border:1px solid #ccc;padding:1px;" align="center"><?php echo $key+1;?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a href="<?php echo $this->baseUrl().'/other/slideshow/edit/ads/'.$row['alias'];?>"><?php echo $row['ads_code'];?></a></td>
			  	<?php 
				  	$str1 = utf8_encode($row['ads_title']);
				  	$title = substr($str1, 0, 120);
			  	?>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/default/listads/detail/ads/'.$row['alias'];?>"><?php echo utf8_decode($title);?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/menu-manager/ads/update-post/adsid/'.$row['id'];?>"><?php echo $row['price'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/menu-manager/ads/update-post/adsid/'.$row['id'];?>"><?php echo $row['customer_name'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/menu-manager/ads/update-post/adsid/'.$row['id'];?>"><?php echo $row['phone1'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/menu-manager/ads/update-post/adsid/'.$row['id'];?>"><?php echo $row['category_name'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><a target='_blank' href="<?php echo $this->baseUrl().'/menu-manager/ads/update-post/adsid/'.$row['id'];?>"><?php echo $row['province_name'];?></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo date("d/m/Y",strtotime($row['publish_date']));?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo date("d/m/Y",strtotime($row['expired_date']));?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['status'];?></td>
			  	<td style="border:1px solid #ccc;padding:1px;text-align: center;" ><a target='_blank' href="<?php echo $this->baseUrl().'/default/listads/detail/ads/'.$row['alias'];?>"><img src="<?php echo $this->baseUrl().'/images/adsimg/'.$row['image_feature'];?>"  style="max-height:30px;"/></a></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['status_use'];?></td>
			  	<td style="border:1px solid #ccc;padding:1px;"><?php echo $row['viewer'];?></td>
		  </tr>
      <?php }?>
     </tbody>
     </table>
   </div>
  <div class="footer_list"><?php echo $stringPagination; ?><span class="row_num"><?php echo $tr->translate('NUM-RECORD')." ".count($this->row)?></span></div>
    <?php }else{?>
    	</table></div><center style="font-size:18pt;"><label id="data_table">No record</label></center></form>
    <?php }?> 
  <script>
   var url_getcontrol = '<?php echo $this->url(array('module'=>'default','controller'=>'listads','action'=>'getcontroller'));?> ';
   function getControll(){
	   var category_search = dijit.byId('category_search').get("value"); 
		   $.ajax({
				url: url_getcontrol,
				type: "post",
				data:{'category_id':category_search},
				success: function(data){
					document.getElementById('lbl_controlsearch').innerHTML=data;
					var noResult = jQuery(".form-select").data('noResult');
					jQuery(".form-select").chosen({});
				},
				error:function(err){
					alert(err);
				}
			});
	}	
  </script>