<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CONTRACTOR'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'contractor','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend><strong><?php echo $tr->translate("ADD_CONTRACTOR");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("HUSBAND_INFO")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?>*</td>
							<td><?php  echo $frm->getElement('name_kh');?></td>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><?php  echo $frm->getElement('nationality');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('sex');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('national_id');?></td>
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('age');?></td>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $frm->getElement('phone');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("WIFE_INFO")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php echo $frm->getElement('hname_kh');?></td>
							<td><?php 	echo $tr->translate("NATIONALITY")?></td>
							<td><?php   echo $frm->getElement('p_nationality');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('ksex');?></td>
						</tr>
						<tr>
							<td><?php 	echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php   echo $frm->getElement('wife_nation_id');?></td> 
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('p_age');?></td>
							<td><?php 	echo $tr->translate("PHONE")?></td>
							<td><?php  	echo $frm->getElement('lphone');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("CURRENT_ADDRESS")?></td>
						</tr>
						<tr>
							<td colspan="6"><?php  echo $frm->getElement('current_address');?></td>
						</tr>
						<!-- <tr>
							<td><?php echo $tr->translate("PROVINCE")?></td>
							<td><?php  echo $frm->getElement('province');?></td>
							<td><?php echo $tr->translate("DISTRICT")?></td>
							<td><input id="district" required="true" ></td>
							<td><?php echo $tr->translate("COMMUNE")?></td>
							<td><input id="commune" ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("VILLAGE")?></td>
							<td><input id="village" ></td>
							<td><?php echo $tr->translate("STREET_NO")?></td>
							<td><?php  echo $frm->getElement('street');?></td>
							<td><?php echo $tr->translate("GROUP")?></td>
							<td><?php  echo $frm->getElement('group');?></td>
						</tr> -->
						<tr>
							<!-- <td><?php echo $tr->translate("HOUSE_NO")?></td>
							<td><?php  echo $frm->getElement('house');?></td>-->
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top"><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
							<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<?php 
// echo $this->frm_popup_district;
// echo $this->frm_popup_village;
// echo $this->frm_popup_comm;
?>
<script type="text/javascript">

//var d_datastore  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->clienttype));?> );
//var joint_doc_type_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode($this->clienttype));?> );
//var district_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );
//var commune_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );
//var village_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );
//var adistrict_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );
//var dcommune_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );
//var qvillage_store  = getDataStorefromJSON('id','name', <?php //print_r(Zend_Json::encode(array()));?> );


dojo.ready(function(){
	
	try{
	
//	new dijit.form.FilteringSelect({
//	store: district_store,
//	autoComplete: true,
//	required: false,		           
//	name: "district",
//	id: "district",
//	searchAttr: "name",
//	class: 'fullside',
//	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
//		onChange: function() {
//			district = dijit.byId('district').get('value');
//			if(district==-1){
//				showPopupdistrict();
//				}
//				filterCommune();
//		}  
//	}, "district");
	 
//	new dijit.form.FilteringSelect({
//	store: commune,
//	autoComplete: true,
//	required: false,		           
//	name: "commune",
//	id: "commune",
//	searchAttr: "name",
//	class: 'fullside',
//	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
//		onChange: function() {
//			commune = dijit.byId('commune').get('value');
//			if(commune==-1){
//				showPopupCommune();
//			}
//			else{
//				filterVillage();
//			}'
// 		}
//	}, "commune");

	 
//	new dijit.form.FilteringSelect({
//	store: village_store,
//	autoComplete: true,
//	required: false,		           
//	name: "village",
//	id: "village",
//	searchAttr: "name",
//	class: 'fullside',
//	missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
//		onChange: function() {
//			vill = dijit.byId('village').get('value');
//			if(vill==-1){
//				showPopupVillage();
//			}
//		}
//	}, "village");



	}catch(e){
		alert(e);
	}
});

//url_getdistrict = '<?php //echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
/*function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district').set('store', district_store);
		},
		error: function(err) {
			alert(err);
		}
	});	
}*/
//url_getcommune = '<?php //echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
/*function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}*/
//url_getvillage = '<?php //echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
/*function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village').set('store', village_store);
		},
		error: function(err) {
			alert(err);
		}
	});
}

function showPopupVillage(){
	communeid = dijit.byId('commune').get('value');
	if(communeid!=-1){
		province_id = dijit.byId('province').get('value');
		dijit.byId('province_name').attr('value',province_id);
		dijit.byId('province_name').set('readOnly',true);

		district_name=province_id = dijit.byId('district').get('value');
		dijit.byId('district_name').attr('value',district_name);
		dijit.byId('district_name').set('readOnly',true);

		dijit.byId('commune_name').attr('value',communeid);
		dijit.byId('commune_name').set('readOnly',true);
		dijit.byId('frm_village').show();
	}else{
		alert('please select commune first');
		dijit.byId('commune').focus();
	}
}
function showPopupCommune(){
	district = dijit.byId('district').get('value');
	if(district!=-1){
		dijit.byId('district_nameen').attr('value',district);
		dijit.byId('district_nameen').set('readOnly',true);
		dijit.byId('frm_commune').show();
	}else{
		alert('please select district first');
		dijit.byId('district').focus();
	}
}
function showPopupdistrict(){
	province_id = dijit.byId('province').get('value');
	if(province_id!=0){
		dijit.byId('province_names').attr('value',province_id);
		dijit.byId('province_names').set('readOnly',true);
		dijit.byId('frm_district').show();
	}else{
		alert('please select province first');
		dijit.byId('cprovince').focus();
	}
}
*/
//var district_url = '<?php //echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-district'));?>';
/*function addNewDistrict(){
	if(dijit.byId('frm_district').validate()) {
		dojo.xhrPost({
			url:district_url,	
			form:dojo.byId('form_district'),
			handleAs:"json",
			load: function(data) {	
				var myNewItem1 = {					
						id: data,
						name: dijit.byId('pop_district_name').get('value')+' - '+dijit.byId('pop_district_namekh').get('value'),
				};			
				addDataToSelectbox(dijit.byId('district'), district_store, myNewItem1, data);	
				dijit.byId('frm_district').reset();
				dijit.byId('frm_district').hide();
			},
			error: function(err) {
				alert(err);
			}
		});	
	}
}*/
//var commune_url = '<?php //echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insertcommune'));?>';
/*function addNewCommune(){
	if(dijit.byId('frm_commune').validate()) {
		dojo.xhrPost({
			url:commune_url,	
			form:dojo.byId('form_commune'),
			handleAs:"json",
			load: function(data) {	
				communeen = dijit.byId('commune_nameen').get('value');
				communekh = dijit.byId('commune_namekh').get('value');
				var Itemcommune = {					
						id: data,
						name: communeen+' - '+communekh,
				};			
				addDataToSelectbox(dijit.byId('commune'), commune_store, Itemcommune, data);
				dijit.byId('frm_commune').reset();
				dijit.byId('frm_commune').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}*/
</script>